### ISSUE TITLE
Entity edit form should provide the user a link to the applied/suggested record, or redirect them

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-client#100]
Currently the entity edit pages just display a success/fail message when the form is submitted. Instead, if the submit/apply is successful then the user should be provided a link to the updated/submitted record or be directed to that record immediately.

**Comment by malachig** [comment]
Adding a few notes on this topic from the gitter.im chat.  

At the end point of each edit I was wishing that I was automatically returned to either (1) the `Summary View` for that variant if I did `Apply` OR (2) to the diff view in `Variant Talk` -> `Revisions` if I did `Submit Revision for Review`.

**Comment by jmcmichael** [comment]
Just pushed an update to master that adds links to entity edit success messages. Since 'Apply' doesn't currently create a revision, I haven't changed its success msg but when the server provides revisions it'll be easy to add.
