### ISSUE TITLE
Add link to admin interface in bottom bar?

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-client#116]
For those of us who use the admin interface regularly it might be nice to have a link hidden away somewhere on the page.

**Comment by acoffman** [comment]
I believe that if you are logged in and an admin, you will see a link if you click the arrow by your username.

**Comment by obigriffith** [comment]
Ah. This appears only when browsing at http://127.0.0.1:3000, not at http://127.0.0.1:3001 as I was doing. I didn't realize this distinction. Should we always be using the former?

**Comment by malachig** [comment]
I think this was recently added via: https://github.com/genome/civic-client/issues/107

**Comment by jmcmichael** [comment]
Yeah I opened and closed that one pretty quick, easy to miss.

Regarding ports, 3001 is the dev install running from your civic-client directory served by node/gulp. If you hit port 3000, you'll get the latest production version served from civic-server/public. So you should use port 3001 unless you really want to see the latest production build of the client.

That said, I think the admin link in the user dropdown feature made it into the ASCO production build, so it *should* work from port 3000 - check to see if you're running the latest civic-server.

**Comment by obigriffith** [comment]
Yeah. I see it now at at http://127.0.0.1:3000 but not at http://127.0.0.1:3001. This is a nice way of handling this issue. I think we can close this issue.

**Comment by jmcmichael** [comment]
Hmm.. Now I'm not seeing it myself on the latest civic-client, let me see what's up.

**Comment by jmcmichael** [comment]
Nevermind, it's there - had just done a db re-import and forgot to make myself admin.
