### ISSUE TITLE
Mutation Assessor formatting within MyVariant.info pop up is strange

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#1167]
<img width="468" alt="Screen Shot 2019-08-15 at 2 10 03 PM" src="https://user-images.githubusercontent.com/8527125/63119737-76ab0680-bf66-11e9-840d-c409d20c4dc1.png">

Noticed to be a problem for the following variants:
https://civicdb.org/events/genes/20/summary/variants/38/summary#variant
https://civicdb.org/events/genes/20/summary/variants/36/summary#variant

**Comment by kkrysiak** [comment]
Remove brackets and quotes is I think the only thing needed.

**Comment by susannasiebert** [comment]
I think this is a problem, potentially, with the frontend not expecting these fields to be arrays. I think myvariant.info will sometime return these fields as arrays and sometimes as single values.

**Comment by jmcmichael** [comment]
Yeah, this is pretty much what we're getting from MyVariantInfo:

<img width="685" alt="Screenshot 2019-08-15 14 18 31" src="https://user-images.githubusercontent.com/132909/63120266-95f66380-bf67-11e9-96f4-a54532f7178b.png">

Currently MutationAssessor isn't included in the list of fields that might be returned as a string OR an array, I'll check into handling these values better so they don't look so ugly. Probably can't do anything about the repeated "." but can remove the array brackets at least.
