### ISSUE TITLE
Drug entry currently broken in add/edit evidence form

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-client#117]
Drug entry is currently broken in the add/edit evidence form.

**Comment by malachig** [comment]
There is an 'Add Drug' button now, but when I use it to add a drug and then hit `Submit Revision for Review`, nothing happens.  If I hit `Apply` I get a message that it was successfully applied.  But I don't think it propagates correctly.

**Comment by jmcmichael** [comment]
The drug multi-input field now works as expected, and Adam is working on modifying the backend to handle the requests it now sends. Currently, you'll get a 400 Bad Request error if you attempt to add a drug that isn't currently in the civic db, and if you delete all of the drugs, the server will return an error as well. These should be fixed shortly. I'm closing this as the remaining issues with this features relate to the server.
