### ISSUE TITLE
Orange vs Green Guidance Text on EIDs

### ISSUE THREAD

**Issue by arpaddanos** [genome/civic-client#1172]
Adding guidance text (aka WARNING text) on EIDs and perhaps also on the EID scroll display, which emphasizes the potential problems with orange EIDs. (using image for guidance). It may also be worth considering to pass this distinction on to entities who use CIViC as a client and might be displaying EID information. 
<img width="925" alt="EID_Warning_Screenshot" src="https://user-images.githubusercontent.com/13948978/63218512-fcbf7c80-c121-11e9-98bd-841cee824e48.png">

**Comment by arpaddanos** [comment]
With this change, default view could also be returned to show all non-rejected EIDs, and therefore also all variants that have have at least one non-rejected EID.

**Comment by kkrysiak** [comment]
Is this the same or is there a nuance I'm not seeing? https://github.com/griffithlab/civic-client/issues/1192
