### ISSUE TITLE
Evidence form should reset or give more indication that something has happened after submit

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-client#118]
I just submitted a new evidence statement to an existing variant (DNAJB1-PRKACA):
https://civic.genome.wustl.edu/#/events/genes/17/summary/variants/107/summary

I then went to the admin interface and accepted it and that all worked pretty well. However, when I hit "submit evidence for inclusion" it was very subtle to notice that anything happened. I noticed a really quick loading bar as a flash but otherwise couldn't tell that anything had happened until I scrolled up to the top of the page and saw the "your new evidence item was submitted succesfully". The form should either reset or at least bring you to the top so you see that status message. There is perhaps some utility to leaving the fields filled as they were for cases where you are entering several related statements for a single paper. But, we need more of a visual cue for the successful submission.

**Comment by malachig** [comment]
Maybe the "your new evidence item was submitted succesfully" could be displayed at the top *and* bottom of the page?

**Comment by jmcmichael** [comment]
Yeah I agree, issue #114 addresses most of the problems you raised. And as a quick fix I think I will display the success message near the buttons as @malachig suggested.

My idea is to replace the entire form with a more extensive success message that informs the user what happened, where their submission is, next steps to get it accepted, and other things they can do with the system.
