### ISSUE TITLE
Add "Dominant Negative" to Functional Clinical Significance

### ISSUE THREAD

**Issue by arpaddanos** [genome/civic-client#1189]
CIViC is currently tasked to capture and annotate TP53 functional evidence. Evidence types have broadly fallen into Gain of Function, Loss of Function, Neomorphic and Dominant Negative (DN) annotations. We currently lack in CIViC the capability to annotate the DN category, and I suggest this category be added to the Clinical Significance of the Functional Evidence Type.

**Comment by arpaddanos** [comment]
The following search of functional EIDs with evidence explicitly discussing DN effects, yet lacking consistent annotations, demonstrates the need for a consistent annotation category for this type of evidence.

https://civicdb.org/search/evidence/253caffa-f6db-4571-a062-34e19a212c81

**Comment by kkrysiak** [comment]
@arpaddanos to figure out icon, tool tip, help text.
