### ISSUE TITLE
evidence w/ combination drugs appears to only return a single drug in adv. search response

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-client#1200]
Examples:
https://civicdb.org/search/evidence/bf5f0b56-1095-4a4b-b6bf-6e8bc730292f
(ASS1)

https://civicdb.org/search/evidence/5caf4e61-030f-4864-b7ef-3684386ae86b
EID1845 and 1046

If you click through to the evidence record, you'll see multiple drugs listed. Looks like a server issue as the API is only returning a single drug from the adv. search API.

**Comment by susannasiebert** [comment]
It appears that if you search by drug name, only the drug names matching the query will be returned, not all of the drugs. If you search by evidence item id, it displays all of the linked drugs. Digging more as to why that is.

**Comment by ahwagner** [comment]
See this evidence item:
https://civicdb.org/events/genes/30/summary/variants/75/summary/evidence/1219/summary#evidence

Should return from this search:
![image](https://user-images.githubusercontent.com/811065/71688601-bf245e80-2d65-11ea-8052-da4ec4a8151b.png)

**Comment by susannasiebert** [comment]
I have confirmed that the advanced search by multiple drugs is a separate bug. I will make a new issue for it.
