### ISSUE TITLE
Variant with no EIDs

### ISSUE THREAD

**Issue by cgrisdale** [genome/civic-client#1217]
PIK3CA variant D549N says it has one pending item when you scroll over the variant name, but there are no EIDs in the evidence grid even with the option set to 'show all'. I checked all PIK3CA variants that only have a single pending evidence item and two others seem to have the same issue: R1023Q and G1049A.
Is this a known issue?

**Comment by ahwagner** [comment]
Reviewed and verified. This should be an orphaned variant, but instead is counted as a "variant with submitted evidence".

Thanks for the bug report, @cgrisdale.

**Comment by ahwagner** [comment]
Issue moved to [griffithlab/civic-server #542](https://github.com/griffithlab/civic-server/issues/542) via [**ZenHub**](https://www.zenhub.com/)

**Comment by kkrysiak** [comment]
<img width="1011" alt="Screen Shot 2019-10-10 at 2 27 02 PM" src="https://user-images.githubusercontent.com/8527125/66600029-3b921180-eb6a-11e9-8d42-265cac481305.png">
https://civicdb.org/events/genes/37/summary/variants/884/summary/evidence/2072/summary#evidence
