### ISSUE TITLE
drug interaction type not displaying on evidence summaries

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-client#1228]

**Comment by susannasiebert** [comment]
The same problem applies to the assertion summary, e.g.: https://civicdb.org/events/assertions/19/summary

**Comment by jmcmichael** [comment]
Drug Interaction Type has its own attribute display, beneath the drug list, on assertions ('Substitution' in the case of AID19) - so it's there, but not displayed in the same way as on the evidence summary. Which is confusing, I'll switch the assertion display of drugs/interaction to match the evidence summary.
