### ISSUE TITLE
Edit evidence page has evidence direction mislabeled as evidence type

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-client#123]
See screenshot. "Evidence Type" is listed twice. But, one of them is actually supposed to be evidence level. I see this on edit evidence page but not add new evidence page.

![screenshot 2015-05-29 10 13 35](https://cloud.githubusercontent.com/assets/1638042/7885793/a31b07d0-05eb-11e5-965b-a1c0b5f32f17.png)

**Comment by malachig** [comment]
It looks like the second label should be "Evidence Direction" perhaps?

**Comment by jmcmichael** [comment]
Fixed.
