### ISSUE TITLE
Implement NCCN guidelines options in add/edit/search forms as a typeahead instead of hard-coded select

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#1255]
I've noticed that there are new NCCN professional guidelines such as Acute Lymphoblastic Leukemia (pediatric).

I don't think we have a plan for how to enter these moving forward. I believe this was a manual thing.

**Comment by kkrysiak** [comment]
This is actually relevant to AID28

**Comment by susannasiebert** [comment]
We should make this available and editable in the admin interface.

**Comment by susannasiebert** [comment]
It's currently not a table but an enum, so we would need to make it its own table (which is probably a good idea anyway).
