### ISSUE TITLE
Add link to ProteinPaint CIViC track in CIViC gene summary

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#1258]
We are working with ProteinPaint to have gene and variant level cross linking. After preliminary discussion with Dr. Zhang and members of her team the following action items were proposed: 

1. ProteinPaint would pull in monthly CIViC releases and create a CIViC "track" within ProteinPaint similar to what is currently done for ClinVar or Cosmic. CIViC data releases can be found here: https://civicdb.org/releases
2. CIViC would create a Gene-level link to ProteinPaint (we should confirm with them how this is named and whether to use a logo they approve of). This link would for example take the user from [CIViC BRAF page](https://civicdb.org/links/gene/5) to [ProteinPaint BRAF page](https://pecan.stjude.cloud/proteinpaint/BRAF).  The URL would be crafted so that by default the CIViC track would be loaded in ProteinPaint and perhaps some other defaults (e.g. pediatric mutations, or COSMIC?, or ClinVar?).  In the CIViC page, this could look similar to how we currently link to DGIdb at the gene level.
3. ProteinPaint would create a Gene-level link back to CIViC. Examples for creating these links can be found here: https://griffithlab.github.io/civic-api-docs/#linking
4. The ProteinPaint CIViC track would link individual variants back to the corresponding variant page in CIViC.  Examples for creating these links can be found here: https://griffithlab.github.io/civic-api-docs/#linking
5. CIViC variant records would link to ProteinPaint pages so that when the user arrives at ProteinPaint, the variant is already selected/highlighted in ProteinPaint.  This may require some further discussion with ProteinPaint developers to figure out how to identify the variant correctly.  In the CIViC page the variant link to ProteinPaint could look like what we do for Allele Registry ID.

Other notes:
- If ProteinPaint wishes to use a CIViC logo for linking, logo files can be found here: https://civicdb.org/graphics
- Once the above is close to ready for deployment on both sides we would propose a joint PR announcement to our respective institutions to announce this collaboration between WASHU CIViC and St. Jude ProteinPaint.

**Comment by susannasiebert** [comment]
For 1. I would recommend CIViCpy over parsing our TSVs.

For 4. and 5. we would need to figure out how to associate their variants with ours. I would recommend using the ClinGen Allele Registry as an in between since users are already able to look up CIViC variants by CAID.

**Comment by arpaddanos** [comment]
I would suggest that representation of CIViC EIDs in ProteinPaint be restricted to accepted status. some details like if an EID has is flagged might also be taken into account, but the main issue would be restricting to accepted.

**Comment by susannasiebert** [comment]
If we want to do this we should instruct Xin to import/parse the accepted VCF instead of the accepted and submitted one.

**Comment by malachig** [comment]
Hmmm, right now you won't see too much detail about the evidence associated with each variant until you follow the link which takes you back to CIViC.  There you would see the status and warnings.  

Since we are not conveying any claims about the evidence in ProteinPaint maybe this is okay.

Our current default view of variants when you go to a gene in CIViC is "Show variants with accepted and/or submitted evidence".

I think we should mirror that behavior otherwise it will be confusing as one goes back and forth between a gene view in CIViC and gene view in ProteinPaint.  

I also like this approach because it conveys all the variants that CIViC has some info on, but you go back to CIViC for the full details.

**Comment by susannasiebert** [comment]
The statuses are being outputted in the CSQ field so if they aren’t currently being displayed in protein paint it would be easy to add.

**Comment by arpaddanos** [comment]
It seems that if the links are at the variant level then there should be no problem.
