### ISSUE TITLE
allow users who belong to multiple Organizations (or Sub-Organizations) to choose Organization when moderating

### ISSUE THREAD

**Issue by arpaddanos** [genome/civic-client#1263]
The request is to have a user belong to different groups, and to have CIViC activity be added to the activity totals of the respective group that they are associated with at the time of activity, and to be able to switch this association when desired.

- Admin adds Curators to different subgroups they can be part of
- UI addition: a select tool where subgroup is chosen at any submission instance (EID, Revision, Variant Summary or Coordinates etc). Defaults to last chosen subgroup.
- Past EIDs and activity are already attributed to the group that Curator was member of during the actions. 
- What membership would be displayed on the subgroups member pages? Members can be displayed in multiple groups, with their individual group-specific curation numbers added respectively to each group. 
- There exists a temporary workaround of using Google login for one group and OrcID to curate for anther. These can be combined at a later date.

**Comment by jmcmichael** [comment]
Here are some screenshots from the WIP pull request which show the addition of the org icon and tooltip to clearly convey to users which org will be credited for the action:

**Button with dropdown selector showing org icon:**

![Screenshot 2020-03-05 13 24 06](https://user-images.githubusercontent.com/132909/76017889-fa1d4c80-5ee4-11ea-9708-9c589fc04d53.png)

**Tooltip showing name of selected org:**

![Screenshot 2020-03-05 13 24 11](https://user-images.githubusercontent.com/132909/76017912-05707800-5ee5-11ea-90ca-a6724dd55c2f.png)

**Dropdown showing available orgs w/ icons:**

![Screenshot 2020-03-05 13 24 17](https://user-images.githubusercontent.com/132909/76017936-10c3a380-5ee5-11ea-801b-213104cbe13d.png)

**Reject/Accept buttons w/ org selector dropdowns:**
![Screenshot 2020-03-05 13 24 42](https://user-images.githubusercontent.com/132909/76017979-2042ec80-5ee5-11ea-904c-24e7125a61b4.png)

**Comment by jmcmichael** [comment]
Reopening, client requires refactoring logic to better handle edge cases when a user's most_recent_org doesn't exist in their orgs array, or have no most_recent_org assigned, and updates to templates to handle displaying multiple orgs when necesary.

**Comment by susannasiebert** [comment]
I believe this is now complete.
