### ISSUE TITLE
Make disease that aren't linked to DOID not clickable (harmonize with drug terms)

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#1271]
Currently, all disease terms link to disease ontology whether they have a valid DOID or not. We recently did this for drugs and we would like to have this behavior consistent between entities.

Example: EID7128. This disease is not in DOID.

**Comment by jmcmichael** [comment]
We're generating the URL to a disease's DO record on the server and trasmitting it to the client w/ a 'url' attribute a disease object. For EID7128, the client gets

`url: "http://www.disease-ontology.org/"`,

and for an EID w/ a disease that has a DO record, the client gets

`url: "http://www.disease-ontology.org/?id=DOID:1788"`

I can check to see if the URL contains an id string when determining to display the disease name w/ a link, but it might be more elegant to return a disease object w/ no url attribute, or an empty string, or nil instead to make that logic more clear.
