### ISSUE TITLE
Browse grid filtering on drugs non-intuitive

### ISSUE THREAD

**Issue by susannasiebert** [genome/civic-client#1276]
In the browse grid for evidence & variants, when filtering on the drug field for entries that have many drugs, only the matching drug is displayed. The non-matching drugs get removed from the grid field.

The expected behavior is that all associated drugs for the entry remain and the matching term is bolded.

I believe this might be a frontend issue so I'm assigning @jmcmichael

**Comment by jmcmichael** [comment]
This does look like a server issue. The variant DNMT3A/R882 when loaded initially looks like this:

![Screenshot 2020-01-06 17 00 54](https://user-images.githubusercontent.com/132909/71855435-a211c780-30a6-11ea-88ea-9dc2cc5aa0f1.png)

If I type 'daun' into the Drugs filter, the server returns the DNMT3A/R882 object as:

![Screenshot 2020-01-06 17 00 29](https://user-images.githubusercontent.com/132909/71855471-bce43c00-30a6-11ea-911d-70036f4ad0cd.png)

Note that in the drugs array, it's only returning Daunorubicin. If Idarubicin were also returned, the grid would display that in the row's Drug cell as well.
