### ISSUE TITLE
"Description" title is confusing on evidence form 

### ISSUE THREAD

**Issue by rbilski** [genome/civic-client#130]
Sorry if this has been discussed before. When adding evidence, the section to write the evidence statement in is currently titled "Description." It is not intuitive without reading the help what should go there and seems easily confused with "New Evidence Description". Since we refer to this as evidence everywhere else, maybe "Evidence Statement" and "Support for Inclusion" would be better titles.

**Comment by malachig** [comment]
I agree, I have had this exact same experience when entering new evidence.  I like "Evidence Statement" or maybe "Supporting Evidence Statement".

**Comment by jmcmichael** [comment]
Yeah, I agree. Done!
