### ISSUE TITLE
Deduplicate variant name suggestions

### ISSUE THREAD

**Issue by acoffman** [genome/civic-client#1313]
No need to show MUTATION in the typeahead multiple times for instance

**Comment by acoffman** [comment]
@jmcmichael I went to fix this server side, but it looks like you're actually using the datatables endpoint to power the typeahead, when filtering on variant name in the datatable, this is actually the desired behavior (ie: i type MUTATION and i want the data table to show me all the rows with mutation), so we either need to introduce a new endpoint specifically for this, or you'll need to dedup the names on your end. I'm good with either, just let me know how you want to proceed.

**Comment by jmcmichael** [comment]
What I could do is limit the search to variants of the gene, if specified - so if the gene field is valid, then supply it as another parameter to the datatable query. Presumably the response would then contain no duplicate variant names.

If the gene isn't specified, the typeahead would behave as it currently does, however.
