### ISSUE TITLE
Admin utility merge didn't perform correctly

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#1323]
I merged two IKZF1 variants "Deletion" (keep) and "IKZF1 deletion", however, the evidence items from IKZF1 deletion didn't move over. I also noticed that other IKZF1 variants were viewable in the admin interface but not the UI. I tried a hard refresh and neither of these were resolved.

https://civicdb.org/events/genes/73/summary/variants/2579/summary

**Comment by kkrysiak** [comment]
<img width="474" alt="Screen Shot 2020-02-02 at 1 38 55 PM" src="https://user-images.githubusercontent.com/8527125/73614064-6a247400-45c1-11ea-85ac-d56399e4abc6.png">

**Comment by susannasiebert** [comment]
The problem with not being able to see the other variants in the UI is because they don't have accepted evidence items (which is still the default variant filter on the production instance). Do you have any records of which evidence items were linked to "IKZF1 deletion" before the attempted move?

**Comment by susannasiebert** [comment]
According to the TSVs there were two Evidence Items as of Feb 1st, that belonged to "IKZF1 deletion" : https://civic.genome.wustl.edu/links/evidence_items/7532 and https://civic.genome.wustl.edu/links/evidence_items/7541. Those were successfully moved to "IKZF1 DELETION".

**Comment by kkrysiak** [comment]
Must have been a cache issue or something buggy with my computer.
