### ISSUE TITLE
Search tabs don't reformat when browser window is resized. 

### ISSUE THREAD

**Issue by ShahilPema** [genome/civic-client#1324]
When the CIViC is open in google chrome browser on a 15'' screen, and the window is sized to half the screen, the search tabs are not formatted correctly and partially cover the "Browse," "Search," and "Activity," and "Add" buttons. See attachment (I've cropped out the rest of the screen).
<img width="834" alt="Screen Shot 2020-02-05 at 8 35 25 PM" src="https://user-images.githubusercontent.com/40402702/73906635-724a1100-4858-11ea-8428-76c5a14d1345.png">

**Comment by susannasiebert** [comment]
IMHO this should be addressed during the V2 redesign and not be fixed in V1.
