### ISSUE TITLE
Make CIViC VCF available on the Data Releases page

### ISSUE THREAD

**Issue by susannasiebert** [genome/civic-client#1332]
We now create two nightly VCFs: `nightly-civic_accepted_and_submitted.vcf` and `nightly-civic_accepted.vcf` in the same folder as the TSVs. 
We also create monthly VCFs in the format: `dd-Mon-YYYY-civic_accepted_and_submitted.vcf` and `dd-Mon-YYYY-civic_accepted.vcf` in the same monthly folders as the TSVs (there haven't been any successful runs for these yet; the first one would be March).
These two VCFs should be added to the [Data Releases](https://civicdb.org/releases) page.

**Comment by susannasiebert** [comment]
There is currently no space for adding these VCFs to the table. It was suggested to add tabs to the table, one for VCFs and one for TSVs.

**Comment by susannasiebert** [comment]
It also looks like only the past 25 months are being displayed; we would want to show them all.

**Comment by ahwagner** [comment]
Nightly .vcfs are available for download already, pending UI changes to make these easy to find:

https://civicdb.org/downloads/nightly/nightly-civic_accepted_and_submitted.vcf
https://civicdb.org/downloads/nightly/nightly-civic_accepted.vcf

**Comment by jmcmichael** [comment]
Sounds like tabs + datatable would be the best way to refactor this.
