### ISSUE TITLE
add instructions to docs detailing how to request that a group/subgroup be added

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-client#1338]
Include email address to contact, discuss need for logo, name, description that is markedly different from existing groups.

**Comment by kkrysiak** [comment]
Adapting text below from our "Administrative_form_fills_quicktext" google doc.

We would be happy to create an Organization for your group. To do so, we need the following information. Items 1-5 are required. You can see an example Organizations page [here](https://civicdb.org/organizations/1/summary).
 
1. Official Name:
2. Resource / Organization external URL:
3. Brief Description of the Organization:
4. Logo / Branding / Icon
- Logo / Branding - square version of org logo to be displayed in med/large contexts
-- minimum dimensions: 256px by 256px
- Icon - square version of org icon (usually available as a website favicon)
-- NOTE: CIViC client will display this icon at sizes as small as 14px by 14px, therefore icon should be somewhat recognizable at this size. Most orgs with a web presence will have a ‘favicon’ version of their logo as an image file suitable for these dimensions.
-- minimum dimensions: 48px by 48px
-- maximum dimensions: 128px by 128px
5. List of CIViC usernames to be added to the Organization:
6. Parent Organization (if applicable, see more below):

To have a Parent Organization, you are indicating a relationship between an existing organization and the organization you are submitting. Please only employ this option if you have at least 5 members of each organization and distinct groups are needed for tracking purposes (statistics, permissions, etc). If your desired Parent Organization does not exist, a request following items 1-5 will be required. All members of a suborganization are, by default, part of both the parent and the suborganization. A distinct subset of users should be indicated. For example, [Pediatric Cancer Taskforce at ClinGen](https://civicdb.org/organizations/9/summary). Members of the Pediatric Cancer Taskforce are all members of ClinGen but not all ClinGen members are on this taskforce.

**Comment by kkrysiak** [comment]
Once approved (thumbs up) or revisions suggested by at least one other user, this is ready to go.

**Comment by susannasiebert** [comment]
Where in the docs should this go?

**Comment by kkrysiak** [comment]
I would say here: https://civic.readthedocs.io/en/latest/using/organizations.html

Although I think a simple link on https://civic.readthedocs.io/en/latest/using/community.html?highlight=organization#user-organization-lists should be added.

Existing:
"The Community section is divided into two similar pages, one for users and the other for organizations - groups of users. Both pages provide leaderboards, and a filterable list of users or organizations." 

Update:
"The Community section is divided into two similar pages, one for users and the other for organizations - groups of users. Both pages provide leaderboards, and a filterable list of users or organizations. Learn more about Organizations here[link]."
