### ISSUE TITLE
User can submit empty comments

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#134]
On any talk page I can hit the `Submit Comment` button with nothing written and produce an empty comment.  Or a series of them if I wish.  Wasn't there a minimum amount of comment text required at one point?

![screen shot 2015-06-13 at 2 10 42 am](https://cloud.githubusercontent.com/assets/856728/8143434/6ec9fe46-1171-11e5-814f-3d8de74a6bc5.png)

**Comment by jmcmichael** [comment]
Implemented a new comment entry form that requires at least 2 characters to be submitted - figured the shortest message I could think of would be a smiley face. The field also shows the current user icon to the left, like github's.
