### ISSUE TITLE
Add uniprot IDs to MyGene.info box

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#1342]
Probably in the pop up, and not necessarily in the main box.

**Comment by malachig** [comment]
Text from Peter McGarvey:

> However, nothing will get implemented on our side until CIViC has links back to UniProt entries for each protein encoding gene and we have an example mapping file.  So we will need you to work on these sometime. You mentioned before about using mygeneinfo to link back to UniProt and that is fine, their mapping to us are good and I would suggest you only take the SwissProt accessions. If you could add a link to us in the blue mygeneinfo box on your gene pages that would be perfect, though you could put it elsewhere on the page if you want.

>We also need you to provide us with a tab delimited mapping file with the uniprot accession and the identifier we use to link to you. In the examples you mentioned this would be either the gene symbol "BRAF" or "5". Personally I think BRAF is best. So it might look like.

P15056    BRAF
Q9UM73    ALK
.....

>If there is a url to your APIs that can produce a tab delimited list like this we can use that also. We have too many xrefs to process to maintain parsers to different formats various resources use so we ask for an ftp or http(s) link to get or create the file.

**Comment by malachig** [comment]
Also from Peter, 

> Note: there is an option for a third string of information where the "-" is. If CIViC wanted to use this it might add something like "45 variants" or similar info each gene. Requires a 3rd column in the tab delimited table.

So perhaps we could do something similar to what we do for NDEX.  Where a process runs on a schedule to produce this tab delimited file that will be hosted from the CIViC server and used for uniprot to do their updates.  The file would be a TSV with three columns: uniprot id, gene name, basic stats about civic info on the gene.

**Comment by malachig** [comment]
Peter McGarvey followed up with me on this today.  I believe this is done now from our end?  

<img width="1333" alt="Screen Shot 2020-09-29 at 2 49 03 PM" src="https://user-images.githubusercontent.com/856728/94608484-160e8400-0263-11eb-96b1-3b7ac8000aeb.png">

**Comment by malachig** [comment]
One of the requirements mentioned above is:
```
We also need you to provide us with a tab delimited mapping file with the uniprot accession and the identifier we use to link to you. In the examples you mentioned this would be either the gene symbol "BRAF" or "5". Personally I think BRAF is best. So it might look like.

P15056 BRAF
Q9UM73 ALK

If there is a url to your APIs that can produce a tab delimited list like this we can use that also. We have too many xrefs to process to maintain parsers to different formats various resources use so we ask for an ftp or http(s) link to get or create the file.
```

Was that handled or does the capability to generate this readily via API already exist?

**Comment by malachig** [comment]
I realize this is contradicting the original comment on this issue, but can we also put the UniPROT ID in the main blue gene info box?  Right beside Entrez ID?

**Comment by susannasiebert** [comment]
I made a new issue for creating the mapping file: https://github.com/griffithlab/civic-client/issues/1533
