### ISSUE TITLE
Receive 500: Internal server error when submitting to staging server

### ISSUE THREAD

**Issue by jsaliba10** [genome/civic-client#1349]
In order to confirm a potential bug related to source suggestions I attempted to submit test information to the staging server, but whether it is a source suggesting or a new evidence item, I get a 500 server error.  I am logged in to civic through my github when doing this.

<img width="1792" alt="Screen Shot 2020-04-09 at 11 48 58 AM" src="https://user-images.githubusercontent.com/59739804/78920003-62b59700-7a58-11ea-9aa1-ea5f31b1d01f.png">
<img width="1792" alt="Screen Shot 2020-04-09 at 11 48 28 AM" src="https://user-images.githubusercontent.com/59739804/78920004-634e2d80-7a58-11ea-8fb0-f824c591b91a.png">

**Comment by susannasiebert** [comment]
This should be resolved. Can you give it a try again?

**Comment by jsaliba10** [comment]
I get the same error on the staging server.  Even tried a few different browsers.

**Comment by susannasiebert** [comment]
I merged and deployed griffithlab/civic-server#597, which should fix this error. @jsaliba10 can you give it another try please?
