### ISSUE TITLE
Browse grid not displaying all results

### ISSUE THREAD

**Issue by cgrisdale** [genome/civic-client#1350]
When I enter text in any of the fields at the top of the grid (eg. gene/disease/drug) when using Browse (evidence, variants, etc), only 1 page of results are shown. Initially there is the option to change pages below the grid (page 1-272), but once text is entered to browse a subset, the ability to change pages is lost. 

![New Picture](https://user-images.githubusercontent.com/3093548/78924438-b4592400-7a4e-11ea-96f1-0ead5e521939.jpg)

**Comment by jmcmichael** [comment]
This looks like a server bug. The response from the server's data grid endpoint used to populate these tables includes a `result` attribute - an array of entity objects, and a `total` attribute which is a count of the total records in the set. It uses the `total` attribute to calculate the pagination of the grid.

It looks like when filtering is applied, the server always returns a `total` of `0`, causing the client's display of the paging interface to fail:

*Before filtering:*
<img width="253" alt="Screenshot 2020-04-28 16 40 19" src="https://user-images.githubusercontent.com/132909/80540546-2dbda580-896f-11ea-9e63-ae1fe7157c1a.png">

*After filtering:*
<img width="205" alt="Screenshot 2020-04-28 16 40 09" src="https://user-images.githubusercontent.com/132909/80540560-32825980-896f-11ea-8297-608d01084014.png">
