### ISSUE TITLE
Unable to update Assertion

### ISSUE THREAD

**Issue by arpaddanos** [genome/civic-client#1361]
I am currently unable to update (Submit a revision for) the Assertion Description text for some reason on an assertion (AID4). I made updates to the revision description, left a comment to describe the update, but the Submit Revision button remains grayed out. This happened on two web browsers.

**Comment by arpaddanos** [comment]
I have labeled this high priority since the resubmission of fixes to ClinVar Assertion set requires revision to existing Assertions, and in general this is a very basic CIViC functionality that may not be working.

**Comment by obigriffith** [comment]
I'm seeing the same thing and agree this is a high priority to fix

**Comment by jmcmichael** [comment]
Taking a look at this now.

**Comment by susannasiebert** [comment]
This has been fixed on production. @arpaddanos please confirm that you are able to update this assertion.

Side note: Josh saw some weird behavior when testing this bugfix locally where the nccn guideline showed as changed in the suggested change diff even though he didn't change it. Please let us know if you notice that on production as well.
