### ISSUE TITLE
remove 'Status' from source summary page

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-client#1367]
Currently the status values (e.g.: “submitted”) reflect what is happening in the source suggestion queue. The words “status” and “submitted” feel unintuitive to the user who may not even know a source suggestion queue exists.  A source for which nothing was every submitted to the queue but has evidence shows status “curation completed”.  Again it seems unintuitive that what this really means is that there are no pending items in the source suggestions queue.  

After discussion, it was decided to remove this attribute from source pages, and show all source suggestions on the source summary datatable.

**Comment by malachig** [comment]
![Source status to remove](https://user-images.githubusercontent.com/856728/80148463-b48f0e80-857a-11ea-9dd8-05480aee6608.png)

Screenshot for clarity
