### ISSUE TITLE
Notifications are not appearing on "My Account" page.

### ISSUE THREAD

**Issue by jsaliba10** [genome/civic-client#1387]
In the last 24 hours, some of the EIDs I am subscribed to receive notifications for have had activity (accepted or comments), but no notification has appeared on my profile's "My Account" page. EIDs with recent activity: 7933, 7992, 7798, 7801, 8115

**Comment by jsaliba10** [comment]
Looked into it further and both Arpad's and my notifications paused as of 8-9 day ago. Not sure if has happened to anyone else.

**Comment by susannasiebert** [comment]
I see some errors on sidekiq but it's not clear to me what would be causing them:
```
ActiveJob::DeserializationError: Error while trying to deserialize arguments: FATAL: database "civic_copy" does not exist
```
