### ISSUE TITLE
Single base deletion variant not being assigned to ClinGen Allele Registry (shifting problem)?

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#1395]
This variant does not seem to get linked to ClinGen Allele Registry:

https://civicdb.org/events/genes/3465/summary/variants/642/summary#variant

I wonder if the problem with that variant is related to left vs right shifting. 

The variant is a deletion of an A within a long string of A's.  Our variant coordinates indicate deletion of the far left one.  ClinGen Allele Registry uses the far right one.

Though if I put either of these in ClinGen Allele Registry search: NC_000012.11:g.69234988del or NC_000012.11:g.69234998del they both resolve to the same variant CA238461468.

**Comment by susannasiebert** [comment]
I manually ran the job that sets allele registry IDs and it associated the ID correctly. So this is something related to the job scheduling. My hunch is that https://github.com/griffithlab/civic-server/pull/605 is causing issues.

I'm also pretty sure that there is no code in place to immediately fetch the allele registry id when a suggested change to a variant's coordinates is accepted. the job that sets the ID runs nightly so you would expect to see it updated at that point.
