### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by acoffman** [genome/civic-client#14]
We need to add links and explanations of the CC license we've selected on the downloads page and in the page footer.

**Comment by malachig** [comment]
@acoffman added the MIT license to the server repo.  I added the same to the client repo.  But we still need the Creative Commons License (https://creativecommons.org/licenses/by/4.0/) for the content to be featured in the footer.  We should also make note of this on the downloads page when that arrives.

**Comment by jmcmichael** [comment]
Added CC Attribute 4.0 license to footer w/ appropriate links.
