### ISSUE TITLE
Help page clarity - add corresponding colors to the help documentation

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#141]
To help connect parts of an evidence statement with items on the help page, add colors and images.
1) Add pictures of stars next to the star ratings on the help page.
2) Color code "Evidence Type" and "Evidence level" text to correspond to visualization. (ie, B - Clinical should be blue as observed in the evidence table.

**Comment by rbilski** [comment]
I changed the Evidence level table in the HelpPage.html to have the corresponding colors in the background of the cells to match the colors of the levels in the evidence table.

**Comment by nspies13** [comment]
Pushed this change

**Comment by jmcmichael** [comment]
I've updated the Help section with tabs for the various sections, and cleaned up the HTML/styles a bit.
