### ISSUE TITLE
Users sort by activity not working on Community page

### ISSUE THREAD

**Issue by cgrisdale** [genome/civic-client#1412]
On the Community page the "Sort by" "Most active" is not working properly. Also, there is no option to switch between pages at the bottom, it says "10 Total" and "Page 1 or 1".

Changing the "Limit to" between week, month, etc does not change the order of users.

![CIViC_UserActivitySort_bug](https://user-images.githubusercontent.com/3093548/85604317-0b11db00-b606-11ea-93e6-b91d23616f75.png)

**Comment by jmcmichael** [comment]
This appears to be a server issue, the 'total' reported on the /users endpoint looks to be incorrect:

`GET users/?count=24&limit%5Bmost_active%5D=this_month&page=1&sorting%5Bmost_active%5D=desc`

`{
"result": [24 items],
"total": 29
}`

**Comment by acoffman** [comment]
Yeah, it does appear to be server related, will take a look; thanks for the report!

**Comment by susannasiebert** [comment]
https://github.com/griffithlab/civic-server/pull/620 fixed the totals but didn't fix the sorting issue. Reopening
