### ISSUE TITLE
HPO phenotypes hyperlink directs to an error page. 

### ISSUE THREAD

**Issue by jsaliba10** [genome/civic-client#1414]
On the EID submission and edit form the HPO phenotypes hyperlink in to the associated phenotypes section directs the user to an error page on the HPO website with the following URL: https://hpo.jax.org/app/browse/term?id=HP:0000118

<img width="1744" alt="Screen Shot 2020-06-26 at 10 33 01 AM" src="https://user-images.githubusercontent.com/59739804/85874551-6bd11d00-b798-11ea-92f3-528750d25d2b.png">
<img width="1786" alt="Screen Shot 2020-06-26 at 10 33 29 AM" src="https://user-images.githubusercontent.com/59739804/85874593-7be8fc80-b798-11ea-931a-9210213ef26e.png">

**Comment by susannasiebert** [comment]
Looks like their URL format changed to: https://hpo.jax.org/app/browse/term/HP:0000118
