### ISSUE TITLE
Last updated icon does not disappear when clicking elsewhere on the page

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#142]
Clicking on the icon to see last updated requires you to click the icon again for it to disappear. It would be nice if you clicked somewhere else on the page if it would disappear.

![screen shot 2015-06-29 at 3 54 24 pm](https://cloud.githubusercontent.com/assets/8527125/8418223/508cb014-1e77-11e5-8b67-8e03757f62cc.png)

**Comment by jmcmichael** [comment]
I'm going to remove these buttons/popovers and put the entity updates info directly in the summary somewhere so users don't need to click to get a feel for community activity.

**Comment by kkrysiak** [comment]
That sounds great.

**Comment by jmcmichael** [comment]
Moved the user update info to a row directly above entity summaries, and removed the user updates button/popover.

![screen shot 2015-06-30 at 14 42 38 pm](https://cloud.githubusercontent.com/assets/132909/8440208/535ec628-1f36-11e5-9202-27d24a17520d.png)

**Comment by kkrysiak** [comment]
Looks great!
