### ISSUE TITLE
evidence grids should show if entities have outstanding flags

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-client#1432]
Since entity flags are supposed to call attention to important issues, we should indicate on evidence grids if any evidence has an outstanding flag. 

This could be done adding an icon, or changing the color of the existing notification icon.

**Comment by jmcmichael** [comment]
Working on styles for this, screenshot for feedback:

<img width="1127" alt="Screen Shot 2020-08-13 at 13 02 23" src="https://user-images.githubusercontent.com/132909/90170274-6a1de180-dd65-11ea-988f-834e43b19afe.png">

**Comment by acoffman** [comment]
This is deployed.
