### ISSUE TITLE
unable to reject own "new" revision

### ISSUE THREAD

**Issue by lsheta** [genome/civic-client#1434]
I tried to reject a revision that had not yet been applied and that I had suggested. When I selected the "Reject Revision" button, the civic bar loaded across the top but the revision was still in place. Refreshing the page showed that the revision was still in place.

Edit: Error message "403 - You do not have sufficient permissions to perform that action" appeared when I attempted to reject my own revision.

**Comment by acoffman** [comment]
This is actually the same underlying issue as #griffithlab/civic-server#634 and will be resolved once that's merged. Thanks for the report!
