### ISSUE TITLE
Add gene name to all variant gene groups, even the gene you are currently on.

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#144]
Variants within a variant group from another gene currently show that gene in parentheses. It was not intuitive to a new user that variants without these parentheses belonged to the gene currently being observed.

Perhaps the gene label in the variant group for the current gene being observed can be denoted by a different font color or type to emphasize this.

**Comment by malachig** [comment]
I had this same experience.  But once I realized, it then made sense to me that the gene in question is the current one unless indicated otherwise.  Not sure which way I prefer...  Anyone else?

**Comment by jmcmichael** [comment]
I agree that it could be slightly confusing, and changed the menu so that if a variant group contains variants from more than one gene, it shows the gene names for all the variants. If all the variants are from the same gene then it just shows the variant names.

**Comment by kkrysiak** [comment]
Could we still add a color or something to the gene name to give it some emphasis as the 'current' page? I think that would achieve the effect of adding user clarity but also still indicate, hey this is the page you are on.

**Comment by jmcmichael** [comment]
The UI provides the user w/ a couple of indications as to the current gene - the tab itself is highlighted, so they know that the gene shown in the highlighted tab is the current one. Also the gene name appears at the very top of the variant menu. In my opinion this is sufficient - I really don't want to make the variant menu any more busy than it is.
