### ISSUE TITLE
evidence cards should show flag status

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-client#1442]
Currently the evidence cards in the assertion detail view do not indicate their flagged status.

**Comment by jmcmichael** [comment]
Working on styles for this feature, screenshot for feedback:

<img width="1128" alt="Screen Shot 2020-08-13 at 13 11 58" src="https://user-images.githubusercontent.com/132909/90171110-a140c280-dd66-11ea-80e8-c5f376d4ffab.png">

**Comment by kkrysiak** [comment]
On staging, I'm not signed in but the flag button is illuminated, but pushing it doesn't do anything.
<img width="638" alt="Screen Shot 2020-08-13 at 1 47 43 PM" src="https://user-images.githubusercontent.com/8527125/90174425-94729d80-dd6b-11ea-9c09-5dc4b836d998.png">

**Comment by jmcmichael** [comment]
Yeah, that flag button shouldn't be clickable if one isn't logged in, I'll create a separate issue to fix that.
