### ISSUE TITLE
Pending evidence can be viewed by everyone.

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#146]
Even when you aren't signed in, pending evidence statements can be viewed prior to being accepted by an admin.

**Comment by jmcmichael** [comment]
Filtering pending evidence statements should probably be done on the server. The client assumes that anything it can access should be available to users (depending on a user's access level). Adding a filter on the client side to ignore pending evidence items would add unnecessary complexity to the client.

I've created a new issue on civic-server: genome/civic-server#68.

**Comment by kkrysiak** [comment]
Good to know and thank you for the explanation.
