### ISSUE TITLE
Variant groups not linked to anything plus no edit button?

### ISSUE THREAD

**Issue by jsaliba10** [genome/civic-client#1463]
When clicking on a Variant group name, an error pops up and you get redirected to the homepage. Also, I do not see a button to edit variant groups. I checked out both of these on [NRG1](https://civicdb.org/events/genes/2593/summary/variants/2286/summary#variant) and [NTRK1](https://civicdb.org/events/genes/3983/summary/variants/1278/summary
<img width="1146" alt="Screen Shot 2020-08-12 at 7 57 54 PM" src="https://user-images.githubusercontent.com/59739804/90085102-c12ba400-dcdc-11ea-9ac7-d10f9ddb3b8f.png">
<img width="1146" alt="Screen Shot 2020-08-12 at 8 43 36 PM" src="https://user-images.githubusercontent.com/59739804/90085106-c2f56780-dcdc-11ea-8209-087ced962e9c.png">

).

**Comment by jsaliba10** [comment]
The same error pops on Staging.

**Comment by jmcmichael** [comment]
Looks like the server is throwing a 500 Error. From my dev install:

```
NoMethodError at /api/variant_groups/12
=======================================

> undefined method `organization' for #<Audited::Audit:0x00007ff3b2663a70>

app/presenters/lifecycle_presenter.rb, line 16
----------------------------------------------
```
``` ruby
   11           user = if event.respond_to?(:originating_user)
   12                    event.originating_user
   13                  else
   14                    event.user
   15                  end
>  16           organization = if event.organization.nil?
   17                            {}
   18                          else
   19                            OrganizationIndexPresenter.new(event.organization)
   20                          end
   21           h[event_name] = {
```

App backtrace
-------------

 - app/presenters/lifecycle_presenter.rb:16:in `block in as_json'
 - app/presenters/lifecycle_presenter.rb:9:in `as_json'
 - app/controllers/variant_groups_controller.rb:55:in `show'
 - app/middleware/cross_origin_request.rb:7:in `call'
```

**Comment by kkrysiak** [comment]
Not sure it is helpful at this point but same for "Imatinib Resistance" under BCR. I first tried NRG1 then BCR.

<img width="659" alt="Screen Shot 2020-08-12 at 9 15 32 PM" src="https://user-images.githubusercontent.com/8527125/90087008-5af55000-dce1-11ea-927e-6d9ba12cdc11.png">
<img width="550" alt="Screen Shot 2020-08-12 at 9 17 36 PM" src="https://user-images.githubusercontent.com/8527125/90087014-5e88d700-dce1-11ea-948e-8cadb40fb734.png">

**Comment by acoffman** [comment]
This is related to the multiple organization support addition. In summary:

Variant groups don't don't have the normal lifecycle that say an evidence item or suggested change do, it was never made into a first class entity in CIViC. Its much more like a disease or a drug or source. No one proposes one and then has an editor approve it. For display purposes we show a "creation event" so its clear who made the group, but it doesn't actually have real events like evidence, assertions, etc.

The creation information is pulled from the audit log, which is the lower level history of what's happened than the event log which is what powers the various feeds on the website. This audit log is unaware of the idea of what org a user was acting on behalf of when they made the change. Now, when we try to display that history, the JSON presenter attempts to get the organization and include it, but it doesn't exist. That's what's causing the underlying error.
