### ISSUE TITLE
Provide "Add Evidence" links at the gene, and variant level, which pre-populate the relevant form fields

### ISSUE THREAD

**Issue by mkmatlock** [genome/civic-client#147]

**Comment by jmcmichael** [comment]
We've discussed this type of behavior before, but I am reluctant to add multiple buttons that lead to the same page - our UI is already fairly busy, and we've still many more features to add.

What I have on my list of things to implement is a similar convenience feature - if a user is on a Gene or Variant page and they click the Add Evidence button in the header, then the form will be populated with the gene and variant names of the record they originated from.

**Comment by malachig** [comment]
Yeah this seems like a good compromise to me.

**Comment by jmcmichael** [comment]
Done!
