### ISSUE TITLE
Color/icon codes for clinical significance and evidence direction should appear in evidence listing

### ISSUE THREAD

**Issue by mkmatlock** [genome/civic-client#148]
It would be nice to have a quick summary of what the evidence actually says clinically within the evidence listing itself. Otherwise, users have to click through individual evidence items to get a feel for the clinical significance.

**Comment by malachig** [comment]
Yeah. I feel like this is a duplicate or from an issue that was closed but I can't find it right now.

This is something we have talked about a few times in our meetings.  Currently we have only evidence level, drug, disease, and rating.  This really is not enough information to understand the importance of individual evidence items.  

It would be great if the data grid also allowed you to understand: evidence type, evidence direction, and clinical significance.  For display purposes the this needs to be done in a compact way.  @jmcmichael had some ideas on how this might be done eventually.  

Also its a bit non intuitive right now that in the evidence details view, `Evidence Level` is actually showing a combination of Evidence Level and Evidence Type.

**Comment by jmcmichael** [comment]
I just fixed the combined Evidence Level issue. I'm not sure why we combined the two, I had commented out Evidence Type so it looks intentional. At any rate, I've uncommented the evidence_type row, and now the evidence_level has the proper labels for each letter.

Regarding the evidence grid, we don't really have any more room on there unless we want to ditch the summary. Then I can add a few more columns. I think this might be a good idea, as the we're only getting the first few words of the description, and many of the summaries begin almost identically, so that whole column is of limited use anyway.

What do you think about dropping the evidence description and adding in these additional columns?

**Comment by mkmatlock** [comment]
I feel like you are on the right track. Large text fields really aren't very useful in summary grids.

**Comment by malachig** [comment]
Thinking about the curation workflow here.

The variant summary is meant to be a synthesis of evidence statements.  Creating this synthesis is a major task of the curator.  Right now, to get a sense of what each evidence statement means you really have to click through every one.

The evidence text is a very critical component of each evidence item...  If we drop that, what are we actually looking at?  Everything else is almost an annotation of that text.  Not displaying it feels weird.  I agree that it sucks how truncated they are.  But at least having it there so we can mouse over and see the whole text seems very useful.

*What if you only saw it on mouse over?*  And then we used the recovered space to provide the critical elements we need to understand the evidence statement, several of which are now missing?  

I often wish I could see more than 4-5 evidence items at once, again to help determine if the variant summary is an accurate synthesis of the existing evidence.

The `Rating` field currently takes more space than it probably needs to.  The `Level` field currently uses a lot of space to display one of [A,B,C,D,E].  Similarly, its seems like there would be a way to display other critical information in a compact way.  For example, direction can only be [positive,negative].  That could be displayed at '+', '-'.

It would be very useful to be able to break down the evidence statements by their three main types: predictive, prognostic, diagnostic.  Synthesis of the clinical relevance of a variant will often be done *within* each of these broad categories.  Right now you have to click through every evidence item and mentally build these lists.

**Comment by bainscou** [comment]
I agree with @malachig 's suggestion of using a mouse over to view evidence summaries. I think that is a good compromise. I also think that @malachig makes an excellent point on how the we intend the user to synthesize the evidence statements to make a variant summary. We should definitely support this by making it as easy as possible to reference the evidence statements when writing the variant summary. We should consider adding a table filled the EID and evidence statements  to the edit variant summary page (this would also be nice if we ever got around to implementing citation capability for the variant summary were you could select your reference from the evidence table).

**Comment by jmcmichael** [comment]
OK, I'll implement a window that displays the summary when an icon is clicked or rolled-over, something like that.

**Comment by jmcmichael** [comment]
BTW, when designing these grids we need to keep in mind that they will be displayed at several different widths. The ratings column looks like it has some extra room when the window is very wide, but if you reduce it down to one of the smaller breakpoints, you'll see that it just barely fits. Unfortunately I do not believe that I can adjust the column widths based on the CSS media query breakpoints, but I'll look around to see if anyone else has solved this problem.

**Comment by obigriffith** [comment]
My vote is to still keep some of the evidence statement text, even if really truncated and make up space on other elements by being more efficient (+/- for direction, 1* instead of *****, etc).
