### ISSUE TITLE
Add ProteinPaint (and others) to the data clients

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#1488]
Given our mutual integration, it seems logical to add them there.

**Comment by kkrysiak** [comment]
While we are at it, we should probably add the ClinGen Allele Registry here. "ClinGen Allele Registry" http://reg.clinicalgenome.org/redmine/projects/registry/genboree_registry/landing

**Comment by kkrysiak** [comment]
Although now I wonder how we should handle things like the UCSC Browser integration as well as igv.js, JBrowse, and NDEx.

**Comment by malachig** [comment]
Title: ProteinPaint
Link: https://pecan.stjude.cloud/proteinpaint

**Comment by kkrysiak** [comment]
UCSC Browser, NDex are already added.

**Comment by kkrysiak** [comment]
I don't have clear website links for igv.js and JBrowse integrations in order to direct people. These will not be included at this time.

@susannasiebert please add the ProteinPaint details provided by Malachi above to the data clients page.

**Comment by susannasiebert** [comment]
Addressed by https://github.com/griffithlab/civic-docs/pull/69
