### ISSUE TITLE
Disease Ontology Quick Search

### ISSUE THREAD

**Issue by mkmatlock** [genome/civic-client#149]
Disease type field should provide a quick search feature to find the correct disease entity DOID, instead of requiring the user to navigate to an external site, look up the DOID and copy-paste it over.

**Comment by kkrysiak** [comment]
Josh has implemented a fix for this that hasn't been pushed to the live version yet. 
- the diseases field checks the existence of a DOID, and displays it if found. Additionally the user may check the 'Could not locate DOID' checkbox, and a 'Disease Name' input will appear where they may enter a free-form disease name.
