### ISSUE TITLE
Seraching evidence for disease name or disease DOID results in 500 error 

### ISSUE THREAD

**Issue by jsaliba10** [genome/civic-client#1499]
Searching evidence for disease name results in the following error:
{"data":{"status":500,"error":"Internal Server Error"},"status":500,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","cache":false,"cancellable":true,"data":{"operator":"AND","queries":[{"field":"disease_name","condition":{"parameters":["Cancer"]}}],"entity":"evidence_items","save":true,"gridView":true},"url":"/api/evidence_items/search/","headers":{"Accept":"application/json, text/plain, */*","Civic-Web-Client-Version":"0.0.6","Content-Type":"application/json;charset=utf-8"},"cached":false},"statusText":"Internal Server Error","xhrStatus":"complete"}

This occurs for all diseases and DOIDs I have entered 

<img width="1344" alt="Screen Shot 2020-09-22 at 6 29 16 PM" src="https://user-images.githubusercontent.com/59739804/93947688-fb3b8d00-fd01-11ea-9248-a5934e64c27d.png">
<img width="1344" alt="Screen Shot 2020-09-22 at 6 29 01 PM" src="https://user-images.githubusercontent.com/59739804/93947692-fd055080-fd01-11ea-9837-7e27bc405dc6.png">
<img width="1344" alt="Screen Shot 2020-09-22 at 6 29 30 PM" src="https://user-images.githubusercontent.com/59739804/93947693-fe367d80-fd01-11ea-8e42-e656866a7b4a.png">
<img width="1344" alt="Screen Shot 2020-09-22 at 6 30 54 PM" src="https://user-images.githubusercontent.com/59739804/93947695-fecf1400-fd01-11ea-85b9-32831ba37193.png">

**Comment by jsaliba10** [comment]
Most other search options are returning results, so I think it is something only related to DOIDs. (only one other is not, creating an other issue for "clinical significance" search as this would seem to be a different issue entirely.)

**Comment by acoffman** [comment]
This is fixed and deployed.
