### ISSUE TITLE
Reorder evidence summary items

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-client#15]
I've been thinking more about this. I already suggested some reorders that took effect and were an improvement. But, I am wondering if the following would be even better.
Left column: Evidence Level, Evidence Direction, Evidence Type, Clinical Significance.
Then, as you read down the items you sort of get a sentence/story. Like: "Clinical" evidence "Supports" a "Predictive" association with "Sensitivity". 

The downside is that Drug and Clinical Significance wouldn't appear together. That has a certain logic to it as well. We could at least line them up left to right. 

So, for the right column we could have: Citation, Rating, Disease, Drug.

That has the advantage of putting Citation at the top to bring attention to the source more, followed by rating which is really a rating of that publication. Drug is also commonly N/A for non-predictive evidence so I like having it at the bottom.

Thoughts?

**Comment by malachig** [comment]
I think this layout sounds great.

**Comment by jmcmichael** [comment]
Done as part of e140b44d9fd9e4c034f11cea7fbf316a1a800dcc
