### ISSUE TITLE
Search field: Clinical significance has no options and returns error  

### ISSUE THREAD

**Issue by jsaliba10** [genome/civic-client#1500]
On the search page, when selecting "clinical significance" no options or drop down appears to sort through the different clinical significances offered.  When hitting search, a 500 error comes up.

When Clinical significance is not the primary option, these fields appear. 

<img width="1344" alt="Screen Shot 2020-09-22 at 6 44 32 PM" src="https://user-images.githubusercontent.com/59739804/93948280-ab5dc580-fd03-11ea-9c01-daeda728aad3.png">

**Comment by acoffman** [comment]
This appears to be fixed on production.
