### ISSUE TITLE
double pluralization in "HGVS Description(s)s"

### ISSUE THREAD

**Issue by ahwagner** [genome/civic-client#1503]
See highlighted text.
![image](https://user-images.githubusercontent.com/811065/94330182-13284080-ff90-11ea-9cca-5e6246ab06dd.png)

**Comment by ahwagner** [comment]
Looks like this was already addressed in 4040c645bbf7c7fb70dbc2e9b32197f892dbd57b, but not deployed? @jmcmichael can you confirm this works in dev env and is awaiting deploy? If so feel free to close.

**Comment by acoffman** [comment]
This is indeed fixed and deployed.
