### ISSUE TITLE
Create background job to check DOID for diseases with a manually assigned DOID not in the cancer_slim file (e.g., Von Hippel Lindau)

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#1509]
We have several diseases that are cancer associated but it would not be appropriate to add it to the cancer_slim file for other DO users that might want to use this file.

So in these cases (Li-Fraumeni, VHL, etc) we can add the DOID manually in the admin interface, but it does not stay up to date, only links to that DOID at DO. It would be nice if a background job would periodically check these DOIDs for updates and synonyms/aliases.

**Comment by susannasiebert** [comment]
@kkrysiak or @arpaddanos can you provide me with a full list of DOIDs where this is the case. I need a way to differentiate between terms we legitimately don't want in the cancer slim file and ones that need to be added.
