### ISSUE TITLE
Need to add synonymous variant in the SO preferred terms table

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#1522]
https://civic.readthedocs.io/en/latest/model/variants/types.html#curation-guidelines-for-specific-sequence-ontology-types

We have `synonymous`, `synonymous variant` and `silent` sequence ontology terms in CIViC. We need to unify this and add instructions to the docs.

**Comment by kkrysiak** [comment]
I would add this above the N/A (last row of the table)

Sequence Ontology Term | Sequence Ontology Definition | Comments
synonymous_variant | A sequence variant where there is no resulting change to the encoded amino acid. | --

http://www.sequenceontology.org/browser/current_svn/term/SO:0001819

**Comment by susannasiebert** [comment]
What about `synonymous` and `silent`? Do these terms needs to be fixed on the database side of things (combined with `synonymous_variant`)?

**Comment by kkrysiak** [comment]
I was imagining that we'd do this as curators in the interface. There is only 1 instance of `Synonymous` and actually when I used the Variant Search `Silent` doesn't bring anything up. That seems weird unless someone fixed that since yesterday (my guess would be Lana).

**Comment by kkrysiak** [comment]
Confirmed. Lana fixed these. 

@susannasiebert is there an easy way to limit those SO IDs so they can't be picked? I'm not saying we should do so but it might be worth considering if it would be simple.

**Comment by susannasiebert** [comment]
we could remove them from the database but they would probably just be added back in next time the SO scraper runs. We would need to update the logic to skip them, which shouldn't me too difficult.

**Comment by kkrysiak** [comment]
Maybe we should add that to the next CIViC agenda as a consideration or create an issue for a v2 thing. I think we'd want to do this for more than just these 2 SO terms. Since that may also be confusing to users who go directly to SO, I don't want to take this too lightly.

**Comment by susannasiebert** [comment]
ok, for now I can just add the `synonymous_variant` term to the documentation with the details you provided above.

**Comment by susannasiebert** [comment]
During yesterday's meeting it was decided that we would not be skipping terms like `synonymous` and `silent` for import. Instead a better typeahead sorting was proposed in https://github.com/griffithlab/civic-client/issues/1536
