### ISSUE TITLE
Variant type-ahead should only pull sequence ontology terms from sequence_variant root. 

### ISSUE THREAD

**Issue by lsheta** [genome/civic-client#1530]
I think the current variant type-ahead when curating variant types pulls all terms from sequence ontology. It may reduce incorrect annotations if the type-ahead only pulled terms from the sequence_variant root. 
From Alex (in civic curation slack channel from Fri Oct 23, 2020): The general advice that I’ve seen is to pick the most specific forms relevant to the variant, such that they are not in a direct lineage and all chosen terms arise from the sequence_variant root concept.

**Comment by susannasiebert** [comment]
Instead of only importing certain parts of the SO, we decided to improve the variant type typeahead (https://github.com/griffithlab/civic-client/issues/1536). Closing this issue in favor of #1536
