### ISSUE TITLE
angular resources 404 

### ISSUE THREAD

**Issue by caaespin** [genome/civic-client#1550]
A lot of the resources on https://github.com/griffithlab/civic-client/blob/staging/gulp/cdnize.js are sulting in 404 responses (like https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.8.2/angular-sanitize.min.js)

**Comment by jmcmichael** [comment]
I need to refactor the workflow eliminate dependencies removed from NPM after the [flatmap-stream package compromise](https://thenewstack.io/attackers-up-their-game-with-latest-npm-package-compromise/). Several of the client's workflow dependencies were removed, and I've been putting off the refactor as the workflow utilizes many complex custom functions which have proven non-trivial to update to work with the latest versions of the removed packages.

The civic-server repository's [public directory](https://github.com/griffithlab/civic-server/tree/staging/public) contains the latest compiled client that works with the staging branch of the server. If you don't intend to do any hacking on the client, then this build will allow you to interact with the server.

If you intend to make modifications to the client code, we have an archived node-modules directory that you may copy into the root of a fresh clone of the client repository. This will allow you to execute the workflow commands without having to complete a npm/yarn installation from scratch:

[civic_node_modules_2019-07-17.zip (75MB)](https://wustl.box.com/v/civic-node-modules-2019)

Please reopen this if you have further problems building the client.
