### ISSUE TITLE
Download CSV is not working in Evidence grids 

### ISSUE THREAD

**Issue by lsheta** [genome/civic-client#1566]
I'm able to select `Download CSV` for other grids (assertions, sources, variants, etc) under the `Get Data` option. `Get Data` appears in the evidence grid, but selecting `Download CSV` does not pull up the download page.

**Comment by sfacista** [comment]
I can confirm that I am having the same issue. I have tested in FireFox Version 83.0 (64-bit) & Google Chrome Version 87.0.4280.88 (Official Build) (64-bit).

The button points to the following script: ctrl.exportData()
![image](https://user-images.githubusercontent.com/29548573/103579286-40d92b80-4e95-11eb-98db-65dbe8767b61.png)

**Comment by acoffman** [comment]
@jmcmichael, Looking at the dev tools, this doesn't seem to be sending a server side request, so I'm guessing its a client side issue. Would you mind taking a look?

**Comment by jmcmichael** [comment]
We've got a fix for this, merged with PR #1572 and recently staged. It should be live sometime this week - sorry for the delay!
