### ISSUE TITLE
Flagged entities tab not updating between each page

### ISSUE THREAD

**Issue by lsheta** [genome/civic-client#1571]
When clicking through the pages of flagged entities, pages 1 and 2 show the same entities, pages 3 and 4 show the same entities. Hard refreshes don't seem to help.

**Comment by lsheta** [comment]
I don't think the flag page is working at all anymore. When I select flags on the home page, it doesn't take me to the flagged page.

**Comment by lsheta** [comment]
The Open Flag button doesn't open the page of flagged entities. 

<img width="224" alt="Screen Shot 2021-02-04 at 12 56 17 PM" src="https://user-images.githubusercontent.com/40039142/106954309-74071880-66e8-11eb-9a27-aee4ad84961e.png">

**Comment by susannasiebert** [comment]
This seems to be a data problem. I'm digging into it.

**Comment by acoffman** [comment]
This is resolved, sorry about that and thanks for letting us know! 
(Both the pagination issue and the page not loading)
