### ISSUE TITLE
Unable to accept revision

### ISSUE THREAD

**Issue by cgrisdale** [genome/civic-client#1574]
I'm not able to accept revision #29107 for EID5957. Hard refresh didn't solve it.

The error shown on the page is:
403 - The attempted update conflicts with an existing record.

There is only one revision so I'm not sure what conflicts could exist.

![CIViC_cant_accept_revision](https://user-images.githubusercontent.com/3093548/103933969-0cee4800-50d9-11eb-9407-48aa893abb0b.png)

**Comment by kkrysiak** [comment]
@cgrisdale Do me favor and try a hard refresh and see if it has been accepted. It may otherwise be because the disease was changed.

**Comment by cgrisdale** [comment]
A hard refresh did not solve it.

**Comment by kkrysiak** [comment]
Solid Tumor was entered into the database 255 times due to some old error. So the disease term update (removal of extra terms) caused this issue. Using the admin interface to remove this suggested change to the disease field should have fixed it.

**Comment by kkrysiak** [comment]
Successfully resolved!
