### ISSUE TITLE
create pediatric cancer variant results page and homepage news promo w/ link

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-client#1575]
Results page will be a saved advanced search result:

https://civicdb.org/search/evidence/9dfdc53d-4022-43b1-8f3a-6b6bf81caff6

 Also add a customized example  search button (light baby-blue colored) to the top saved searches.

Need copy for the homepage news item, mention CCDI funding.

**Comment by jsaliba10** [comment]
I will write up an Announcement and place it here.

**Comment by jsaliba10** [comment]
Through support from the Childhood Cancer Data Initiative (CCDI), we have executed our initial phase of highlighting pediatric cancer variant content. This advanced search query displays childhood relevant data contained in CIViC. Stay tuned for more pediatric-focused features as we launch the first open-access searchable childhood-cancer-specific dataset.
