### ISSUE TITLE
variant not filling on Source Suggestion queue

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#1577]
![Screen Shot 2021-01-20 at 3 00 14 PM](https://user-images.githubusercontent.com/8527125/105234074-522a6500-5b30-11eb-8720-be1b71e2c7d2.png)
![Screen Shot 2021-01-20 at 3 00 03 PM](https://user-images.githubusercontent.com/8527125/105234077-52c2fb80-5b30-11eb-82aa-7ca632b85dbe.png)
I tried it on both the staging and the live site. On the live site I entered I836 as the variant for my source suggestion but it didn't appear. This may have to do with stupid auto-fill protocols on chrome so this may not be a bug for others.

**Comment by jmcmichael** [comment]
This looks like a server issue, as the client doesn't appear to be providing a value for the variant attribute, it's returning `null` for the Tarver et. al. source:
<img width="681" alt="Screen Shot 2021-01-21 at 12 31 30" src="https://user-images.githubusercontent.com/132909/105395650-97a86a00-5be4-11eb-946f-5c45c2ada45d.png">

A test on my dev installation worked OK though - the variant attribute was provided for a new source.

**Comment by acoffman** [comment]
This is resolved in the latest deploy!
