### ISSUE TITLE
advanced search generating internal server errors when looking for empty fields

### ISSUE THREAD

**Issue by lsheta** [genome/civic-client#1590]
I've noticed that several searches generate this error message when I search for empty fields: 
`{"data":{"status":500,"error":"Internal Server Error"},"status":500,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","cache":false,"cancellable":true,"data":{"operator":"AND","queries":[{"field":"representative_transcript","condition":{"name":"is_empty","parameters":[]}}],"entity":"variants","save":true,"gridView":true},"url":"/api/variants/search/","headers":{"Accept":"application/json, text/plain, */*","Civic-Web-Client-Version":"0.0.6","Content-Type":"application/json;charset=utf-8"},"cached":false},"statusText":"Internal Server Error","xhrStatus":"complete"`

A few sample searches:
[Variants with empty CHR1 Chromosome](https://civicdb.org/search/variants/b531d9e3-eece-431a-b43c-8d9ffc775849)
[Evidence with empty DOID](https://civicdb.org/search/evidence/)

The error may not only appear for empty field searches, but that's where I've run into it.

**Comment by susannasiebert** [comment]
I assume this is related to #1589 and would be resolved by the PR I have open. Basically any search right now that returns functional evidence items will result in the error you’re seeing.

**Comment by susannasiebert** [comment]
I think the new staging deploy fixes this issue. @lsheta can you give it a try and confirm?

**Comment by lsheta** [comment]
@susannasiebert I tried all the searches where I had noticed the error and they seem to work now. Thank you!
