### ISSUE TITLE
Advanced search for Functional evidence not working

### ISSUE THREAD

**Issue by cgrisdale** [genome/civic-client#1595]
An advanced search for all Functional evidence returned the following error:
`{"data":{"status":500,"error":"Internal Server Error"},"status":500,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","cache":false,"cancellable":true,"data":{"operator":"AND","queries":[{"field":"evidence_type","condition":{"name":"is_equal_to","parameters":["Functional"]}}],"entity":"evidence_items","save":true,"gridView":true},"url":"/api/evidence_items/search/","headers":{"Accept":"application/json, text/plain, */*","Civic-Web-Client-Version":"0.0.6","Content-Type":"application/json;charset=utf-8"},"cached":false},"statusText":"Internal Server Error","xhrStatus":"complete"}`

**Comment by acoffman** [comment]
It looks like this is the same issue Lana was running into (https://github.com/griffithlab/civic-client/issues/1590)

It should be fixed on staging and by the next prod deploy!
