### ISSUE TITLE
Diseases not in cancer_slim but acceptable to CIViC

### ISSUE THREAD

**Issue by lsheta** [genome/civic-client#1601]
There are a few diseases that aren't going to be in cancer_slim that are okay in CIViC, so the civic-bot doesn't need to flag them. 
Here are the ones I know of and I'll update this list as I resolve the flags. 
Melanotic Neurilemmoma (DOID: 3205)
Lipofibromatosis-like Neural Tumor (DOID: 0080894)
-this one is weird because DO nests it under connective tissue cancer, though it's not in cancer_slim and is not a cancer as far as I can tell.
Histiocytosis-Lymphadenopathy Plus Syndrome(DOID:0111278)

**Comment by susannasiebert** [comment]
I will add those to the background job to be ignored. You will probably want to wait to resolve the flag until I make that change and it gets released into production. Otherwise, those EIDs will get re-flagged next time the background job runs.

**Comment by lsheta** [comment]
Sure, no problem. I'll hold off on resolving those flags. Could you let me know when you make that change?

**Comment by susannasiebert** [comment]
Yes, will do.
