### ISSUE TITLE
Order of Evidence Type in Add evidence form, docs, and elsewhere

### ISSUE THREAD

**Issue by lsheta** [genome/civic-client#1602]
What should the order of Evidence type be in the Add Evidence Form? 
Currently: Predictive, Diagnostic, Prognostic, Predisposing, Functional, Oncogenic.

**Comment by obigriffith** [comment]
This is the order I have been using when making consistent in docs: Predictive, Diagnostic, Prognostic, Predisposing, Oncogenic or Functional

It has a kind of prominence/logic in my mind, although I'm not sure I could fully explain it.

**Comment by arpaddanos** [comment]
My preference is Predictive, Diagnostic, Prognostic, Predisposing, Oncogenic, Predisposing, Functional

Oncogenic comes before Predisposing as it reflects the clinical and then somatic focus of CIViC. Oncogenic (clinical and somatic), Predisposing (clinical and germline), Functional (preclinical and both somatic and germline) This is why Predisposing would come before Functional.

**Comment by lsheta** [comment]
I think in either case, it may be preferable to switch the positions of Prognostic and Diagnostic. Prognostic is used doubly as often as Diagnostic (663 vs 297 EIDs).

**Comment by arpaddanos** [comment]
That makes sense to me: Predictive, Prognostic, Diagnostic, Predisposing, Oncogenic, Predisposing, Functional

**Comment by obigriffith** [comment]
Lana - That makes sense. 
Arpad - You have Predisposing listed twice. But, I think what you are proposing is:
Predictive, Prognostic, Diagnostic, Oncogenic, Predisposing, Functional

I see the rationale for grouping somatic-focused evidence types together. I think a case can be made for swapping Oncogenic/Predisposing to predisposing/oncogenic. I agree they should go together and functional should go last. My thought with predisposing before oncogenic is that it is arguably more clinically relevant than oncogenic so they six types would be roughly (although subjectively) ordered in terms of clinical relevance.

**Comment by arpaddanos** [comment]
Yes that is correct - It was written while listening during the meeting. I can also see the argument that Predisposing is more clinical. But it is still a different field (germline cancer) from somatic cancer driven by somatic oncogenic events. So both options have reasoning behind them, both are workable. There is also overlap, where for instance BRCA germline predisposed cancer still requires a somatic BRCA event on the other allele.

**Comment by lsheta** [comment]
I vote for Predictive, Prognostic, Diagnostic, Predisposing, Oncogenic, Functional. Ordering by clinical relevance makes more sense to me than grouping germline and and somatic, especially because we have [evidence items that are germline but not predisposing](https://civicdb.org/search/evidence/9787ff1f-8244-41e6-8db4-db9edc47ddf2) (e.g., predictive).

**Comment by malachig** [comment]
It sounds like there are two competing orders being proposed here:

`Predictive`, `Prognostic`, `Diagnostic`, `Oncogenic`, `Predisposing`, `Functional`
vs.
`Predictive`, `Prognostic`, `Diagnostic`, `Predisposing`, `Oncogenic`, `Functional`

**Comment by lsheta** [comment]
Yeah, maybe we're at the point where we could poll. I'll make two separate comments with each option. Maybe people could thumb up their preference.

**Comment by lsheta** [comment]
`Predictive`, `Prognostic`, `Diagnostic`, `Oncogenic`, `Predisposing`, `Functional`

**Comment by lsheta** [comment]
`Predictive`, `Prognostic`, `Diagnostic`, `Predisposing`, `Oncogenic`, `Functional`

**Comment by obigriffith** [comment]
This order wins!
