### ISSUE TITLE
ensure field toolstips display properly for 'N/A' selections

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-client#1603]
Evidence Type `Prognostic`, `Predisposing`, and `Oncogenic` and Clinical Significance `N/A` all show "Clinical Significance is Not Applicable for Oncogenic Evidence Type" when different evidence types should show different tips. For instance, `Functional` evidence type and `N/A` clinical significance should show "Variant does not inform clinical action".

**Comment by lsheta** [comment]
Would it be easier for the tooltip for `N/A` for the Clinical Significance of all Evidence Types to say

>Clinical Significance is not applicable.

It's not a very informative tooltip but I don’t want to take up too much dev time if this is a complex problem
