### ISSUE TITLE
Unable to add variant group

### ISSUE THREAD

**Issue by jsaliba10** [genome/civic-client#1615]
Tried to create a new variant group, but when clicking "add variant group" nothing happens. Also, when filling out the variant field, variants are not appearing a drop down menu. 
<img width="1760" alt="Screen Shot 2021-04-26 at 12 49 56 PM" src="https://user-images.githubusercontent.com/59739804/116128308-68474480-a68e-11eb-8f6e-a56567ae3769.png">

**Comment by kkrysiak** [comment]
![Screen Shot 2021-04-26 at 12 49 43 PM](https://user-images.githubusercontent.com/8527125/116129150-6467f200-a68f-11eb-9fcf-b7db9b57dd91.png)
My error when I just navigate to the Add Variant Group page.
