### ISSUE TITLE
Improvements to help documentation content

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#162]
Going through the help documentation pages again I made a few edits but also wanted to raise two issues for discussion:
https://civic.genome.wustl.edu/#/help

1.) On the evidence statement tab, the 'Text summary' entry in the table of components of an evidence statement and the introductory paragraph at the top are somewhat conflating these things: (a) the manually created evidence statement text for a single evidence item from a single publication, and (b) the synthesis of multiple evidence statements to create a variant summary, and to a lesser extent (c) the gene level summary.  

In general I think we could do a better job of explaining the relationship between the components of a single evidence statement/item/record, the summary text for that single evidence statement, the variant summary that synthesizes N evidence statement for a single variant, and the gene summary that synthesizes across multiple variants of a gene.  I think maybe the table in this tab show be focused on the components of a single evidence statement only.  And actually labeling this table as 'evidence statement' is itself confusing.  Maybe better to describe this is an evidence item or record, where the statement (summary text) is but one component.

2.) I'm not sure about our use of the concept of journal `impact factor` in the documentation for Star Ratings.  Should we be publicly endorsing the use of impact factor in this way?  A lot of things influence what journal scientists get their papers published in.  I don't think impact factor of the journal is that well correlated with the quality of individual publications in the journal.  Expert scientists/clinicians should evaluate the evidence at face value. Maybe the impact factor of the journal is one of many factors they subjectively consider, hopefully a relatively minor factor, possibly so minor that it is not worth mentioning specifically in the official CIViC documentation.

**Comment by jmcmichael** [comment]
I changed the Evidence Statement tab to Evidence Item (as that's the term we're using elsewhere in the app). It looks like the other concerns mentioned here have been addressed as well so I'll close this.
