### ISSUE TITLE
Editing variant groups error

### ISSUE THREAD

**Issue by jsaliba10** [genome/civic-client#1620]
When clicking on the edit pencil for a `variant group` an error message pops up and I was redirected to the front page. Also, when clicking `variant talk` an error occurs and I was redirected to the front page. 
<img width="1729" alt="Screen Shot 2021-05-07 at 4 04 24 PM" src="https://user-images.githubusercontent.com/59739804/117502711-e7216480-af4d-11eb-8f75-74580cd91bff.png">
<img width="1729" alt="Screen Shot 2021-05-07 at 4 03 52 PM" src="https://user-images.githubusercontent.com/59739804/117502806-0ddf9b00-af4e-11eb-8e2d-ec9aace6815d.png">

**Comment by acoffman** [comment]
On first glance it looks like this is related to something in the variant group being soft-deleted. Will dig into it more!

**Comment by acoffman** [comment]
This is resolved in the latest deploy!
