### ISSUE TITLE
CIViC organization statistics colors are wrong

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#1621]
https://civicdb.org/statistics/organizations

Submitted and Rejected, the colors are swapped.
<img width="998" alt="Screen Shot 2021-05-09 at 3 02 49 PM" src="https://user-images.githubusercontent.com/8527125/117585354-a5bcc080-b0d7-11eb-9738-3d45c573dff3.png">

**Comment by acoffman** [comment]
This is resolved in the latest deploy!
