### ISSUE TITLE
Source suggestion queue isn't accepting non-existing variants

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#1624]
I tried adding new PTEN variants that do not already exist in CIViC. I received the warning that these do not exist

> NOTE: This appears to be a new variant for the selected gene. Please ensure it has not already been entered under a similar name before you create it.

but when I submit the Source Suggestion, the variant is gone. Occurred 3 times, also attempted a hard refresh.

**Comment by acoffman** [comment]
This is resolved in the latest deploy!
