### ISSUE TITLE
Internal server error in the civic api

### ISSUE THREAD

**Issue by gorupria** [genome/civic-client#1625]
Hi,

The civic api is returning "Internal server error" for the past couple of days. I think the error happens in the last page. Any ideas?
![Screenshot from 2021-07-02 13-18-37](https://user-images.githubusercontent.com/5008375/124260363-45c32300-db38-11eb-81aa-457b087bafc0.png)

**Comment by acoffman** [comment]
Hi @gorupria,

Thanks for reporting this! There was indeed an issue with retrieving the last page of evidence items. The issue should be resolved now, but let me know if you encounter any more problems.

Thanks!
