### ISSUE TITLE
Browse grid pages showing same EIDs more than once

### ISSUE THREAD

**Issue by cgrisdale** [genome/civic-client#1627]
When looking through pages of the Browse Evidence grid I noticed the same EIDs coming up on more than one page; see EIDs 123, 124, 4335, 4413, etc, in screenshots of Page 1 and 2.
The total number shown below the grid (244) is the same as the number I get when doing an Advanced search for this subset of EIDs, so maybe some EIDs are missing from the grid if others are being displayed multiple times?
![Screenshot from 2021-07-22 16-19-16](https://user-images.githubusercontent.com/3093548/126721405-04f9748f-6b38-440a-9d5d-41361f13ea9a.png)
![Screenshot from 2021-07-22 16-20-50](https://user-images.githubusercontent.com/3093548/126721408-87fae244-a279-48c7-ad6e-94e4e0e449c7.png)

**Comment by acoffman** [comment]
This is resolved in the latest deploy!
