### ISSUE TITLE
figure out where we can show a variant groups data grid w/ detail view

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-client#179]

**Comment by kkrysiak** [comment]
Would it be reasonable to add this as another tab on the browse page? It can contain a grid of variant group name, list of variants, list of genes, number of variants, number of evidence items, perhaps?

**Comment by jmcmichael** [comment]
Yeah, the browse view looks like the best place to locate a variant group data grid. The client will need to query a datatables/variant_groups endpoint which doesn't exist yet.
