### ISSUE TITLE
implement scrolling back on browse page

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-client#181]

**Comment by jmcmichael** [comment]
The ui-grid feature for doing infinite-scroll with server-side updates is still in the alpha stage, so I'm going to put this off until it has better support. The paging interface works OK for now.

**Comment by malachig** [comment]
Okay.  If the pagination is staying then I wonder if this is an easy fix.  On the "Browse by Gene" view, if you go to page '4' or 'Last' you see an empty page.  It looks like we only have enough genes for 3 pages.  Are the number of pages not determined dynamically based on database contents?

I noticed the same thing for the "Browse by Variant" view for quite a while.  But now we have a result that spills onto page 9 that used to be empty.
