### ISSUE TITLE
add affiliation and institution attributes to profile and profile edit pages

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-client#183]

**Comment by obigriffith** [comment]
This has been requested by ClinGen as a pre-requisite to engaging with their curators to allow clingen specific filtering of records.

**Comment by acoffman** [comment]
@obigriffith Would we additionally need filters for evidence or variants submitted by users of a specific affiliation?

Do we need access control for the groups? IE: Should there be an "owner" of the institution group on CIViC that grants that affiliation to other users? Or should groups be free to join?

**Comment by jmcmichael** [comment]
Closing, added Organization fields to relevant profile, community components.
