### ISSUE TITLE
Set an intuitive order for tables of evidence statements

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#19]
It is not obvious how these are sorted now.  For example, if we select BRAF V600E, there are currently 31 evidence statements.  Not sure what order these are in now.  But it would be awesome if they were ordered by 'Level' (A, B, C, D) and then within statements of the same level by 'Rating' (highest rating first).  Thoughts?

**Comment by nspies13** [comment]
Didn't see this. I added another issue to have them sort by trust rating. That was the first thing Zach and I clicked when loading the table. I think it is most intuitive to sort that way. But any sorting is better than none at the moment.
