### ISSUE TITLE
Event stream should list Gene (as well as variant) and link to the event

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-client#191]
As we start seeing more proposed revisions in the event stream it is hard to find the actual revision because we don't know what gene is involved. Ideally the event stream item would link to the event (or at least relevant gene/variant page).

![screenshot 2015-08-24 15 57 50](https://cloud.githubusercontent.com/assets/1638042/9452267/ea521be4-4a78-11e5-9215-922ddf77741d.png)

**Comment by kkrysiak** [comment]
This has already been done.
