### ISSUE TITLE
Apply button should be dropped

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-client#193]
I believe we decided to drop the apply button site-wide?  Even admins should review their additions/edits before committing them live to the site through the public interface. Direct changes can still be made through the separate admin interface if needed.

**Comment by jmcmichael** [comment]
The latest master contains a commit that removes the Apply buttons. I just now pushed another that removes text referring to Apply buttons from edit entity form instructions. (We're still getting another build out, the delays are my fault - I wanted to finish off the Add Variant Group, Profile Edit features and fix a data grid issue)
