### ISSUE TITLE
Revision view for gene sources shows internal IDs

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-client#194]
When adding a new source for a gene summary, the revision diff shows our internal IDs rather than the more human readable PMIDs.

![screenshot 2015-08-25 11 34 20](https://cloud.githubusercontent.com/assets/1638042/9472880/6c211c02-4b1d-11e5-8c9e-23cf47fd731b.png)

**Comment by jmcmichael** [comment]
Yeah, this is definitely something we're going to fix (as well as the diffs for Drugs, which also show IDs).

**Comment by jmcmichael** [comment]
OK, this has been fixed on civic-server.
