### ISSUE TITLE
Order variants by name within variant list or variant-group list

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#198]
The order of variants on the left side of the variant view seems quite random.  Currently based on the underlying integer id?  This results in a confusing order for some genes.  For example:

<img width="1151" alt="screen shot 2015-09-02 at 11 40 20 am" src="https://cloud.githubusercontent.com/assets/856728/9637673/c5d9ff7a-5167-11e5-9100-4af1e3386357.png">

Can we order them by name instead?

**Comment by kkrysiak** [comment]
If we had coordinates for all of them, maybe we could consider using those? Or would that be to non-intuitive? It would be helpful for the SNVs but maybe not for other mutation types.

**Comment by jmcmichael** [comment]
Yeah, there's an open issue (#67) requesting the variant menu to be ordered by genome coordinate. Until we have coordinates for all the variants then I don't think that will work out very well.

The current master sorts variants and variant groups by name.

**Comment by malachig** [comment]
Yeah the variant coordinates are still really a work in progress with debate about how to even do it still ongoing...  Until we get that resolved I think the name is an okay compromise.

**Comment by jmcmichael** [comment]
Done.
