### ISSUE TITLE
Profile page shows events for logged in user, even when on another's profile page

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-client#209]
![screen shot 2015-09-02 at 6 19 15 pm](https://cloud.githubusercontent.com/assets/1638042/9647098/3847dc44-519f-11e5-98ae-943fdc15983e.png)

**Comment by jmcmichael** [comment]
Don't we want to show events for all users on their profile page? This information is public elsewhere on the site but just scattered around attached to various entities - the profile page just shows them all in one place.

**Comment by obigriffith** [comment]
I'm not sure I understand. If Malachi is logged in he sees his events on his profile page. If I am logged in I see my events on my profile page. That makes sense. But, when I am logged in, I don't expect to see my (obigriffith) events when I am visiting Malachi's profile page. I expect to see his events. The snapshot above shows me visiting Martin's page, wondering what he has been up to, but learning only what I have been doing.

**Comment by obigriffith** [comment]
As a corollary to this. When I am logged out, I don't see any events on any profile pages. Presumably because it currently generates events for the logged in user.
![screen shot 2015-09-03 at 10 38 39 am](https://cloud.githubusercontent.com/assets/1638042/9662989/e731a5d6-5227-11e5-8496-c33852394b7f.png)

**Comment by jmcmichael** [comment]
Oh, duh. Yeah sorry - this is not intended behavior, I misunderstood your original issue.

**Comment by jmcmichael** [comment]
This is fixed. As this was a server issue, please pull the latest civic-server master to get the fix for your installation.
