### ISSUE TITLE
Scrolling in table of evidence statements is extremely sensitive

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#21]
To illustrate this, go to the browse page, sort by number of statements, and select one with lost of evidence (e.g. BRAF V600E).  Scrolling through the evidence statements is very fast, making it difficult to land in the middle of the table.

**Comment by jmcmichael** [comment]
Yeah I'm going to implement paging on this datagrid, which should fix this issue.

**Comment by jmcmichael** [comment]
Implemented pagination on the evidence grid (40b0145117d83b236081934bc09fb67f45b987df), closing.
