### ISSUE TITLE
Genes count on landing page statistics is counting all Entrez genes

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#211]
It looks like the gene count is summarizing everything cached?  We probably want genes with at least one evidence item here.

![screen shot 2015-09-03 at 10 12 46 pm](https://cloud.githubusercontent.com/assets/856728/9675902/58bc161c-5289-11e5-8f74-5474c87e2a47.png)

**Comment by malachig** [comment]
Yeah I wondered if it should have been a civic-server issue instead.  The proposed solution makes sense. :)

**Comment by malachig** [comment]
I believe this is now fixed and this issue can be closed?  Unless there is some aspect still pending @acoffman or @jmcmichael ?

**Comment by acoffman** [comment]
This is fixed and can be closed now! Good catch.
