### ISSUE TITLE
Need to add a variant table to help documentation

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#213]
Create a new Help Table for Variants (below the evidence table on help page) that the following can be added to:
- Create help documentation on how to choose a **representative variant**
  * Look for most recurrent mutation in COSMIC
  * choose the first alpha numeric mutation 
- Create help documentation about variant groups
- Create help documentation about generating variant summaries

**Comment by jmcmichael** [comment]
This seems like it would include quite a bit of content - maybe it should be its own tab instead of a section  in the Evidence Item tab?

**Comment by jmcmichael** [comment]
Create a main menu w/ items for each of the CIViC entities - current Help will comprise the Evidence Items page.

**Comment by jmcmichael** [comment]
I've added new pages for genes, variants, and variant groups to the Help section, along w/ a sidebar menu. The new Variant page should be perfect for hosting the content detailed above (I can add tabs to this page, like the Evidence page, if necessary)
