### ISSUE TITLE
Display transcription strand for each gene

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#216]
When reviewing and interpreting representative variants (amino acid translation of codons in particular) it is critical to account for the transcription strand of the gene (+ve vs. -ve).  For convenience we should display this key gene information for every gene.  Perhaps beside `Entrez Symbol` and `Entrez ID` we could still fit `Strand: +ve` or `Strand: -ve`?

**Comment by jmcmichael** [comment]
Sure, this will be easy to add to the UI once civic-server returns the attribute on gene objects.

**Comment by jmcmichael** [comment]
This is available from MyGene.info - the 'strand' attribute is either -1 or 1, corresponding to -ve and +ve

**Comment by jmcmichael** [comment]
Use the genomic_pos_hg19 attribute from MyGeneInfo, add a 'Coordinates' line to the MyGeneInfo block:
"genomic_pos_hg19": {
"start": 56360553,
"chr": "12",
"end": 56366568,
"strand": 1
},

**Comment by malachig** [comment]
Looks like the latest update including this addition just went live on the public server.  I see headings for `Chromosome:	 Start: End: Strand:`.  But no values.  @acoffman not sure if this is likely to involve server or client but adding here since this was the open issue.

**Comment by malachig** [comment]
FYI, @jmcmichael and @acoffman this does not seem to be totally consistent.  Some genes display it, and some do not.

For example, working:
https://civic.genome.wustl.edu/#/events/genes/5/summary#gene

Not working:
https://civic.genome.wustl.edu/#/events/genes/1/summary#gene

**Comment by acoffman** [comment]
We cache the responses from MyGene.info for a little while so that we don't hit their API on every page load. Looks like we still had some of the entries cached from before the change that included this info. I went ahead and cleared the cache and it looks like we're getting the strand info across the board now!

**Comment by malachig** [comment]
Awesome.  Looks good now.  Closing.
