### ISSUE TITLE
number of variants count disagrees between front page and browse page

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-client#228]
At the moment the front page reports 229 variants but browsing only shows 203. Is this expected?  Should they agree?

**Comment by jmcmichael** [comment]
The homepage is reporting 204 variants now, as is the browse page. Are they still showing up different for you? Not sure what mechanism would cause different counts.

**Comment by malachig** [comment]
I also 204 in both places...

**Comment by obigriffith** [comment]
Yeah. They seem to agree now. We can close this issue.
