### ISSUE TITLE
New users without user name

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-client#232]
A new user just joined and created a new evidence statement. They don't have a user name. This results in some unfortunate display glitches such as "null" on their profile page and a truncated user logo everywhere else. 

![screenshot 2015-10-04 18 59 06](https://cloud.githubusercontent.com/assets/1638042/10271074/670c0660-6aca-11e5-8aa0-a214b5d62d4c.png)

![screenshot 2015-10-04 19 04 41](https://cloud.githubusercontent.com/assets/1638042/10271087/cbf533f8-6aca-11e5-98ec-72cefa64c7f1.png)

**Comment by jmcmichael** [comment]
I'll add a fallback to display .name instead of .username if the username is null.

**Comment by jmcmichael** [comment]
Switched to using the new display_name property, which is guaranteed to be populated, for displaying names on user components.
