### ISSUE TITLE
Create a variant synonym concept and allow curators to add these in the variant edit form

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#233]
@acoffman and @jmcmichael, this would presumably require a server change as well...

As with curation of genes at Entrez over time we are realizing in CIViC that we are starting to see multiple terms refer to the same variant concept.  Sometimes competing terms to describe a variant both have a strong following.  We should choose one, but also have the ability to store these variant synonyms.

For example,
https://civic.genome.wustl.edu/#/events/genes/19/summary

EGFR currently has an 'AMPLIFICATION' variant and a separate 'INCREASED COPY NUMBER' variant.  Unless we can clarify how these are different we should probably merge these under 'AMPLIFICATION'. But it would be nice if we could record on the variant entry that others may refer to it by 'INCREASED COPY NUMBER'.

This is a classic example where MGI curators used one term and BCGSC curators used another term but we are talking about the same thing.

**Comment by acoffman** [comment]
We could definitely introduce the concept of alternate or secondary variant names pretty easily! We already have alternate names for genes (though they aren't able to be modified or interacted with like this since they're just from MyGene.info).

This wouldn't be all that different and we could use them to match against when users are searching for evidence items.

**Comment by malachig** [comment]
Yeah that would be great.  That way when a curator comes to CIViC and searches using a synonym they will hopefully realize that their variant of interest is already in place and enter evidence there instead of creating a new (ambiguous) variant.

**Comment by jmcmichael** [comment]
No problem adding these to the UI and suggested revision forms. These aliases should also be included in the various search and datatables results.

**Comment by malachig** [comment]
Pinging on this one.  In recent talks we were talking this up as a value added feature for contributors to CIViC (we will help you find evidence for the same variant that is being discussed under a different name).  After talking about it publicly I remembered that this feature is not live yet. :)

**Comment by acoffman** [comment]
This should be fairly straightforward to add!

**Comment by jmcmichael** [comment]
(implement same as variant types, also with typeahead)
