### ISSUE TITLE
Minor issues with submit evidence flow

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#237]
When I submit a new evidence item I noticed a few things.
1.) When I hit the submit for review button I was shown a message saying that it had been submitted for review.  Can we get a link here to take us to the evidence item with submitted status.

2.) Even though I have 'Show Submitted' option selected in evidence grid, I had to do a force refresh of the page to see my new evidence item.  Even if I left the page by going to browse and clicking on the new event in the event stream it would not show until a refresh.

**Comment by jmcmichael** [comment]
Split issue #2 into its own issue, #241.

**Comment by malachig** [comment]
Sorry, you're right this should have been two issues.
