### ISSUE TITLE
Duplicate diseases in drop down that differ only in their capitilization

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#238]
Not sure if this is a server or client issue.  May require input from @acoffman.  I entered an evidence item and noticed that it had a disease name that was identical to others that differ only in their use of capitalization.

Now we have evidence items that have disease `Acute Lymphoblastic Leukemia` and `acute lymphoblastic leukemia`.  See these two for example:

https://civic.genome.wustl.edu/#/events/genes/73/summary/variants/200/summary/evidence/625/summary
https://civic.genome.wustl.edu/#/events/genes/73/summary/variants/200/summary/evidence/626/summary

In this screenshot we can see that the underlying DOID is the same.

![screen shot 2015-10-08 at 6 57 40 pm](https://cloud.githubusercontent.com/assets/856728/10382904/936bc944-6dee-11e5-9dea-bccde03335c6.png)

**Comment by acoffman** [comment]
That looks like it may be a server issue, taking a look today!

**Comment by acoffman** [comment]
All duplicate diseases have been merged! We shouldn't get these going forward!
