### ISSUE TITLE
Can column headers display full name/description on hover?

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#239]
For example in the evidence item grid, could EID, DESC, DIS, etc. display their full names on hover?

**Comment by jmcmichael** [comment]
Mmmmmaaaybe. Last time I checked the headers were kind of a pain to customize with anything more than a simple string (no HTML without a lot of tinkering), I will check out the latest version to see if this is easier now.

**Comment by malachig** [comment]
Okay, if its too painful I'm fine if we punt on this for now.

**Comment by jmcmichael** [comment]
Turned out pretty easy to do.

**Comment by malachig** [comment]
Awesome!
