### ISSUE TITLE
Event stream events for accepted evidence missing verb

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-client#240]
When I accept a newly submitted evidence item it appears in the evidence stream as "obigriffith evidence item KRAS ...". I think it should say something like: "obigriffith accepted evidence item..." 

![screenshot 2015-10-09 09 58 13](https://cloud.githubusercontent.com/assets/1638042/10395861/36a4684a-6e6d-11e5-8724-6eab33a96e25.png)

**Comment by jmcmichael** [comment]
Fixed. BTW, event items now include a humanized timestamp:
![screen shot 2015-10-09 at 11 03 16 am](https://cloud.githubusercontent.com/assets/132909/10398934/587328e6-6e75-11e5-871e-0355fdf40f14.png)
