### ISSUE TITLE
evidence grid instructions needs layout work for smaller and mobile breakpoints

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-client#244]

**Comment by kkrysiak** [comment]
I was playing around with the website and my iPad. See attached screenshots. There are a few formatting things that may be improved but the biggest issue is the appearance of the sign in button prior to sign in. It's almost impossible to see. You can see it right next to the FAQ in the first screenshot if you really look hard. Once I signed in, you can easily see it in the 3rd screen shot.

![image](https://cloud.githubusercontent.com/assets/8527125/10703615/cd299a0e-7996-11e5-998a-dc05c0edda1b.png)
![image_1](https://cloud.githubusercontent.com/assets/8527125/10703617/cf317e5c-7996-11e5-9f65-647a8027bc86.png)
![image_2](https://cloud.githubusercontent.com/assets/8527125/10703627/d75205fc-7996-11e5-9296-9137d184ebf1.png)
