### ISSUE TITLE
Clinical Significance is not displaying

### ISSUE THREAD

**Issue by nspies13** [genome/civic-client#25]
When clicking on an evidence item, the clinical significance field is blank.

**Comment by acoffman** [comment]
This looks like an issue with the spreadsheet - the column is named "Clinical Signficance" I'll fix the typo and prepare a new data dump.

**Comment by nspies13** [comment]
Ha... My bad.

**Comment by acoffman** [comment]
Ha, no worries, I should have caught it too! Pushing the fix to master shortly.
