### ISSUE TITLE
implement adv. search by gene, variant, variant group, user

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-client#257]

**Comment by malachig** [comment]
For clarity, each of these searches should probably be on their own tab.  i.e. `Evidence Items` -> `Genes` -> `Variants` -> `Variant groups` -> `Users`.

@acoffman or @jmcmichael if you could stub in the basic framework for these tabs, one of us could perhaps work through setting up and testing various queries using the existing search code as an example.

**Comment by jmcmichael** [comment]
Implemented gene, variant, vg advanced searches. User search can be accomplished on the Community page.
