### ISSUE TITLE
Search for Variants in Quick Event Search

### ISSUE THREAD

**Issue by nspies13** [genome/civic-client#26]
Requiring the gene before the variant in quick event search is a bit frustrating, and may lead people to believe a variant is missing. Typing 'V600E' should bring up BRAF V600E. And G12D should drop down all the RAS's with G12 entries.

**Comment by nspies13** [comment]
@acoffman I think this might require both front-end and back-end fixes.

**Comment by acoffman** [comment]
I think the backend is ready to support this, I'll coordinate with @jmcmichael on the frontend changes.
