### ISSUE TITLE
search page evidence grid does not display multiple drugs in drug column

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-client#261]

**Comment by jmcmichael** [comment]
This appears to be due to some crazy edits that I did when testing on my local installation - I do not see this issue on the live server.

**Comment by malachig** [comment]
Hmmm,

I'm seeing this in the live site for both the search and browse view.  For example:
https://civic.genome.wustl.edu/#/events/genes/19/summary/variants/34/summary/evidence/642/summary#evidence

![screen shot 2015-10-29 at 6 00 18 pm](https://cloud.githubusercontent.com/assets/856728/10834386/06ba8f24-7e67-11e5-8988-c3ef7b001ce8.png)

![screen shot 2015-10-29 at 6 00 41 pm](https://cloud.githubusercontent.com/assets/856728/10834392/0f196186-7e67-11e5-805b-636eb7955bbc.png)

**Comment by jmcmichael** [comment]
Oops, yeah - will get to the bottom of this.

**Comment by jmcmichael** [comment]
This looks like a server issue, Adam is looking into it.

**Comment by acoffman** [comment]
This is fixed in master and will go out next deploy!
