### ISSUE TITLE
Suggested revisions search has extra drop down filter

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#262]
I went through all the primary search options.  All of the customized search filters look good except this one:

![screen shot 2015-10-29 at 10 18 31 pm](https://cloud.githubusercontent.com/assets/856728/10837821/cba33baa-7e8b-11e5-85dc-826aaf23c3c5.png)

The second filter with `is greater than or equal to, is greater than, is less than, etc.` could probably just be dropped.  

Overall, the search page is really looking and working amazingly. :)

**Comment by malachig** [comment]
So I was misunderstanding this.  This query is determining the `evidence items` with some number of `revisions` that match a certain `status`.  This could probably be worded a bit more elaborately to make this more intuitive.  Looking at it though I'm not sure how to achieve that.  Maybe we could pre-populate the count field with '0' so that the most relevant query is ready to go.  Otherwise I think this one was mostly user error/misunderstanding on my part.

**Comment by kkrysiak** [comment]
I also didn't register this until I saw this issue update but I can't think of how to improve the clarity either. My best solution is that this might be clarified by adding the canned example searches.

**Comment by malachig** [comment]
Ok lets just close this one.
