### ISSUE TITLE
implement saved advanced searches

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-client#263]
Adam has created a system for saving searches that works as follows:

- submit an advanced search as usual, but with the addition of a 'save' boolean parameter on the root POST object
- if save is true, the server will return an object:

``` json
{
  "params": {
    "operator": "AND",
    "queries": [
      {
        "field": "description",
        "condition": {
          "name": "contains",
          "parameters": [
            "Ca"
          ]
        }
      }
    ],
    "format": "json",
    "controller": "advanced_search",
    "action": "create",
    "advanced_search": {}
  },
  "token": "unique token string",
  "results":[ "array", "of", "result", "objects"]
}
```
params: original search params, for reconstructing the search form
token: unique token for later retrieval of the results and search params
results: array of search results

```
localhost:3000/api/evidence_items/search/[TOKEN]
```
will return both the search parameters (for rebuilding the search form) and the search results.

**Comment by malachig** [comment]
This is going to be super useful for editors, advanced curators, and users with specific use cases.
