### ISSUE TITLE
event stream shows two people accepting same new evidence item

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-client#264]
I accepted a new evidence item but KK got there just before me. I didn't receive an error and both of us are credited with accepting EID646. Although, in the evidence item log only one acceptance is shown so that is working.

![screenshot 2015-11-09 14 41 17](https://cloud.githubusercontent.com/assets/1638042/11045963/141e7360-86f0-11e5-98b1-6791af375198.png)

**Comment by acoffman** [comment]
This now happens transactionally and with locking, so there is no longer a race condition on accepting evidence items. Fix is in master and will go out with next deploy.
