### ISSUE TITLE
comments on revisions requires page reload

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#268]
This one is subtle but consistent and can be confusing.

If I review a suggested revision to an evidence item and make a comment.  When I submit the comment it appears.  I then accept or reject the revision and everything seems fine.  But if I navigate away somewhere and come back to this revision, my comment appears to be gone.  Until I do a page reload, then I see it again.

**Comment by jmcmichael** [comment]
Nice catch. Probably I'm missing a cached list of comments that I need to flush when a comment is submitted on a suggested revision.

**Comment by malachig** [comment]
This appears to be fixed now.
