### ISSUE TITLE
community page improvements

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-client#269]
include selects for role, area of expertise
default sort by last_seen
visual cue on userCard for area of expertise, role

**Comment by obigriffith** [comment]
I think it would be ultimately really great if the community page was by default broken into separate sections for editors, curators, admin/moderators perhaps in that order. My thinking is that we want a way to really promote the editors as these are the people that we are going to try to recruit. They will either come in as valuable experts at the editor level already (based on their external expertise) or be promoted from curator to editor role after they have demonstrated expertise through activity. It should be a "big deal" to make it to the editors section/page.

**Comment by jmcmichael** [comment]
Done. Moving the separate pages for community members feature to another issue.
