### ISSUE TITLE
add gene strand to mygeneinfo box

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-client#270]

**Comment by jmcmichael** [comment]
Done - now displaying strand + start, end, and chr.

**Comment by malachig** [comment]
It looks like these coordinates are from build38 (hg20) of the human genome reference. These may cause confusion with the mostly build37 (hg19) coordinates being used for all variants below.

Can we instead pull the hg19 coordinates from mygene.info ??

We checked and they are there.

We should also clearly indicate in the mygene.info box that the coordinates being displayed here are from build37.

**Comment by acoffman** [comment]
Yup! It looks like you're correct - we can get the hg19 coordinates from the API and use those instead. I'll update the query we're using.

**Comment by jmcmichael** [comment]
OK, Adam updated the server API for the my gene info endpoint, and I've updated the client as well.
