### ISSUE TITLE
already closed/rejected revision still shows/allows accept/reject buttons

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-client#276]
There was a variant with two revisions. One had already been rejected/closed. The other was new/pending. But, the closed/rejected revision still had reject and accept buttons active. From a dangerous sense of curiosity I hit the reject button. It allowed me to reject again without warning but apparently no harm was done. However, it also let me accept the revision. This then caused the other newer/pending revision to switch to superseded status. Now that the older revision had mistakenly been accepted there was no way to reverse course and reject it. The newer revision could not be accepted because it now conflicted with the older accepted revision. So, I had to reject the newer revision and create a new revision. 

Is there any reason why we should allow a rejected revision to be re-rejected (pointless) or accepted? My gut feeling is that once rejected a revision should stay rejected and if someone disagrees they should have to resubmit a new revision.

**Comment by jmcmichael** [comment]
I've added logic to the templates to hide the admin buttons on rejected revisions (previously it had only hidden them on applied revisions, not rejected - my bad).

**Comment by malachig** [comment]
It seems like this issue is still happening in the live site.  When you reject a revision, the `accept`/`reject` buttons remain visible.

**Comment by malachig** [comment]
I think this is now fixed again.
