### ISSUE TITLE
Revisors are not showing on community page of live site

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#277]
The new community page is looking amazing.  One minor issue I see is that there are no `Top Revisors` listed. 
https://civic.genome.wustl.edu/#/community/main

When I look at my own activity profile:
https://civic.genome.wustl.edu/#/users/15/profile

I do see some revisions being listed.  For example,
https://civic.genome.wustl.edu/#/events/genes/4/summary/variants/241/talk/revisions/list/421/summary

**Comment by acoffman** [comment]
I believe this is a server issue, related to my backfilling of the attribution stuff now that its deployed. Should be fixed this evening!

**Comment by malachig** [comment]
Awesome. Thanks @acoffman

**Comment by acoffman** [comment]
Fixed on the live site!
