### ISSUE TITLE
Correct display of variant group description heading.

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#28]
For genes with multiple variant groups. Under the "variant group talk" tab, the ID of the variant group is being displayed prior to the heading. So it says "2 Description" instead of just "Description".

**Comment by nspies13** [comment]
I got this! All done and closed out.

**Comment by nspies13** [comment]
@jmcmichael I changed the variantGroup.id entry to variantGroup.name in line 5 of this file. 
views/events/variantGroups/directives/variantGroupTalkComments.tpl.html

Is there anything downstream that would have been affected that I am overlooking?

**Comment by jmcmichael** [comment]
This looks good to me, please reopen if I missed something.
