### ISSUE TITLE
Minor refresh issue after variant name is changed

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#280]
After applying a variant name change, the tab name doesn't automatically refresh like the header does. Variant was updated from R359Q to K359Q.

![screen shot 2015-12-02 at 12 27 39 pm](https://cloud.githubusercontent.com/assets/8527125/11540113/9f61e616-98f0-11e5-8312-473d9f14294e.png)

**Comment by malachig** [comment]
I also noticed that the revision status does not update in the revision table when you accept a revision.  Also requires page reload.
