### ISSUE TITLE
create separate community pages for member types?

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-client#282]
In a separate issue, Obi wrote, "I think it would be ultimately really great if the community page was by default broken into separate sections for editors, curators, admin/moderators perhaps in that order. My thinking is that we want a way to really promote the editors as these are the people that we are going to try to recruit. They will either come in as valuable experts at the editor level already (based on their external expertise) or be promoted from curator to editor role after they have demonstrated expertise through activity. It should be a "big deal" to make it to the editors section/page."

**Comment by obigriffith** [comment]
To be clear. I am not sure if separate pages are needed or just separate sections, or tabs within a page. Open to suggestions. But the main idea is to have an expert editors page/section/tab that is something to strive towards and maybe even need to maintain activity to stay there.

**Comment by obigriffith** [comment]
I think this issue will solved by the new About page.
