### ISSUE TITLE
help page overview tables inconsistent

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-client#305]
The help page table for Evidence is inconsistent with those for Variants, Genes, and Variant Groups. 

Evidence has: Attribute, Description and Example.

Variants, Genes, and Variant Groups has: Attribute, Description, Source, and Editable. 

I propose that we rework them so that all follow the same pattern and have the following: Attribute, Description, Example, and Source. I think all of the tables/fields will benefit from examples. And, the 'Source' value will either be the external source (Pubmed, Disease Ontology, Entrez etc) or CIViC where a value of CIViC implies that it is editable. 

Thoughts?

**Comment by kkrysiak** [comment]
I like this proposal overall, however, I think the implied editable portion gets a little hairy with external sources. For instance, the disease (DOID) is an editable field but source of the information is external, although if it's a custom one it can be internal. I kind of liked the edit yes/no field. Perhaps we can make this prettier with an icon or something to indicate editable fields (or non-editable fields).

**Comment by kkrysiak** [comment]
This is probably a better example of the level of complexity that I'm thinking about and I'm wondering if there is a better way to handle this.

![screen shot 2015-12-10 at 2 22 28 pm](https://cloud.githubusercontent.com/assets/8527125/11727457/886d68fe-9f49-11e5-9740-5ff2e64a8406.png)

**Comment by malachig** [comment]
I think it would be good if we could maintain the ability to indicate what things are editable or not.  But I'm sure we can do it in a more compact way.  I think using the same icon and placing it beside each attribute name would do the trick.  Then maybe we have a footnote that explains the meaning of that symbol or include it in the preamble section at the top.

Also like the idea of making these tables more consistent if we can without it feeling too forced.

**Comment by kkrysiak** [comment]
Fixed with commit ef776744f858aa7b19765ac653984d3fec49f2cb
