### ISSUE TITLE
refactor help section such that each major section has its own state

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-client#306]
This will allow direct linking to a help section, and the Back button working as expected when linking out of sub-sections.

**Comment by malachig** [comment]
Hi @jmcmichael, this is super helpful.  One note, it looks like the last two items in this list `Get Help` and `Report Problem` still share the same state: `/#/help/get`.  Was that deliberate?

Based on the others it looks like these could be:
`/#/help/getHelp` and `/#/help/reportProblem`.
