### ISSUE TITLE
create google sitemap.xml file for better indexing

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-client#307]

**Comment by obigriffith** [comment]
This has kind of dropped off the radar but will be increasingly important as the science content continues to improve and we try to raise the profile of CIViC. Right now if someone googles for "cancer variant interpretation database" or similar they will find CIViC. But, if they are looking for "WT1 mutation" or similar they likely will not find CIViC unless they also include "civic" as a search term and even then... ironically google returns lots of other civic-related hits such as from the two github repos, SolveBio's import of CIViC data, etc but not the actual CIViC page for that variant/gene.

**Comment by jmcmichael** [comment]
Also: figure out how to incorporate metadata for improved SEO, page descriptions, etc.

**Comment by jmcmichael** [comment]
@acoffman, this modification will place a sitemap.xml file into /dist during the build task. I'm assuming that your build process will then place this in the root of the site, but I wanted to give you a heads up in case you needed to tweak configuration files or deploy process.

**Comment by acoffman** [comment]
@jmcmichael awesome - thanks for the heads up! That should work fine with the existing build process.
