### ISSUE TITLE
why did nightly downloaded files contain less records than previous data release?

### ISSUE THREAD

**Issue by jyu2012** [genome/civic-client#312]
I thought "nightly" means the latest build which should contain the most records? Do I misunderstand it?

**Comment by obigriffith** [comment]
Yes. It looks like we have several issues with the tsv dumps. 

(1) The nightly dump seems quite out of date. 

(2) The latest monthly dump (01-dec-2015) for GeneSummaries.tsv lists all genes, not just genes with at least one evidence statement as expected. 

(3) In ClinicalEvidenceSummaries.tsv. (A) the pubchem_ids column is always empty. We can probably drop this column. (B) Where multiple drugs are listed we should probably show the Drug Interaction type. (C) The Evidence Level, Variant Origin, field is missing.

**Comment by obigriffith** [comment]
We should also think about including evidence statement status for the ClinicalEvidenceSummaries.tsv and only including genes, variants, and variant groups in the other three TSVs if they have at least one evidence statement (possibly of accepted status?).
