### ISSUE TITLE
Evidence level - swap 'C' and 'D' for all evidence items - client side

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#314]
After feedback from clinicians and users we have decided that the order of evidence levels should be adjusted to:

    A Validated
    B Clinical
    C Case Study
    D Preclinical
    E Inferential

Need to change the labels but also help docs on the client side.

Related to server side issue: https://github.com/genome/civic-server/issues/138

**Comment by kkrysiak** [comment]
Starting a list of Client-side help pages where we would need to update this:
src/app/pages/help_evidence_levels.tpl.html
src/app/views/add/evidence/addEvidenceBasic.js

**Comment by jmcmichael** [comment]
Done.
