### ISSUE TITLE
Link out to disease ontology entries for evidence items

### ISSUE THREAD

**Issue by acoffman** [genome/civic-client#315]
The Disease Ontology recently implemented a mechanism for directly linking to their entries (http://www.disease-ontology.org/news/). We should take advantage of that!

**Comment by kkrysiak** [comment]
Due to popular demand the direct term link has a new format:
http://www.disease-ontology.org/?id=DOID:12365
This allows for term information to be displayed directly in the content panel, not in a separate page, while also expanding the ontology tree to show the specific term.

**Comment by acoffman** [comment]
Pushed changes the master branch of both the client and server, this is now working! It ill go out in the next release.

In the event that its a disease without a doid, it will currently link to the disease ontology homepage instead of a specific disease page. We can change that behavior as desired though!
