### ISSUE TITLE
Evidence level search work with `is below` and `is above` but not `is`

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#318]
@acoffman not sure if this is related to server side or not.

As described.  On the advanced search page:
https://civic.genome.wustl.edu/#/search/

I can find evidence items that are 'above' or 'below' a particular evidence level (e.g. level C).  However, when I try to get evidence items that are a certain level the query fails.  

The javascript console says this:
```
https://civic.genome.wustl.edu/api/evidence_items/search/ 500 (Internal Server Error)(anonymous function) @ vendor-c611bef5.js:10722v @ vendor-c611bef5.js:10515c @ vendor-c611bef5.js:10222s @ vendor-c611bef5.js:14745(anonymous function) @ vendor-c611bef5.js:14761f.$eval @ vendor-c611bef5.js:15989f.$digest @ vendor-c611bef5.js:15800f.$apply @ vendor-c611bef5.js:16097(anonymous function) @ vendor-c611bef5.js:91203n @ vendor-c611bef5.js:3298
```

The weird thing is that when I look at what I think is the code, everything seems to be in order.

Everything seems to be in order in this file on the client side:
src/app/views/search/SearchController.js

And on the server side:
app/models/advanced_searches/evidence_item.rb

For my own understanding I would be curious to better understand how to resolve this one.

**Comment by malachig** [comment]
Further error message:
```
PG::UndefinedFunction at /api/evidence_items/search
===================================================

> ERROR:  operator does not exist: integer ~~* integer
LINE 1: ..."."deleted" = $3 AND (evidence_items.evidence_level ILIKE 2)
                                                               ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.


app/presenters/advanced_search_presenter.rb, line 20
----------------------------------------------------

``` ruby
   15   
   16     private
   17     def results
   18       searcher = saved_search.searcher
   19       searcher.search
>  20         .map { |r| searcher.presentation_class.new(r) }
   21     end
   22   end
```

App backtrace
-------------

 - app/presenters/advanced_search_presenter.rb:20:in `results'
 - app/presenters/advanced_search_presenter.rb:12:in `as_json'
 - app/controllers/advanced_search_controller.rb:18:in `create'
 - app/middleware/cross_origin_request.rb:7:in `call'
```

**Comment by acoffman** [comment]
This required both a small frontend and a small backend change. Both fixes are pushed and will go out in the next release!

**Comment by malachig** [comment]
Hi Adam, can you reference the commits here.  I have been trying to reverse engineer some of this code and it could be super educational for me!  :)

**Comment by acoffman** [comment]
@malachig Sure thing!

The client side fix is here: https://github.com/genome/civic-client/commit/96e91332bc8bafb89379ea9c0ce3f15bd9327d21 and the server side fix is here: https://github.com/genome/civic-server/commit/b93e8db9f858cd0ee9974d67f2556546840ea669

The client side fix is essentially changing what the frontend is sending to the server. Before it was sending a string comparison equality operator but it needed to be sending a numeric equality operator as evidence level is stored as an enum. The server side fix is in a special method that's set up specifically for evidence level to handle less-than and greater-than comparisons. We actually have to swap which operators we use as 'C' 'is_below` 'A' logically, but that's not how they'd sort using a tradtional `<` or `>` operator.

**Comment by malachig** [comment]
Man I was so close to having this solution.  The code all seemed quite logical and actually not bad to follow.  I tried things very similar to this but just didn't make the connection that I needed to add the extra comparison type to the `reverse_order_operations ` list.  Thanks for explaining!
