### ISSUE TITLE
Retrieval of genes through API

### ISSUE THREAD

**Issue by sigven** [genome/civic-client#319]
Hi,

I just tried your API to retrieve all the genes in the CIVIC database (with your local gene IDs), using the following URL:

**Comment by sigven** [comment]
https://civic.genome.wustl.edu/api/genes

However, it only returned 25 genes (from ALK to EGFR). I am sure there are more than these 25 genes in the databaes?

**Comment by acoffman** [comment]
Hi @sigven! Thanks for using our API. Right now, the genes endpoint is actually paginated, though the response and documentation need to be updated to reflect that. This is why you're only seeing 25, that's the first page with the default pagesize of 25. This has been discussed a little bit over here: genome/civic-server#82.

Until we get things updated, you can pass a `count` parameter (ie `?count=10000` or similar) to the request which will increase the page size enough for you to get all the genes in a single request. As the data set grows over time, this approach may not be future proof, but it will work for now!

Thanks again, and let me know if you have any other issues!

Adam
