### ISSUE TITLE
Must refresh page after a comment is deleted

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#322]
If I delete a comment I have to reload the page to get it to actually disappear.

For example in this view:
https://civic.genome.wustl.edu/#/events/genes/37/summary/variants/311/talk/revisions/list/707/summary

**Comment by jmcmichael** [comment]
Tracking this down - I'm not able to reproduce this behavior on my own installation, checking on the live install...

**Comment by jmcmichael** [comment]
@acoffman, I'm not able to reproduce this behavior on my local installation. However, on the live installation, while the comment is actually deleted, the server returns a 500 error. The odd thing is that's all it returns - Network DevTools just tells me 'This request has no data available.'

**Comment by malachig** [comment]
This appears to be resolved.
