### ISSUE TITLE
CIViC API doc link links to middle of page

### ISSUE THREAD

**Issue by zlskidmore** [genome/civic-client#324]
The link here:
https://civic.genome.wustl.edu/#/api-documentation

on the CIViC homepage links to the middle of the page instead of the top.

When clicking on the link at the homepage.

**Comment by jmcmichael** [comment]
Nice catch. I disabled auto-scrolling to the top of the page globally, as in the app parts of the site we want the UI to remain where it is (or move to specific locations/forms etc). I'll figure out how to selectively enable it for the more page-like sections of the site.

**Comment by malachig** [comment]
The API docs are now handled separately.  This can be closed now.
