### ISSUE TITLE
Variant list for a gene should not show a variant with only rejected evidence items

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#328]
For example:
https://civic.genome.wustl.edu/#/events/genes/19/summary#gene

There are at least two examples here where someone submitted evidence items that we later decided were not valid or the variant itself does not make sense to even exist. 

But once it existed once, it stays in the list at the left forever.  

Can we set the front end to hide variants with only rejected evidence items?

**Comment by kkrysiak** [comment]
This should also be accounted for in the total evidence item and variant count in the browse view (don't include rejected statements in the count) as well as exclude them from the type ahead search.

**Comment by acoffman** [comment]
On the main view page, we're only going to show variants with at least one submitted or accepted evidence item in the sidebar. We'll hide variants with only rejected evidence items behind an "expand" or "view all" button.

**Comment by jmcmichael** [comment]
In order to hide specific variants in the sidebar based on pending/accepted evidence items, I'll need some additional information in the variant attribute returned from the /gene endpoint. Right now the client gets an array of objects:

```javascript
gene: {
//...
variants: [{name: "C634W", id: 112}, {name: "M918T", id: 113}]
//...
}
```
To drive display logic in the sidebar, we could add another attribute in there:
```javascript
gene: {
//...
variants: [
  {
    name: "C634W", 
    id: 112,
    evidence_items: {
      pending: 1,
      accepted: 3,
      rejected: 0
    }
  },
  {
    name: "M918T",
    id: 113,
    evidence_items: {
      pending: 4,
      accepted: 5,
      rejected: 1
    }
  }
]
//...
}
```

**Comment by acoffman** [comment]
This data is now coming back from the endpoint as requested!
