### ISSUE TITLE
user mentions - don't work for users with spaces in user name?

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-client#329]
If I am writing a comment anywhere is CIViC I can mention a user (e.g., "@ecerami" or "@obigriffith") and it will create a link to their CIViC profile page. That's awesome. But, how does it work for a user who's Name and username are both "Malachi Griffith" or similar?

**Comment by obigriffith** [comment]
A simple fix for this could be to not allow spaces in the username field.

**Comment by kkrysiak** [comment]
I think we decided to implement obi's suggested fix, just don't allow spaces.

**Comment by jmcmichael** [comment]
This is fixed server side (display names with spaces are no longer allowed), but the profile edit form needs better error handling for cases where users attempt to edit spaces into their display name.
