### ISSUE TITLE
Add Variant/Gene tab would be helpful, and can point to add evidence page. 

### ISSUE THREAD

**Issue by nspies13** [genome/civic-client#33]
It would be nice to have buttons for adding genes/variants. This could land you at the add evidence page, maybe with a prompt that reads "Adding a gene or variant requires at least one evidence statement: Add it here!"

**Comment by jmcmichael** [comment]
I've added an 'Add Evidence' button to the subheader - I think this is the least confusing, simplest solution for now. We definitely need to discuss and brainstorm on this further.
