### ISSUE TITLE
add ability to search by evidence id in advanced search

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#331]
If someone refers to an EID in an email or something, it is actually not easy to find that evidence without further information.

Currently I think the admin interface is required.

**Comment by kkrysiak** [comment]
They can be found through the advanced search on the main website but not in an easy way. With how items are displayed in the admin interface, I've often wished for a way to quickly navigate to them. I have 2 ideas for that:
1) Allow for searching by EID in the main search box. Although I worry it will get too busy and it will be difficult for low numbered EIDs (e.g., EID1) to search by just the number without the EID prefix.
2) Add it as a search field in the advanced search. If EID is equal, greater than, less than or in a range.

**Comment by malachig** [comment]
They can be found through the advanced search on the main website?  Maybe I haven't had enough coffee. :).  Which would I select in this drop down to search by evidence ID?

<img width="639" alt="screen shot 2016-02-09 at 2 09 38 pm" src="https://cloud.githubusercontent.com/assets/856728/12929142/e62e6980-cf36-11e5-96a5-89221a1b23cb.png">

**Comment by acoffman** [comment]
It would certainly be easy to add EID as an advanced search option. I can definitely do that. I've also considered the possibility of having some sort of shortlink system. An EID uniquely identifies an evidence item, so in theory it provides all the context we need to create a link on the site to that item. If people could just visit `/evidence/$EID` or something, that would make things easier. I can talk to @jmcmichael about the feasibility of this.

**Comment by malachig** [comment]
It would also be nice if you typed `EID123` in a comment that it would automatically generate a link to that record.

**Comment by kkrysiak** [comment]
@malachig I currently cheat by selecting all evidence items using "Evidence Level" > E and sort by EID. It takes some scrolling but gets you there.

**Comment by malachig** [comment]
Oh okay. Now I understand. @acoffman do you mind if I take a crack at implementing this and submit a pull request. I think I have it working in a checkout with a minor tweak to both repos.  I will do this on a branch for each repo and submit a pull request for each.

**Comment by malachig** [comment]
Okay I created two pull requests. 
Server side: https://github.com/genome/civic-server/pull/152
Client side: https://github.com/genome/civic-client/pull/333

**Comment by malachig** [comment]
I think this is working but the Travis-CI build is failing on the server side. @acoffman I will probably need a bit more info on how to test properly prior to pushing...  I also get 8 failures when I do a `rake spec` in my checkout.  I also get those on the master branch though so perhaps I just don't have me environment set up correctly for local testing.

**Comment by acoffman** [comment]
The test failures look like they are unrelated to this PR - I'll take a look! The server side PR looks good to me.

**Comment by malachig** [comment]
Okay understood.  Thanks!  @jmcmichael you cool with: https://github.com/genome/civic-client/pull/333

**Comment by jmcmichael** [comment]
Yeah, accepted your pull request, tested and pushed to master.
