### ISSUE TITLE
implement per-page permissions in order to restrict add/edit etc. pages to editors/admins only

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#335]
When I logged out the page was still visable even after I refreshed the page.

**Comment by jmcmichael** [comment]
This is definitely something that the app should do, but is a bit more difficult to implement than just toggling the page from its logged-in to its logged-out state. I still need to implement per-page permissions that will prevent non-editors/admins from accessing certain pages, and getting kicked off when they log out. Note that the the various action buttons will only display for logged-in editors/admins, so even if a regular viewer accesses the page, they won't be able to actually do anything.

**Comment by kkrysiak** [comment]
Buttons are hidden to prevent adding anything this way. I think this is fine.
