### ISSUE TITLE
Fields in the Add Evidence page should be separated by required and not-required. 

### ISSUE THREAD

**Issue by nspies13** [genome/civic-client#34]
Requiring that each field is filled is a major burden for a curator. Many of these can be back-filled by us post-curation. Required fields should be: Gene Name (Not Entrez ID), Variant Name, Disease (Not DOID), Source (PMID is greatly appreciated but not required), Evidence Summary, Evidence Type, Evidence Level, Clinical Significance, Evidence Direction, Evidence Rating, Comments. 

We also need to discuss these... Keeping the barrier to entry as low as possible is my personal priority #-1, but maybe @obigriffith @malachig may feel differently.

**Comment by jmcmichael** [comment]
A low barrier to entry for users to get information into the CIViC database is definitely an important design goal, but another important goal that we've identified is building a database of precise, structured data. Having precise, structured data allows us to provide a more structured, intuitive, and reliable API, develop interfaces and forms that know more about the data they're displaying and asking for, and makes the data just more usable and easier for 3rd parties to integrate and build upon.

To that end, we all have made an attempt to precisely define the fields that we're interested in and how they will be stored, behave in the user interface, and be available to the outside world via the API.

If this focus on precise, structured data is projected throughout the system, from the database tables to interfaces that moderate how the data gets into the system, we'll likely end up with a precise, structured data set. To that end, our forms should insist on precise, structured information. Consequently this will will make the submission flow simpler (it won't have to take into account edge cases were people enter incorrect information), it will make administration easier (admins and/or the community won't have to deal with incomplete submissions in various states of approval), and I think it will result in higher-quality data.

Additionally, do we really want users who have trouble locating entrez IDs and disease IDs to be contributing to the database? This seems to be a relatively low barrier to entry for the kind of user we've targeted to be high-quality, active content contributors and moderators.

That said, we definitely want to make this process as easy as possible, so Adam and I are planning several features on this form that will ease the job of finding and entering accurate entrez IDs, drug IDs, etc.

As user enters data into the form, it can relay the current field value to the backend server, which will then query the relevant database to verify the ID, and if it is valid, fetch the record and display the relevant details (gene name, disease name, citation title) in the form so the user may verify it. If the ID is not valid, the form can display the error as well as information on how to locate the correct ID. Depending on the features of the APIs these 3rd parties offer, all of the searching and identification of valid IDs could be conducted from the evidence entry interface (note that these are post-AGBT goals).

Does that sounds like a acceptable compromise on ease-of-data entry & moderation vs. maintaining structured data?

**Comment by nspies13** [comment]
I agree that the value of structured data is immense. I guess the unanswered question remains "who will be doing most of the curation?". If it is clinicians, these tasks may discourage them from entering their high-quality evidence because the process seems daunting. I'm not sure how reasonable it is to expect clinicians to contribute, but if they want to, their information would be very valuable. I think these cases might be few and far-between, allowing a moderator to fill-in a structure to their data without it becoming unmanageable. 
I like the fixes you have proposed. And certainly we can discuss this more in the coming future.

**Comment by obigriffith** [comment]
This does seem like a reasonable compromise. My main concern is that in fact a typical user will rarely "get it right" the first time. A really important attribute that is currently missing (but we need) is the actual genome/transcriptome coordinates. When we add that, we may have to accept a workflow that allows non-bioinformatics users to create an incomplete submission that is later completed and validated by another user. Once we accept that workflow then it seems some (but not many) other fields could also be optional.

**Comment by malachig** [comment]
I agree with the spirit of everything @jmcmichael has said.  But I think we should go through each element of an evidence statement and talk through some of the gotchas that apply certain fields.
- [ ] Coordinates (fields still not formally defined in the DB?) 
- [ ] Gene Name (Not Entrez ID)
- [ ] Variant Name
- [ ] Disease (Not DOID)
- [ ] Source (PMID is greatly appreciated but not required)
- [ ] Evidence Summary
- [ ] Evidence Type
- [ ] Evidence Level
- [ ] Clinical Significance
- [ ] Evidence Direction
- [ ] Evidence Rating
- [ ] Comments

Is this really everything?  We should walk through each of these and decide as a group what is absolutely required, or optional, and what the consequences of those decisions might be.  Here are some things that come to mind immediately.

- On the topic of DOID.  If we absolutely require this, what does that look like from the user perspective?  Will we have to implement our own method of checking validity automatically?  Are there diseases with valuable information that we want to capture but where there is no obvious DOID now?
- On the topic of Entrez Genes.  Assuming we have decided on a convention for how to handle gene fusions, and this is well explained to the user, is there a reason to *not* enforce compliance with Entrez standards. i.e. if they enter a name it must unambiguously map to a valid Entrez gene or the evidence statement is invalid and can not be submitted.
- On the topic of PubMed ID. If we do not require this, we might wind up with cases where the citation is not obvious.  Basically we can't figure out what evidence they are actually citing.  On the other hand, I think there is a lot of valuable data out there that does not have a pubmed ID but at least initially I thought we had no plan to allow such data...  Again I'm tempted to say that if you can provide a PubMed ID maybe we shouldn't trust you evidence statement.  From the perspective of building a training set for machine learning on Abstracts in the PubMed database, this link is critical. Of course it would be trivial to grab the subset of statements where PubMed ID was defined.
- Several fields would seem to consist of enumerated lists where the choices are completely non-negotiable.  e.g. you must chose one of: 'predictive', 'diagnostic', 'prognostic' for evidence type.

**Comment by malachig** [comment]
Fields that are still up for debate.  The others have been checked off the list above:
- Coordinates.  This is still a work in progress.  
- Gene identifier.  I think we are in agreement that we should not ask the user to look up an Entrez ID.  Instead we should ask for Gene Symbol and explain to the user that we mean Gene Symbol from Entrez.  If we can implement a system that looks up synonym and helps the user resolve ambiguous names, then maybe this can be required.  i.e. that it must unambiguously match an Entrez gene symbol.
-

**Comment by malachig** [comment]
@acoffman is going to look into whether we could clone the DOID database so that we can do name lookups?  Strategy would be that the user types in a disease name and is displayed first options for diseases already in our database, and second options from the DiseaseOntology.  Or the user could enter the DOID directly.

**Comment by jmcmichael** [comment]
I think we've developed the Add Evidence form to the point where we're OK with the required/optional behavior for the various fields.
