### ISSUE TITLE
Add an evidence grid to the user profile screen. 

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#340]
I would envision this evidence grid contains all evidence submitted by a given user, would display like what is seen in the advanced search (so includes gene and variant names), and have basic sorting/filtering options along the top. 

I still like the activity feed that is currently on the users profile. Maybe the evidence grid could be on a second tab so activity is always the default but you can click on the evidence grid tab to see all your evidence statements.

**Comment by jmcmichael** [comment]
I've added an evidence grid to the profile page, but the method I'm using to fetch a user's submitted evidence items might not be the best.

@acoffman, what I did was submit a search to the advanced search endpoint:

```json
{
   "operator":"AND",
   "queries":[
      {
         "field":"submitter",
         "condition":{
            "name":"is",
            "parameters":[
               "jmcmichael"
            ]
         }
      }
   ]
}
```

The iffy thing is that the 'is' condition didn't exist in previous advanced search forms - we just had 'contains' and 'starts with'. I tried 'is' - assuming that it would only match exact display_names - and it seemed to work but then when I logged in as a different user and submitted an evidence items, both profile pages show both evidence items. I added a server issue (genome/civic-server#160) for this.

**Comment by obigriffith** [comment]
Looks great!

**Comment by malachig** [comment]
Yeah, this is awesome

**Comment by jmcmichael** [comment]
Yeah, great idea @kkrysiak!

**Comment by obigriffith** [comment]
Yeah. I think this came out of discussion between @arpaddanos and @kkrysiak.

**Comment by kkrysiak** [comment]
Yep, I can't take all the credit on this one. :) Thanks @arpaddanos!! @jmcmichael it looks great!
