### ISSUE TITLE
Warn users of outstanding suggested changes to a given field before allowing them to submit

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#342]
A few times now I've run into evidence statements more than one of us have suggested near identical changes to. Once clicking submit, it would be great if a warning popped up that "A revision exists for 1 or more fields you are editing are you sure you want to submit? Click Review suggested changes or submit revision."

**Comment by malachig** [comment]
Yeah this would be nice.

This issue is related to https://github.com/genome/civic-server/issues/155.  If there were a visual hint before you even got to editing that the thing you were about to edit already has outstanding revisions this would help avoid duplication of effort.
