### ISSUE TITLE
Unusual display quirk in revision diff

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#343]
Not sure why but some text wound up displayed outside the diff insertions/deletions. I'm running Firefox and haven't observed this before but thought I would note it.

"Cetuximab-treated patients with AREG-low KRAS wild type CRC had a poor survival, similar to KRAS mutated CRC." Is outside of the green insertions box.

![screen shot 2016-02-16 at 8 49 11 am](https://cloud.githubusercontent.com/assets/8527125/13079556/738cfba4-d48a-11e5-9f19-8bde763fd175.png)

**Comment by jmcmichael** [comment]
Interesting. That diff, unlike any of the others that I've seen from the Ruby gem that generates these, has an '<unchanged>' node in addition to '<ins>' and '<del>'. I didn't create any CSS position/formatting for that node, so it just gets dropped in there after the insertions and deletions.

It looks like this evidence item description actually contains two paragraphs, and the second paragraph is the unchanged string that appears outside any boxes. I bet if you remove that line break so the description is all one paragraph, the unchanged string will be incorporated into the ins/del blocks.

This whole revisions display is something that I want to refactor, as it's a barely-working mess of CSS that does the whole layout, and it's not easy to modify. I'll leave this issue as-is, unless we plan to have multi-paragraph descriptions before I get the chance to redo the revisions components.

**Comment by obigriffith** [comment]
This was probably a copy paste error or something. I think we should discourage multiple paragraphs in evidence statements. Even in variant and gene summaries I think our goal should be a single paragraph although someone might be able to convince me otherwise for those.

**Comment by jmcmichael** [comment]
Yeah I can probably able to implement a filter on the description textarea that will prevent line-breaks and show a small message when a user attempts to enter one.

**Comment by kkrysiak** [comment]
Is this the same problem? https://github.com/genome/civic-client/issues/309
