### ISSUE TITLE
Filter Drop Down For Evidence Level In Browse Evidence Grid Doesn't Contain "C" or "D"

### ISSUE THREAD

**Issue by acoffman** [genome/civic-client#348]

**Comment by acoffman** [comment]
The odd part about this is that it appears to only be a display bug. Clicking where "c" or "d" would be filters the grid appropriately.

**Comment by jmcmichael** [comment]
Yeah, I had accidentally used 'name' instead of 'label' in the definition object for the dropdown contents.
