### ISSUE TITLE
Advanced search evidence settings reset to default on refresh

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-client#350]
Sometimes it is useful to have an advanced search result opened in one tab of a browser while working on a specific curation task. For example I am searching for all evidence statements with status=accepted and suggested revisions with status=new and is_equal_to=0 and evidence type=predictive and then filtering for drugs that are N/A. This gives me all the predictive evidence statements that are missing a drug while skipping those that already have a pending revision (possibly fixing the missing drug). Then in a separate tab I can go to each evidence item and fix it. It would be nice if I could refresh the page on the advanced search result and have it update (drop items) as I fix them. But, instead it resets to defaults for each of my search terms. Is this desired?

I realize that I can just hit the 'search evidence items' button to refresh the search. So this is a low-priority issue.

**Comment by malachig** [comment]
Hmmm, to me this is the expected behavior of hitting refresh on a page like this... that it would initialize to the state you would see if you had just landed on this page.  If we make this the behavior on page refresh, we should add a reset query button.  Or maybe to discourage page reloading, create a button that refreshes the result (even though the existing button already does this...)

**Comment by jmcmichael** [comment]
The advanced search form *should* rebuild itself with the previously submitted parameters after a refresh. The saved search hash in the url (e.g. c037d085-16b5-42ee-88ee-ca133d1206ba) causes a request to the server to return the form parameters from the server, which the client uses to repopulate the search form. Are you seeing this hash in the URL after you perform a search? 

We've tried the specified search and the could not replicate this behavior in Chrome, FF, or Safari.

**Comment by acoffman** [comment]
In fact, you should be able to use that unique URL to share your search with others if that's a useful feature!

**Comment by malachig** [comment]
Oh right, I forgot about this.  Very cool.

**Comment by obigriffith** [comment]
The conditions are rebuilt but the selected values forgotten. See before and after images from chrome.

![screenshot 2016-02-18 13 08 40](https://cloud.githubusercontent.com/assets/1638042/13155038/6bfd443a-d641-11e5-822d-8e6c2e3f037d.png)
![screenshot 2016-02-18 13 08 53](https://cloud.githubusercontent.com/assets/1638042/13155037/6bfcf340-d641-11e5-839d-151c67cee826.png)

**Comment by jmcmichael** [comment]
Oh, I see - the number input for the Suggested Revisions isn't getting set after refresh. It should be - I'll see what's going on...

**Comment by obigriffith** [comment]
The url doesn't change after refresh but the choices made for search conditions do not seem to be preserved? 
https://civic.genome.wustl.edu/#/search/043c1e56-8d94-4164-b43d-a85cf2d37196

**Comment by obigriffith** [comment]
Also, the status choice is defaulting from Accepted back to Submitted.

**Comment by jmcmichael** [comment]
I tried a couple of other fields, and they seem to be working fine (pubmed ID refreshes as expected). Something's up w/ Suggested Revisions.

**Comment by obigriffith** [comment]
Evidence Type also switches back to Predictive if you select anything else and then refresh. Seems like it is going back to default selections for any search types that have them?

**Comment by jmcmichael** [comment]
Yeah, this is an issue with how default values are set. The defaults are always overriding what returns from the server. I'm working on a fix.
