### ISSUE TITLE
Help Evidence Type Reordering

### ISSUE THREAD

**Issue by rlesurf** [genome/civic-client#352]
In the Help Section, under Evidence -> Evidence Type, I'd recommend reordering the sections to Diagnostic, Predictive, then Prognostic. It is more logical to have Diagnostic come before Predictive

**Comment by obigriffith** [comment]
I agree that you propose a logical ordering that is based on the timeline of clinical events so-to-speak. The current ordering reflects feedback from clinicians in terms of actionability. The first thing they want to know is whether any genomic event might help choose a therapy (predictive). In some cases, a genomic event may strongly indicate a specific subtype of cancer that helps guide therapy choices (that was somehow missed by traditional diagnostic methods). Last but least, it may be clinically informative to have a genomic marker that predicts better or worse outcome. But, we get consistent feedback that this is the least "clinically actionable" of the three types. So, that's where the current ordering came from.

**Comment by jmcmichael** [comment]
Interpreting this to mean we should keep the order as it is.
