### ISSUE TITLE
Assembly version hg20

### ISSUE THREAD

**Issue by rlesurf** [genome/civic-client#354]
When entering the genomic coordinates for GRCh38, it currently says "GRCh38 (hg20)", but I believe it should say "GRCh38 (hg38)". There was a jump that happened in naming conventions from GRCh37/hg19 to GRCh38/hg38 to make things simpler.

**Comment by malachig** [comment]
Yup, good catch:
hg38 = Dec. 2013 = Genome Reference Consortium GRCh38

**Comment by jmcmichael** [comment]
Updated this on a couple of forms.
