### ISSUE TITLE
MyGene.info Coordinate Assembly Version

### ISSUE THREAD

**Issue by rlesurf** [genome/civic-client#355]
When the genomic coordinates are shown for a gene (in the MyGene.info panel), it might make sense to also show the assembly version. Especially if this differs from the assembly version shown for the variant. 

Going forward, it might also make sense to show both hg19 and hg38 for all coordinates, or simply stick to only using hg38. This seems to be the standard now on many websites.

**Comment by acoffman** [comment]
We actually had hg20 displayed previously, and were asked by @malachig [here](https://github.com/genome/civic-client/issues/270#issuecomment-161457730) to switch to hg19 as most of our variant coordinates are hg19.

We could display both sets, labeled appropriately, if you think that might be helpful?

**Comment by rlesurf** [comment]
I'll defer to Malachi's opinion on this, but I still think it would be helpful to then say GRCh37 somewhere inside the MyGene.info panel so that the user knows what the coordinates refer to.

**Comment by malachig** [comment]
If it is easy to add build version to the MyGene.info panel, then yes we should do that.  All of this is temporary, the long term plan is to have support for multiple versions and perhaps the ability to toggle between builds dynamically.  

For now, to simplify the current version of the site we should try to stick to build37 as a convention when entering coordinates.  And make better support for multiple coordinates a priority soon...

**Comment by jmcmichael** [comment]
I added '(GRCh37)' underneath the coordinates line in the MyGeneInfo box.
