### ISSUE TITLE
Add Predisposing as an evidence type

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#365]
Starting this issue to continue and document the discussion about adding this evidence type. 

Evidence type: Predisposing
Clinical significance: Positive, Negative (Excluding N/A)

Currently we have Diagnostic evidence items that should be considered to be moved here:
- Germline Mutation (N=4)
- Germline Polymorphism (N=2)

Pros:
- We already have things that fit here
- Encourages engagement of groups we may not otherwise reach

Cons: 
- Further encourages entry of items we don't consider high priority
- Dilution of the things we want to highlight/further curation resources used for lower priority items
- Increases our appearance as competition of other resources

**Comment by malachig** [comment]
I think we should revisit this idea in our next group meeting but generally I think we should move forward with it. This may be a "v2" target though...

**Comment by obigriffith** [comment]
+1 We should do this.

**Comment by kkrysiak** [comment]
EID1111 has been discussed as a potential candidate.

**Comment by jmcmichael** [comment]
I've added this option to Evidence Types. For the description that appears beneath the Evidence Type select, the following appears for Predisposing:

"Evidence pertains to a variant's impact on a patient's likelihood to contract a disease"

When Predisposing is select for Evidence Type, then the Evidence Direction select options are set to Supports/Does Not Support, with the corresponding description text:

'Supports': 'The experiment or study supports a variant\'s likelihood to contract a disease',
'Does Not Support': 'The experiment or study does not support a variant\'s likelihood to contract a disease'

These are easily updated, let me know if you'd like modifications to them.

**Comment by malachig** [comment]
I find the wording of the help text a bit awkward.  How about:

'Supports': 'The experiment or study supports a variant\'s role in conferring susceptibility to a disease',
'Does Not Support': 'The experiment or study does not support a variant\'s role in conferring susceptibility to a disease'

**Comment by jmcmichael** [comment]
Updated.
