### ISSUE TITLE
Add live filter for EID to evidence data grid

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#366]
Currently on the evidence data grid we can filter on everything except EID.  When curating a variant with many evidence items it can sometimes be hard to find the one you are looking for in the list.  EID filter box would help with this if there is space to add it.

![screen shot 2016-03-10 at 11 34 28 am](https://cloud.githubusercontent.com/assets/856728/13678411/14c2d8fa-e6b4-11e5-8730-23e54f3d94c5.png)

**Comment by kkrysiak** [comment]
Until this feature added, I'd suggest using the EID sort capability to speed up finding your EID of choice.
