### ISSUE TITLE
Retrieving gene information through gene name from API 

### ISSUE THREAD

**Issue by jas1994** [genome/civic-client#367]
I need to use CIVIC database through api.There seems no provision to retrieve gene information through gene name.We can access gene info. through your local id which we dont know beforehand.Is it expected to first use (https://civic.genome.wustl.edu/api/genes) which returns all gene ids and name and use it to find required gene id through gene name and use this gene id to query database or there is some alternate to it? Can i directly retrieve using name say FRS2	 etc.

**Comment by acoffman** [comment]
Hi @jas1994,

With the current version of the API the idea is that you would use the `/api/genes` endpoint to retrieve our internal gene ids and then use those to query for variants and evidence items. Querying by Ensembl gene ids and symbols is a commonly requested feature though, so I'm going to go ahead and add that ability. I will update this ticket with details when the changes are live!

Thanks!
Adam

**Comment by acoffman** [comment]
Hi @jas1994 

I wanted to let you know that we've implemented a change that should help you out! Now you can pick an `identifier_type` when using the `genes` api endpoint.

The default behavior will be to continue to utilize our internal gene ids. However, the following queries will now work:

`GET /api/genes/BRAF?identifier_type=entrez_symbol`
`GET /api/genes/238?identifier_type=entrez_id`

This change should make it out to production this evening, so feel free to give it a try tomorrow! 

Thanks for your interest in CIViC!

Adam

**Comment by jas1994** [comment]
Thanks for this @acoffman .It takes lot of time to search through large JSON object and match name to id.Its quite simple now.Thanks!
