### ISSUE TITLE
Support clinical trial ID (clinicaltrials.gov) rather than just pubmed source

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#37]
For example: NCT02279654

Will require different information than Pubmed ID (author, date, journal) to be displayed for evidence item entries. I'm not sure what data at this moment or what the options would be from their API.

**Comment by malachig** [comment]
One approach would be to have a required field 'source' and require that this be either a PubMed ID or a Clinical Trials ID.  This would require two sets of methods to generate a human readable name for the source as each would have to hit different APIs to get basic information.  We would also need different methods to ensure the validity of these two ID types.

**Comment by jmcmichael** [comment]
At this time we're only going support pubmed ids. If in the future we decide to support the ClinicalTrials DB, an enhancement issue should be opened on civic-server as this is primarily a server/schema issue. Closing.
