### ISSUE TITLE
Indenting of user drop down seems non intuitive

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#380]
I took me a while to understand the sections in the user drop down menu.  To me the indenting seems backwards.  e.g. `notifications` is indented and less prominent looking than the to following items, which are types of notifications: `mentions` and `subscribed events`.

Would it make sense to have `notifications`, `account`, and `adminstrator tools` left justified, and the options under of each of these headings be smaller and/or indented?

**Comment by jmcmichael** [comment]
Yeah these are the default Bootstrap styles, which I am not happy with either. I'll implement something similar to what you described.
