### ISSUE TITLE
Notification location could be more intuitive

### ISSUE THREAD

**Issue by zlskidmore** [genome/civic-client#382]
If you have marked all you're notifications as seen the only way to get to the notifications page is from the dropdown menu on you're name -> My Account

Intuitively I think as my account as the page when you click on you're name maybe this could be made more intuitive such as renaming My account to notifications or merging the two?

**Comment by malachig** [comment]
I am okay with the two pages, but I think we should just make it a bit more clear.  

I also think that while its nice that clicking on your user name takes you to your profile page, we should also include a link to this in the dropdown to help make it clear that there is an `my account` page and a `my profile` page.  With a bit more reorganization of this drop down I think we can make it all more intuitive.
