### ISSUE TITLE
write 'description' copy for About page domain experts list

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-client#392]
I've added a list of domain experts to the About page, accompanied with profile details and a short description intended to list the expert's qualifications, background, CIViC contributions, etc. 

We'll need a write up for each expert to replace the filler text that the profiles currently display:

![screen shot 2016-04-12 at 13 52 22 pm](https://cloud.githubusercontent.com/assets/132909/14471796/d5e13a0c-00b5-11e6-87ef-f0e376d170d3.png)
.

**Comment by obigriffith** [comment]
Josh. Not sure if this is a complete list but I believe the initial set of users was also to include nspies and obigriffith.

**Comment by jmcmichael** [comment]
Yeah you and nick are in the list but I didn't the whole list in the screenshot - just wanted to show about how much room each has for the description text. Also I used the order in the email I have on the subject,  but that's easy to change.

**Comment by obigriffith** [comment]
OK. we're working on write-ups
