### ISSUE TITLE
Link into CIVIC by HUGO gene ID

### ISSUE THREAD

**Issue by holtgrewe** [genome/civic-client#395]
Is it possible to link into CIVIC using the HUGO gene ID and optionally a protein-level variant? I have not found any way to do so and the data I can download does not include the CIVIC gene IDs (CIVIC gene 25 is not ABL1, for example).

**Comment by acoffman** [comment]
It is possible to query the API via Entrez gene id or symbol like so:

````
https://civic.genome.wustl.edu/api/genes/ALK?identifier_type=entrez_symbol

https://civic.genome.wustl.edu/api/genes/128?identifier_type=entrez_id
````

But at the current time it isn't possible to link to the frontend in that manner (or via HUGO ids or protein level variants). Its a feature we might consider adding in the future however!

If you are interested in using the data downloads to construct links to CIViC, we can definitely include our internal CIViC ids in the TSV files - that is a pretty minor change! I will go ahead and make the change and let you know when its live on the site.

**Comment by holtgrewe** [comment]
Yes, please! :)

**Comment by obigriffith** [comment]
I can't find the issue. But, I thought this was an existing issue to add internal IDs and other missing data to the data dumps as part of being compliant with UCSC submissions. Did that not get resolved already and maybe just not yet pushed live?

**Comment by acoffman** [comment]
@obigriffith You're right, it was sitting in a branch waiting to be merged in and pushed! 

Its out as of today's deploy and I went ahead and manually triggered a build of the nightly TSV dumps. So as of today, the nightly dumps will include all the fields that @LeiChen0218 specified: including our internal CIViC ids and links to all entities on the site!

I will also re-ran the monthly dump for April so it will include the same information.

**Comment by acoffman** [comment]
@holtgrewe Since this solves the immediate linking problem, I'm going to go ahead and close this issue, but I've opened #396 to track the more general problem of supporting links into CIViC via alternate identifiers.
