### ISSUE TITLE
CIVIC logo license

### ISSUE THREAD

**Issue by holtgrewe** [genome/civic-client#398]
What is the license of the CIVIC logo. I'm working on integrating CIVIC data into cBioPortal and would like to use the favicon for representing a CIVIC link-out in the result display. Is this covered by the MIT license and/or fair use?

**Comment by jmcmichael** [comment]
Good question. Initially covering the logos under the Creative Commons license that applies to the data seemed reasonable, but we don't want the logo to be modified or re-used, either for commercial or non-commercial reasons. So now I'm thinking that we should probably cover the logos under a more restrictive license - we'll discuss at the next CIViC meeting. In the meantime, feel free to use the favicon around links or material that refers directly to CIViC.

**Comment by holtgrewe** [comment]
Thanks.

Here is my humble attempt at linking between cBioPortal and CIVIC: https://github.com/cBioPortal/cbioportal/pull/1077

**Comment by jmcmichael** [comment]
Perfect, that looks great! Thanks for integrating CIViC data into your application.
