### ISSUE TITLE
Improve variant group suggested revisions to display variants being added, not just IDs

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#405]
It would be much easier as a moderator to see the names of the variants being added to the variant group, rather than the IDs. Currently this is what is shown:

![screen shot 2016-05-03 at 10 04 10 am](https://cloud.githubusercontent.com/assets/8527125/14987798/997b6378-1116-11e6-909d-d4f6a73109e3.png)

**Comment by kkrysiak** [comment]
I'd like to bump this issue again.

**Comment by jmcmichael** [comment]
The server generates these revisions, I've created [another issue](http://github.com/genome/civic-server/issues/238) over there for it.

**Comment by acoffman** [comment]
Fixed! Will go out in the next deploy!
