### ISSUE TITLE
add CSV download option to evidence grid

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-client#406]
Especially with the advanced search results this would be very useful to many users.

**Comment by malachig** [comment]
+1 this will be very handy to grab the results from complex queries.

**Comment by jmcmichael** [comment]
Done. Looks like this:

![screen shot 2016-05-05 at 10 41 53 am](https://cloud.githubusercontent.com/assets/132909/15048224/38713eec-12ae-11e6-93e7-01a4d7c1a39c.png)

Working on a PDF export option as well.
