### ISSUE TITLE
Cannot add evidence item directly after submitting one

### ISSUE THREAD

**Issue by zlskidmore** [genome/civic-client#408]
After submitting an evidence item you are taken to the page saying "Thank you. The evidence item has been ....".

On this page the ADD button is greyed out, is this by design?

Minor issue but I would prefer being able to just add again without returning to the home page, especially in cases where a submitted paper discusses multiple genes/events.

**Comment by jmcmichael** [comment]
Yeah, good point - I'll add an 'Add another' button to the report submitted notice.
