### ISSUE TITLE
Suggested evidence item edits do not update on front end when commit is requested by admin

### ISSUE THREAD

**Issue by bainscou** [genome/civic-client#41]
When you edit an evidence item and submit it to the queue the admin has the option to commit the change. When the commit button is pressed the change gets updated in the back end but the view does not get updated on the front end

**Comment by jmcmichael** [comment]
Yeah there's a couple ways to pass functions around in nested components and I chose one that's simple at first but gets more problematic the more nested levels there are. The function call to update the parent entity(s) is getting dropped somewhere in the chain. So I'm diving into another component refactor to switch the method I'm using for sharing functions between components - this should also have the effect of reducing the number of components and the general complexity of the events states.
