### ISSUE TITLE
Force correct 'Clinical Significance' values based on 'Evidence Type' selection when adding evidence

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#42]
When adding or editing evidence statements we want to enforce a relationship between each 'Evidence Type' and certain 'Clinical Significance' values

| 'Evidence Type' | 'Clinical Significance' values allowed           |
| --------------------- | --------------------------------------------------------- |
| Predictive          | 'Sensitivity', 'Resistance or Non-Response'  |
| Prognostic         | 'Better Outcome', 'Poor Outcome'                 |
| Diagnostic         | 'Positive', 'Negative'                                      |

**Comment by malachig** [comment]
This issue is related to #34

**Comment by acoffman** [comment]
Additional state:

Only display drug name (pubchem id) when Predictive is selected for the Evidence Type.

**Comment by jmcmichael** [comment]
This issue is superseded by #70, as the specification spreadsheet includes this requirement.
