### ISSUE TITLE
Browse page "Browse by Variant" is having a paging problem

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#431]
Clicking page 21 or "last" causes an error, returning "no records found". 504 records should produce just over 20 pages (25/page) but not that many entries are displayed. Page 20 is incomplete. I'm assuming this has to do with hidden/removed variants.

<img width="1215" alt="screen shot 2016-06-02 at 4 10 34 pm" src="https://cloud.githubusercontent.com/assets/8527125/15761389/7d4da3b2-28dd-11e6-8fdd-6d9bb4f4356a.png">

**Comment by jmcmichael** [comment]
Yeah, it looks like the item totals includes additional records that aren't returned in the actual request. @acoffman, could you check this out when you get a chance? BTW, it would be cool to add the _meta data attribute to these datatables endpoints.

**Comment by jmcmichael** [comment]
Closing, this looks like a server issue.

**Comment by acoffman** [comment]
Fixed in master server side.
