### ISSUE TITLE
notifications should indicate if they refer to an unlinkable entity

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-client#432]
For example, creating a comment will generate a notification, but if the user then deletes the comment it becomes impossible to link to directly. Requires a server update, will create an issue for a 'deleted' flag on notifications.

**Comment by kkrysiak** [comment]
This doesn't appear to be working. Amber deleted a comment on EID1445 but there is no indication on my notifications page.
<img width="1200" alt="screen shot 2016-09-01 at 1 44 12 pm" src="https://cloud.githubusercontent.com/assets/8527125/18180107/0725337a-704b-11e6-9376-1fcfcea19156.png">

**Comment by jmcmichael** [comment]
I believe the entities that affect the 'linkability' of a notification are the primary entities - genes, variants, evidence, etc. and not comments. So deleting the comment won't toggle the notification to unlinkable, but deleting the actual entity to which the comment is attached will.

@acoffman is this the case?

**Comment by acoffman** [comment]
Yeah, looks like there's a hole in the logic there. I'll get it fixed!

**Comment by jmcmichael** [comment]
Added a server issue, closing.

**Comment by kkrysiak** [comment]
Awesome. Thanks guys!
