### ISSUE TITLE
add dropdowns for Role and Area of Expertise in Community search UI

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-client#444]
To complete genome/civic-server#198

**Comment by acoffman** [comment]
For reference, server side supports:

 * Param name: `area_of_expertise`
   * Valid values: `Patient Advocate`, `Clinical Scientist`, `Research Scientist`

 * Param name: `role`
   * Valid values: `moderators`, `editors`, `admins`

Either or both can be specified in the `filter` section just like `display_name`
