### ISSUE TITLE
Must reload (refresh) page after accepting new evidence record

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#449]
I think this might have been fixed in the past but has re-emerged.  Right now when I click accept an evidence record, the page appears to load (bar at top moves across), but the buttons do not disappear and the page does not update until I manually refresh.

**Comment by yanyangfeng** [comment]
I can't seem to reproduce this on my dev instance - is this problem still occurring?

**Comment by malachig** [comment]
Confirmed. Both dev instances and the live site appear to be working nicely now with respect to this issue.  Resolving.
