### ISSUE TITLE
add additional help text to Variant Type fields, as well as more extensive Help docs

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-client#459]

**Comment by kkrysiak** [comment]
The more extensive docs have been added in a whole new tab by Amber this summer. Current help text in the edit Variant form is: " Add one or more variant types from the Sequence Ontology ". Not sure what else to add there.

**Comment by kkrysiak** [comment]
Added a link to SO and some examples.

**Comment by malachig** [comment]
Included in https://github.com/genome/civic-client/pull/618
