### ISSUE TITLE
Gene search goes to wrong location

### ISSUE THREAD

**Issue by chrisamiller** [genome/civic-client#472]
If I go to CIVIC's search box and type in "POLE", then hit enter, I'm taken to this page:
https://civic.genome.wustl.edu/#/events/genes/2596/summary/variants/433/summary

After typing POL, the first autocomplete entry is for this gene (HIF1A), but I think some sort of "no annotations for gene POLE" page would be more appropriate.

**Comment by acoffman** [comment]
Just so I make sure I understand, it didn't take you to the "wrong" location per se, it took you to the location it said it would, that location just wasn't where you thought it should go?

That search box doesn't just search genes, it searches diseases (try `acute`), variant names (`v600`), drugs (`sunitinib`) and gene aliases (`pkaca`). I'm not sure how to retain that behavior while also trying to intuit what a user intended to type. Do we assume they always meant a gene symbol and go to that if their entry matches an existing one? As best as I can tell, typing `POLE` and hitting enter doesn't go anywhere, but typing `POL` and hitting enter takes you to a match for `polymorphism`. Would it make more sense for it to assume you meant the gene `POLE`?

**Comment by chrisamiller** [comment]
Okay, if you get to the end of typing "POLE", there are no longer any autocomplete entries, and hitting 'enter' does nothing. But, if you hit the "Go!" button, it does take you to the page I linked.

I guess my expectation would be that it either a) go nowhere (which seems confusing - could lead people to think the search is broken) or b)  go to some sort of "nothing found for that term" type page. The current state seems bad - going to an page that no longer matches the search box input.

**Comment by acoffman** [comment]
Gotcha, that does make sense - I hadn't noticed the behavior when clicking "go." I agree that if there are no matches it shouldn't just take you to the last thing that happened to match. We'll get that fixed!

**Comment by jmcmichael** [comment]
This has been fixed - if a search term doesn't result in anything returned from the db, the dropdown disappears. Hitting enter at that point does nothing, and given that there's no dropdown item highlighted at that time, won't be confusing or appear broken.

**Comment by chrisamiller** [comment]
I'm going to ask to reopen this, as there's still some unexpected behavior. To reproduce:

1) Go to https://civic.genome.wustl.edu/#/home
2) Click in the search box and type in "KREMEN2"
3) Click "GO"

It takes me to this page for KRAS:
https://civic.genome.wustl.edu/#/events/genes/30/summary/variants/76/summary
