### ISSUE TITLE
Advanced search of evidence using a pubmed id only find accepted evidence

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#474]
We have an evidence statement for pubmed ID 27276561.  It is currently awaiting approval.  If I search in the advanced search I get no evidence records matching.

This search would ideally match evidence records with that source regardless of status.  That way I can see if someone just entered evidence from the same new publication.  Or if someone has already attempted to do so, and it was rejected that might save me making the same mistakes...

**Comment by acoffman** [comment]
As far as I know, it shouldn't be filtering out a particular status unless the user selects one.

I attempted to search for that pubmed id and it seems to have shown up for me: https://civic.genome.wustl.edu/#/search/evidence/952a887c-7bfc-4ce0-8e31-3afdf3a32920

Can you link me to the search where you're not seeing it?

**Comment by malachig** [comment]
https://civic.genome.wustl.edu/#/search/evidence/d9a851f2-c87d-4857-9cd0-a8b9737e1e37

**Comment by malachig** [comment]
Oh sorry.  User error!  Have evidence ID selected instead of PubMed ID.  Closing.
