### ISSUE TITLE
create a curation view

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-client#479]
- reports
  - # items awaiting approval
  - # old items
- item with lots of recent comments
- drugs w/ similar names
- evidence items w/ same pubmed id
- incomplete items (variants w/ empty coords, empty summaries)

**Comment by jmcmichael** [comment]
- new drug names
- new diseases
- new variants

**Comment by kkrysiak** [comment]
Alert of possible EID repeats? Currently this is performed in the add evidence page but prior to that we had no such mechanism. Even with that warning, this may still happen.

**Comment by kkrysiak** [comment]
- Diseases without DOIDs

**Comment by kkrysiak** [comment]
We should discuss whether we want to include some of the admin interface merge tools/utilities (Drugs, Variants). Also the ability to move EIDs between variants which is currently restricted to the admin interface.
