### ISSUE TITLE
Reorder the Add Evidence Statment form items

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#49]
The Add Evidence Statement form doesn't have a very logical flow at the moment from the standpoint of a curator (in my opinion).

I think a better flow would go as follows:
-Entrez Gene ID    *(Gene-based data)*
-Variant Name       *(Variant-based data)*
-Variant Origin
-Disease Ontology ID   *(Disease)*
-Evidence Summary     *(Evidence info)*
-PubMed ID
-Evidence Level            *(Evidence Descriptors)*
-Evidence Type
-Evidence Direction
-Clinical Significance
-Evidence Rating

**Comment by malachig** [comment]
I like this.  One thought.  To emphasize that the evidence statement is at the heart of each entry, maybe that should come first.  The rest of these fields are basically qualifications/annotations of that statement...  Just a thought.
