### ISSUE TITLE
change content license to CC0

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#493]
Please feel free debate this further here but assuming there are no objections, we would like to update the content license to Creative Commons CC0.  Anywhere the license is mentioned in this site should be updated.  

Here is the official info on this license:
https://creativecommons.org/publicdomain/zero/1.0/

And full license text:
https://creativecommons.org/publicdomain/zero/1.0/legalcode

**Comment by jmcmichael** [comment]
What's the reasoning for moving from CC 4.0 Attribution to public domain?

**Comment by malachig** [comment]
An interesting related discussion on the opendata stack exchange:
http://opendata.stackexchange.com/questions/26/benefits-of-using-cc0-over-cc-by-for-data

And a comment on the paper from co-author Ben Good: 
“I encourage you to go all the way to CC0.  My wikidata experience has convinced me that it's the way to go.  The CC Attribution is unenforceable and only slows down the good guys who would be citing you anyway when building aggregated data stores. "

**Comment by jmcmichael** [comment]
Ah, ok - so just the data and not the branding, graphics etc? That sounds fine to me.

**Comment by obigriffith** [comment]
Just to confirm. I think it is fine for branding/graphics to remain under current licenses or as you prefer. CC0 would apply to all the data/content currently under CC-BY.

**Comment by obigriffith** [comment]
Another suggestion from Ben Good. See also this ongoing thread among the OBO community
https://github.com/OBOFoundry/OBOFoundry.github.io/issues/285#issuecomment-236881241

**Comment by malachig** [comment]
Hi @jmcmichael I created this pull request to submit these changes:

https://github.com/genome/civic-client/pull/495

**Comment by jmcmichael** [comment]
Merged the pull request implementing this update to the license.
