### ISSUE TITLE
add privacy note to email form fields

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-client#499]

**Comment by malachig** [comment]
Reassure people about adding their email.  Add something like this:

Email address will not be visible to others, will not be shared, or used for any other purpose.

**Comment by kkrysiak** [comment]
Modified to "Email address will not be visible to others or shared. Email addresses will only be used for sending CIViC notifications, news, and updates." But @malachig, should we say something about it being used for Oauth services. I guess once it is linked it is safe to be deleted?

**Comment by malachig** [comment]
I think this is sufficient.

The email address itself is not used directly for Oauth, it might be used to authenticate on login by the organization providing the Oauth service (e.g. Google), but CIViC doesn't need to store the email address for Oauth to work.

**Comment by kkrysiak** [comment]
So when I changed this text in ~/civic-client/src/app/views/users/profile/edit/profileEdit.js, nothing happened in the edit profile text. However, when I changed it in ~/civic-client/src/app/views/account/profile/ProfileController.js, it worked.

**Comment by malachig** [comment]
Included as part of https://github.com/genome/civic-client/pull/618
