### ISSUE TITLE
should ratings be calculated in aggregate or as a discrete value per record?

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#50]
Currently, we only accept the original curator's trust rating.

It would be great if this could happen without having to click on "edit evidence statement" but still be tracked in the activity of an evidence statement. Otherwise you have to submit a comment about your evidence statement change which may deter users that just want to vote.

**Comment by jmcmichael** [comment]
Yeah this would be cool, and we've discussed implementing ratings as a calculated field based on aggregate votes. But I recall we decided to table that implementation at that time, as there are quite a few details to nail down first regarding exactly how we implement this on the frontend, and what method we use to calculate displayed ratings on the backend.

For example on the frontend, we could go with Amazon and Apple's model with ratings in their stores. They require users to enter a comment when voting. I believe this raises the bar a bit so you don't get people making frivolous or knee-jerk ratings. Or we could just allow people to click on the star control to register a vote.

Also the way we display it can be important. Do we show the rating *and* how many people have voted (like Amazon)? or just the average rating?

This Quora post contains a lot of excellent points and questions about implementing star ratings systems:

http://www.quora.com/Is-there-a-better-alternative-to-the-5-star-rating-system

Here is an excellent post on various heuristics for calculating ratings, both multi-star and thumbs up/down type systems:

http://www.evanmiller.org/how-not-to-sort-by-average-rating.html

Until we get these details specified I think we should treat the rating like the other fields.

**Comment by jmcmichael** [comment]
Also of interest - Youtube dropped their 5-star ratings b/c they discovered almost everyone submitted either one or five star ratings. So they adopted the thumbs up/down interface:

http://youtube-global.blogspot.com/2009/09/five-stars-dominate-ratings.html

Of course our users will probably be different than Youtube's, but it is something to consider.

**Comment by kkrysiak** [comment]
All good points. This will definitely warrant further group discussion. Not a high priority at all, but when I was looking at the website last night it reminded me of the early discussions. Once things calm down it's probably worth another discussion.

**Comment by malachig** [comment]
I kind of like the Google system.  You provide a star rating and you can provide a comment/review as well but it is optional.  Then for the view you get a numerical average, as well as the graphical star representation.  Like this:
![screen shot 2015-02-27 at 2 37 30 pm](https://cloud.githubusercontent.com/assets/856728/6419808/801c4162-be8e-11e4-8c8e-0eab474fd059.png)

**Comment by jmcmichael** [comment]
More reading material - ratings and the UI for making/understanding them are a somewhat complex and contentious topic among user experience developers:

Why Rating Systems Don't Work
Author explains his position (anti star ratings, anti histograms), presents a scatterplot method:
http://goodfil.ms/blog/posts/2012/08/22/why-ratings-systems-dont-work/
interesting hacker news discussion: https://news.ycombinator.com/item?id=4416864

How Do I Sort an Ordinal List of User Generated Ratings Data?
Questioner asks how to sort ordinal ratings and get a variety of in-depth answers:
http://stats.stackexchange.com/questions/19115/how-do-i-sort-an-ordinal-list-of-user-generated-ratings-data

**Comment by obigriffith** [comment]
The scatterplot method is nice although I think for most people this will require more effort to interpret than a five-star system that everybody is already familiar with. Also not clear what our two axes would be. I agree with the ycombinator poster who disputes the quality of the goodfil blog post. I found the histograms DID add useful information to distinguishing between the three movies. They don't make a very strong case against five-star systems in my opinion.

**Comment by jmcmichael** [comment]
At this time we're not calculating ratings in aggregate and probably won't for awhile. I'm going to go ahead and close this, maybe reopen when we're ready to implement aggregate ratings calculations.
