### ISSUE TITLE
Meetings page updates

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-client#517]
- move date/time/location to top of page
- include link to civic-meetings repo

**Comment by obigriffith** [comment]
Can we also add the following content to meetings page somewhere? At bottom?

"This year the Semantic Web Applications and Tools for Life Sciences (SWAT4LS) Conference (http://www.swat4ls.org) and Clinical Interpretation of Variants in Cancer (CIViC) Curation Jamboree and Hackathon (https://civic.genome.wustl.edu/#/meetings) are both at the NKI in Amsterdam, only separated by the weekend.  This brings the opportunity for potential synergy, where content from CIViC is curated and presented in a Semantic Web-ready format, which is then integrated with other resources on the Semantic Web at SWAT4LS.

Attendance at both events would certainly benefit from such a cross-pollination. To enable this, we cordially invite attendees of SWAT4LS to join the CIViC Jamboree and Hackaton and vice versa. Joining the CIViC Jamboree/Hackaton is free of charge (please register at http://ngs2016.org). Attendees for the CIViC Jamboree get a 20% discount when registering for SWAT4LS events (discount codes will be distributed at the CIViC Jamboree and Hackathon). 
"
