### ISSUE TITLE
add example searches to the advanced search views

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-client#528]
It would be relatively easy to have a list of common searches for each of the entities. This would give users a sense of what searches are possible, and how to accomplish them. Some searches, (e.g. variant coordinate searching) have been assumed by reviewers not to not exist when it's actually possible to accomplish using existing search parameters. Implementing example searches would mitigate these kinds of issues.

**Comment by kkrysiak** [comment]
Nice example used in the paper.
*Evidence search:*
Gene name contains ALK
Evidence type is Predictive
Drug Name contains Alectinib
*Source search*
Journal Name contains New England
*Variant search*
CHR1 Chromosome is 2
CHR1 Start is in the range 16000000 to 60000000
*Gene search*
Description contains leukemia
