### ISSUE TITLE
comment form should reset its contents after a comment is succesfully submitted

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-client#53]
Is this the desired behaviour. I was submitting a comment on the Gene Talk page. When I hit 'Submit Comment' I got a 'Your comment was added message' and I see my new comment above. But, it also still shows the form with my title and comment filled in and the button to 'Submit Comment' still there. Should these fields be reset as another clue to the user that there comment was submitted. I could see some users not noticing the message and accidentally resubmitting the same comment again. Thoughts?

**Comment by jmcmichael** [comment]
Nope, those fields should be reset. Will fix that one.

**Comment by jmcmichael** [comment]
Done, closing.
