### ISSUE TITLE
Accepted then Rejected Variant Revisions Still Displayed 

### ISSUE THREAD

**Issue by KujanL** [genome/civic-client#558]
![screen shot 2016-10-21 at 5 49 20 pm](https://cloud.githubusercontent.com/assets/15361912/19614060/c5d48978-97b6-11e6-9bab-68d197d8c49c.png)

Here, RID2847 was accepted and then rejected later on. However, the variant information is still displayed in CIViC (EX: COX2 Overexpression  RID2847)

**Comment by jmcmichael** [comment]
Hi @KujanL, do you recall how RID2847 was accepted then rejected? The UI should hide the accept/reject buttons on any suggested change that doesn't have a 'new' status, so this kind of thing shouldn't be possible to do by clicking a UI button.

**Comment by kkrysiak** [comment]
This may have been me in the admin interface. I don't recall exactly though.

**Comment by jmcmichael** [comment]
Closing, Adam will fix this on the server, as it's only possible to perform this sequence via the admin interface - the client won't display the UI buttons necessary to do this on the client.
