### ISSUE TITLE
For users without first/last name in github. The login bar shows this. 

### ISSUE THREAD

**Issue by nspies13** [genome/civic-client#56]
![messages image 979909647](https://cloud.githubusercontent.com/assets/4623661/6402297/2fe96048-bdcc-11e4-822a-6e921e494626.png)

**Comment by nspies13** [comment]
Can we display username instead?

**Comment by jmcmichael** [comment]
I don't have access to an account w/o a name for testing but this should work now, let me know if you see this behavior again.
