### ISSUE TITLE
Number of Subscribed Events does not match with the number of visually illustrated subscribed events 

### ISSUE THREAD

**Issue by KujanL** [genome/civic-client#560]
![screen shot 2016-10-24 at 2 40 53 pm](https://cloud.githubusercontent.com/assets/15361912/19661167/440d2050-99f8-11e6-849d-de22952a84c0.png)

As illustrated CIViC says I have 5 Subscribed Events, but there are only 3 visible events. I have reloaded the page several times, but the error is still evident.

**Comment by kkrysiak** [comment]
I think this is a repeat of #511
