### ISSUE TITLE
civic flavicon missing

### ISSUE THREAD

**Issue by zlskidmore** [genome/civic-client#561]
Just noticed that the civic flavicon is missing/does not display on my computer:

macbook pro 10.11.6, chrome  53.0.2785.143 (64-bit)

**Comment by jmcmichael** [comment]
Odd, I just noticed this in Chrome as well. It appears that uBlock Origin, an ad-blocker, is blocking the favicon.ico file for some reason. Are you using an ad-blocker?

**Comment by zlskidmore** [comment]
No, ad-blocker. I don't see anything in my extensions that should cause this issue
