### ISSUE TITLE
Add obvious view publication queue button on the suggest publication form

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#562]
The menu item isn't super obvious for users to find if they aren't used to using that menu. Having a backup would be helpful.

**Comment by jmcmichael** [comment]
Added links to the instructions and success messages:

![screen shot 2016-11-14 at 10 46 18 am](https://cloud.githubusercontent.com/assets/132909/20273684/debf7f7a-aa57-11e6-96fe-4e63c5046de5.png)
![screen shot 2016-11-14 at 10 46 38 am](https://cloud.githubusercontent.com/assets/132909/20273683/debdb9ec-aa57-11e6-85a4-8b49b6c27ee9.png)
