### ISSUE TITLE
Publication queue view unavailable to curators

### ISSUE THREAD

**Issue by zlskidmore** [genome/civic-client#563]
It appears that the publication queue link is missing in the curator view. I can access this page https://civic.genome.wustl.edu/#/curation/sources however the link to that page is missing from the the oauth drop down menu.

**Comment by zlskidmore** [comment]
<img width="238" alt="screen shot 2016-10-25 at 12 02 14 pm" src="https://cloud.githubusercontent.com/assets/6145692/19696164/aac47ad8-9aab-11e6-9459-5cc177061a29.png">

**Comment by kkrysiak** [comment]
Currently, this is available to Admins, unclear whether this view is available to Editors. 
<img width="240" alt="screen shot 2016-10-25 at 12 01 19 pm" src="https://cloud.githubusercontent.com/assets/8527125/19696224/e007b188-9aab-11e6-9a34-aa0eb8b81703.png">
