### ISSUE TITLE
add list of data users to About page under Partners or a new section

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-client#566]
Wikidata
Cartagenia/Agilent
SolveBio
DocM
OHSU?
Berlin Institute of Health?
CBioPortal
Omicia?
Guardant?
BioGPS
UCSC Cancer Genomics Browser

**Comment by kkrysiak** [comment]
I wonder if we should have DoCM and DGIdb at the bottom of the about page in a separate sort of category. Related Resources or something. I feel like these "sister resources" should have some sort of nod on the website. I guess I don't know where is most fitting.

**Comment by malachig** [comment]
I have created a first attempt at this and generally reworked the About page a bit. This will be part of the upcoming docs PR. For now I have just included the data partners that we know for sure are using CIViC data and where there was something we could link to.  As we discover more resources that integrate CIViC data we should be sure to update this public list.

**Comment by malachig** [comment]
Included as part of https://github.com/genome/civic-client/pull/618
