### ISSUE TITLE
Add reminder of CC0 to CIViC submission forms

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#577]
Maybe, we should add a brief reminder to all submission forms in the CIViC interface that by contributing to CIViC you are agreeing to add your contribution to a public commons as defined by the terms of the CC0.

e.g. in the add evidence, edit evidence, edit variant, edit gene, etc. forms....

**Comment by jmcmichael** [comment]
You don't believe the other notices cover us sufficiently? I really do not want to add any more complexity or noise to the forms, as they are plenty complex/noisy in their current form.

**Comment by malachig** [comment]
The existing notices are either very subtle (bottom of the page), or are passive. If you read about the aims of CIViC you will see how the existing content of CIViC is licensed.  But when you actually submit something, it would be nice to have a reminder.

How about just a modification or extension of this sentence that is already there in the Add Evidence form?:  

"Please ensure that your submission contains no Protected Health Information, and is your own original work."

Could be something like:
"Please ensure that your submission contains no [Protected Health Information](https://www.hipaa.com/hipaa-protected-health-information-what-does-phi-include/), is your own original work, and you agree to release into the public domain under a creative common license ([CC0](https://creativecommons.org/publicdomain/zero/1.0/)) ."

**Comment by malachig** [comment]
I have updated existing help text with a brief amendment about CC0 in the places where copyright is most critical (variant summary, gene summary, and add evidence).

**Comment by malachig** [comment]
Include in https://github.com/genome/civic-client/pull/618
