### ISSUE TITLE
replace non-TCGA adj allel freq with calculated exac adjusted allele count

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-client#581]
(from genome/civic-server#243)
Since we don't seem to be getting anything from exac non-TCGA adjusted allele frequency I think we should move that entry from the static box and into the MyVariant.Info pop up and replace it with the general adjusted allele frequency. This isn't provided directly by MyVariant.Info, it will need to be calculated from existing MyVariant.Info parameters.

This requires getting the exac adjusted allele count (exac.ac_adj) and the exac adjusted allele number (exac.an_adj). Then just calculate the frequency which is allele count divided by allele number (aka total number of alleles).

exac.ac_adj/exac.an_adj

Allele count and allele number could then be in the MyVariant.Info pop up.

Move non-TCGA adj allel freq to popup window.

**Comment by obigriffith** [comment]
I'm adding a high priority to this. Currently we are missing out on ExAc.
