### ISSUE TITLE
Predisposing needs an icon in the evidence grid

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#583]
![screen shot 2016-11-07 at 4 44 06 pm](https://cloud.githubusercontent.com/assets/8527125/20079270/857b903c-a509-11e6-9838-c2a3862a4ea8.png)

**Comment by malachig** [comment]
We are starting to get low on options maybe, but here are some possibilities:

![info](https://cloud.githubusercontent.com/assets/856728/20081124/268fbeea-a513-11e6-9b2f-e2255da4adf0.png)
![fire](https://cloud.githubusercontent.com/assets/856728/20081126/2abe20d8-a513-11e6-9f7b-9213a617a28f.png)
![bell](https://cloud.githubusercontent.com/assets/856728/20081129/2e2f514c-a513-11e6-886d-61b7500fe54a.png)

**Comment by kkrysiak** [comment]
Fire seems a bit harsh and the info sign seems too much like a help text icon. Rather than the info sign I'd say the alert below. The bell option above is also pretty good.
![screen shot 2016-11-07 at 6 04 01 pm](https://cloud.githubusercontent.com/assets/8527125/20081353/bf7f7842-a514-11e6-925e-e35507fcaa4a.png)
![screen shot 2016-11-07 at 6 05 45 pm](https://cloud.githubusercontent.com/assets/8527125/20081377/d68923da-a514-11e6-8b28-655ddb867076.png)

**Comment by kkrysiak** [comment]
Fire is also out because it is the adverse response sign.

**Comment by malachig** [comment]
Yeah I really like the `alert` one.  Was looking for that but did not see it.  If we are not already using that one, I think that might be best.
