### ISSUE TITLE
Display issue for MyVariant.Info box

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#590]
![screen shot 2016-11-23 at 1 44 24 pm](https://cloud.githubusercontent.com/assets/8527125/20576324/27f090da-b183-11e6-87b0-7789926a516d.png)

**Comment by malachig** [comment]
I see this one as well.  Also the `View MyVariantInfo Details` button is not responding

**Comment by malachig** [comment]
For reference.  Here is the reported example from KK's screenshot:
https://civic.genome.wustl.edu/#/events/genes/45/summary/variants/117/summary#variant

This appears to be fixed now?

**Comment by kkrysiak** [comment]
Yeah, looks fixed.

**Comment by acoffman** [comment]
Yup, this fix is live!
