### ISSUE TITLE
client doesn't finish loading in dev environment

### ISSUE THREAD

**Issue by ahwagner** [genome/civic-client#591]
See http://54.202.232.211:3001/ for example.

**Comment by jmcmichael** [comment]
I reverted a work-around that I implemented to avoid ad-blockers causing problems when they block the google analytics plugin, please try pulling the latest updates and checking that out. 

This latest master appears to work fine on our local dev environments in dev mode, and on the live server as a build package.

**Comment by ahwagner** [comment]
it works!
