### ISSUE TITLE
open port 35729 on AMI for dev server's live-reload feature

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-client#593]
The dev server has a feature that watches for changes to code, styles, and templates then causes connected browsers to refresh itself when those files are updated. This feature operates over a websocket connection to port 35729. Blocking this port won't cause issues (other than connection timeout complaints in the browser console), but livereload can save some time, and its a nice feature for devs to have.

**Comment by ahwagner** [comment]
added to AMI security group.
