### ISSUE TITLE
Demote/promote some fields, link to dbsnp, truncate SNPeff effect for myvariant.info box

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-client#594]
The myvariant.info box is almost perfect but I noticed the following remaining issues:
1. dbSNP rsid should be a link to appropriate dbsnp page
2. EGL class is (almost?) never available, suggest demoting from front page of myvariant.info box
3. Promote ExAc adj allele freq to front page of myvariant.info box now that this is being calculated
4. SNPeff effect string length is sometimes creating display issues and should be truncated when over some number of characters as has been done elsewhere. See attached image.

![screenshot 2016-11-26 18 09 59](https://cloud.githubusercontent.com/assets/1638042/20644707/7a7f7c5c-b404-11e6-9158-c3bd276ef788.png)

**Comment by jmcmichael** [comment]
The dbSNP and OMIM links I was going to add to the hackathon list of feature requests - those will be easy to implement and perfect for someone with little skill. The others might be good too.

**Comment by obigriffith** [comment]
I'm bumping this to high priority as we could like to include a screenshot in the revised paper with ExAc adj allele freq showing a value.
