### ISSUE TITLE
Create a style guide for writing the descriptions for genes/variants and evidence items

### ISSUE THREAD

**Issue by jakelever** [genome/civic-client#602]
During the discussions at the Amsterdam event (http://pardot.agilent.com/NGS), Lynn Schriml, @kkrysiak  and I talked about creating a style guide to help new curators write appropriate short texts that describe genes/variants/evidence items. This would hopefully give a curator a good idea of what information should and should not be included.

Also, I couldn't see it in the documentation. It'd be good to lay out what are appropriate types of paper for citations. i.e. is it okay to use a review as an evidence item? Likely not, unless there is some sort of meta-analysis. But this may be good to discuss somewhere.

**Comment by kkrysiak** [comment]
This is definitely a place where our documentation needs to be stronger. I believe Lynn had suggested some example style guides to peruse to help guide this effort although I need to touch base with her again to get the specifics.

**Comment by malachig** [comment]
I agree, we should do this.

A few specific thoughts.
- We should add a general style guide for evidence statements, variant summaries, and gene summaries. This should all go on the help pages. Perhaps in the overview section of each of these: https://civic.genome.wustl.edu/#/help/evidence, https://civic.genome.wustl.edu/#/help/variants, https://civic.genome.wustl.edu/#/help/genes
- For evidence records, a review should generally not be used, but rather the primary publication where the data was actually generated should be used. One exception to this is where the review has a meta-analysis component where they are not just summarizing previous studies, but analyzing them together to come up with a consensus assertion.  For variant and gene summaries, citation of review papers is encouraged.

**Comment by malachig** [comment]
This has now been addressed and will be part of the docs PR.

**Comment by malachig** [comment]
Included in https://github.com/genome/civic-client/pull/618
