### ISSUE TITLE
Commenting on a variant group causes an error

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#61]
If you try to leave a comment on a variant group entry you get an error 
```
404 Page Not Found:

Service requested a URL that does not exist.
```
![variant group error](https://cloud.githubusercontent.com/assets/856728/6453004/555af266-c0ff-11e4-8d93-919b79c0162b.png)

**Comment by nspies13** [comment]
I experience this too.

**Comment by jmcmichael** [comment]
Fixed, closing.
