### ISSUE TITLE
Update CIViC presentation graphics

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#610]
Now that the manuscript is close to finalized, we should probably update the images we are sharing here:

https://civic.genome.wustl.edu/#/graphics

**Comment by malachig** [comment]
Similarly the data model image here needs to be updated:
https://civic.genome.wustl.edu/#/help/evidence

**Comment by malachig** [comment]
Adding high priority because we want these to be consistent when the paper goes out.

**Comment by jmcmichael** [comment]
Done.
