### ISSUE TITLE
Add options to variant advanced search

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#612]
Can you add "is empty" as a possible search criteria for "Variant Alias"?

**Comment by malachig** [comment]
Note. Variant alias appears under a few search pages, update for each of these.

**Comment by malachig** [comment]
I believe this was done?  Or are there more that were still planned?

**Comment by jmcmichael** [comment]
(backend support exists)

**Comment by jmcmichael** [comment]
Yeah, this is done.
