### ISSUE TITLE
Create a "Getting Started" page in the help docs

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#615]
Create a walkthrough of the website like we do for meetings in a page format aimed at starting to curate.

**Comment by kkrysiak** [comment]
- Examples of Curation Activities
  - Create and evidence item
    - Example evidence item from publication to EID (ALL1?)
  - Edit existing content
  - Comment on existing content
  - Submit to publication queue
  - Use the advanced search
- Sources of Curation ideas
  - Publication queue
  - Gene List
  - Greg's publication list (needs to be added somewhere public)
  - Jake's list (needs to be managed with Jake's help)
- Results
  - Profile
    - Notifications
  - Community page
  - Badges
- Other
  - Reference the paper
  - Mention CC0

**Comment by malachig** [comment]
Note, I tidied up Greg's prioritized publication list (comparison of CIViC to other resources) and added it to the civic-server repo beside our prioritized gene list.  I also emailed Jake to ask whether he is ready for us to point to the first version of a civic-mine spreadsheet that would help curators.

**Comment by malachig** [comment]
This has been added by this PR: https://github.com/genome/civic-client/pull/618
