### ISSUE TITLE
Subscribed events tab links broken

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#626]
The action ("submitted", "commented on", "accepted") on the event stream is no longer visible and clicking on the event no longer redirects to the event. 

<img width="1321" alt="screen shot 2017-01-18 at 1 16 35 pm" src="https://cloud.githubusercontent.com/assets/8527125/22079217/a4c8b168-dd80-11e6-823f-ee844ce71a02.png">

**Comment by jmcmichael** [comment]
Fixed. The suggested change logic was looking for 'revisions' instead of 'changes', probably due to a global search/replace that went a bit too far.

**Comment by malachig** [comment]
Yikes, this is likely my bad.  Sorry.

**Comment by jmcmichael** [comment]
No prob, ultimately the client should include unit and end-to-end tests that would catch issues like this.
