### ISSUE TITLE
Make subtabs or pages for each table within the Help page.

### ISSUE THREAD

**Issue by nspies13** [genome/civic-client#63]
Currently the help page is word vomit. Keep the opening paragraph and screencasts on the main page, then I was hoping for separate subtabs for each idea. Maybe:
 "The Evidence Statement"
"Evidence Types"
"Evidence Levels"
"The Trust Rating" 

This is low priority for now. But good to keep a record of.

**Comment by jmcmichael** [comment]
Done.
