### ISSUE TITLE
test pre-population of Add Evidence form values from VHL spreadsheet

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-client#632]
Might need to add Evidence Type pre-population feature to the form.

**Comment by malachig** [comment]
The add evidence form can be pre-populated with the following information:

- Gene Entrez Name = VHL
- Variant Name = value from spreadsheet ("Predicted.Consequence..p.Protein.Change")
- PubMed ID = value from spreadsheet ("PMID")
- Variant Origin = Germline Mutation
- Evidence Type = Predisposing
- Evidence Direction = Supports

**Comment by jmcmichael** [comment]
OK, this is done. Example URL w/ the required pre-population fields: 

http://127.0.0.1:3001/#/add/evidence/basic?geneId=24&variantId=55&variantOrigin=Somatic%20Mutation&pubmedId=12345&evidenceType=Predisposing&evidenceDirection=Supports

**Comment by malachig** [comment]
Awesome.  Thanks @jmcmichael .  @acoffman can you update the VHL spreadsheet with URLs for each row?

The spreadsheet is in the CIViC dropbox: CIViC/CIViC Data/VHL_Data/160106 table pubmed ID.xlsx

**Comment by acoffman** [comment]
Yup! I generated the file and shared it in Slack for a sanity check. Once everyone is happy with it, we can send it along!
