### ISSUE TITLE
can't cancel after refreshing while on an edit page

### ISSUE THREAD

**Issue by yanyangfeng** [genome/civic-client#644]
Say you click to edit an evidence item and refresh the page - you will see the same edit page, but you clicking the cancel button will do nothing (instead of taking you back to the previous view).

A similar sort of thing happens when if you click to edit an evidence item, but then decide you want to edit the variant. If you try to cancel to get back to the summary page, you will end up in an endless loop, flipping between the edit evidence and edit variant views.

**Comment by jmcmichael** [comment]
The cancel button implements the same behavior everywhere it appears, which is to navigate to the previous state using ui-routers $previousState.go() command. Reloading the browser refreshes the application, thus wiping out the previous state history.

It might be better to use the browser's history instead, as I believe that will remain consistent through a browser refresh.

**Comment by jmcmichael** [comment]
Done, thanks @yanyangfeng!
