### ISSUE TITLE
Add pmcid as searchable entity in evidence advanced search

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#660]
Promotes open access articles, allows searching when found via PMC and highlights articles that cAn be curated or evaluated when institutional log ins are not available.

**Comment by agraubert** [comment]
Something like this?
<img width="1153" alt="screen shot 2017-02-03 at 11 30 16 am" src="https://cloud.githubusercontent.com/assets/997749/22601372/35a7dd00-ea04-11e6-9c97-1e1ad3bca32a.png">

**Comment by acoffman** [comment]
I'm not sure if we currently scrape PMC ids, but i can easily add that if we dont!

**Comment by kkrysiak** [comment]
@agraubert, that's exactly what I am going for. @acoffman, I think we were using PMCID to determine whether the pub was open access or not so I believe it should be there.
