### ISSUE TITLE
Display full HGVS ID in myvariant.info detailed view

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-client#672]
Some HGVS IDs are necessarily being truncated in the variant summary myvariant.info box. These are not currently shown at all in the detailed view. For some cases this means there is nowhere that you can see the complete HGVS ID. This is unfortunate because (I believe) this is the ID by which myvariant.info is actually being queried. This makes troubleshooting challenging and also prevents comparison (for internal consistency) of the HGVS ID that we create for querying myvariant.info to other hgvs strings that we are working on.

![screenshot 2017-02-02 12 28 23](https://cloud.githubusercontent.com/assets/1638042/22562874/f8bb28ea-e943-11e6-974a-d2714a0c15cf.png)
![screenshot 2017-02-02 12 28 47](https://cloud.githubusercontent.com/assets/1638042/22562875/f8bcb318-e943-11e6-9c17-1ef0167cc63a.png)

**Comment by jmcmichael** [comment]
Details popup now displays full HGVS:

![screen shot 2017-02-10 at 2 52 41 pm](https://cloud.githubusercontent.com/assets/132909/22843978/8ebe99f4-efa1-11e6-9382-4947ec21f5af.png)
