### ISSUE TITLE
User profile images get stretched out in narrow browser window

### ISSUE THREAD

**Issue by ahwagner** [genome/civic-client#675]
Example:

**Normal window:**
<img width="947" alt="screen shot 2017-02-02 at 3 43 08 pm" src="https://cloud.githubusercontent.com/assets/811065/22569769/65c3bc8a-e95e-11e6-8e41-1ef2f775a6bd.png">

**Narrow window:**
<img width="724" alt="screen shot 2017-02-02 at 3 42 43 pm" src="https://cloud.githubusercontent.com/assets/811065/22569770/65c39110-e95e-11e6-9863-f83de87425de.png">

**Comment by kkrysiak** [comment]
In Firefox this only occurs when there are 3 or 2 users across, not for 4.

**Comment by jmcmichael** [comment]
Fixed, removed min-height that was causing the stretching.
