### ISSUE TITLE
Should we have 'sub-levels' and if so, how exactly should we define them?

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#68]
- Pros, they allow us to define evidence types with higher resolution.  For example, clinical evidence could be sub-categorized as prospective, retrospective, etc.  Similarly, pre-clinical evidence could be broken down to in vivo vs. in vitro?
- Cons, an already intimidating form for adding evidence becomes even more complex.

A related question is, where do case studies (n of 1 studies) belong?  Currently they are level B.  Should they be changed to level D?  Or a new level E?

**Comment by jmcmichael** [comment]
It feels like we might be doing some 'premature ontological optimization' by defining both categories *and* sub-categories. That we as a small group had so many slightly differing opinions about the breakdown, description and definitions of even the main categories leads me to believe that there might be an even greater diversity of opinions in the community of researchers that we'll be cultivating. 

So a good compromise might be to settle on 4-5 major levels that both fully cover and meaningfully demarcate the evidence of which we are aware, and then see what kinds of sub-categories the community naturally converges to in discussions and critiques of subsequent evidence.

Regarding n of 1 studies, if they could conceivably be in more than one category, the fact that it is an n of 1 study could be denoted by another attribute. So you'd have an evidence item that could be in any level, and you could also check an 'n of 1' checkbox.

**Comment by malachig** [comment]
Yeah, I agree with this.  Lets keep thinking about it and continue to track ideas here as to whether we need sub-levels and if so, how they might be defined.  When there are more external users we should have a better idea of how contentious our current evidence level schema is.

**Comment by obigriffith** [comment]
+1 to punting for now.

**Comment by jmcmichael** [comment]
Closing this for now.
