### ISSUE TITLE
Are gene and variant pages findable by google search?

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#680]
I think an issue related to this was closed recently. I believe CIViC variant, gene and evidence pages are being indexed Google?  However, I really haven't been able to find any evidence of this in Google searches.  The help pages and other static pages return results, but other things do not seem to.  This is not the case for some competing resources (MyCancerGenome, JaxKB, ClinVar, etc.). 

For example, try a google search for these two very specific variant names:
https://www.google.com/search?q=Y772_A775DUP
https://www.google.com/search?q=M774INSAYVM

For such a specific term, that returns almost no Google results at all, I was hoping to see CIViC results displayed.

Further evidence:
`site:www.mycancergenome.org BRAF V600E` -> returns stuff
`site:docm.genome.wustl.edu BRAF V600E` -> returns stuff
`site:civic.genome.wustl.edu BRAF V600E` -> returns nothing :(

Would be great if that search returned this page:
https://civic.genome.wustl.edu/#/events/genes/5/summary/variants/12/summary

This could be a an important source of traffic that we are missing out on.

**Comment by jmcmichael** [comment]
Hmm... yeah, we checked awhile back to see if it was indexing the entity pages and it seemed to be working then. We definitely need to get those pages back into Google. I have a solution for this, will review my notes and write up a plan.
