### ISSUE TITLE
links to revision items not working

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-client#682]
I feel like this might be an open issue but I couldn't find it. I see links to revisions, similar to those for evidence items, etc. But, they don't seem to be working. 

![screenshot 2017-02-07 21 27 43](https://cloud.githubusercontent.com/assets/1638042/22722416/6d752cc6-ed7c-11e6-9b13-6c440b3814dc.png)

**Comment by acoffman** [comment]
This was a server side issue and has now been fixed!
