### ISSUE TITLE
Make variants with only rejected evidence visible when you navigate to them

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#684]
For example, TMPRSS2-ERG variant for EID1755 (below). If you navigate to that EID, the variant isn't in the variant list. If it is displayed, it could follow the convention of the EID grid and be the red color, indicating no accepted evidence. Otherwise, these should be hidden.

https://civic.genome.wustl.edu/#/events/genes/5813/summary/variants/707/summary/evidence/1755/summary#evidence

**Comment by kkrysiak** [comment]
Here's an example of a variant with no accepted evidence items but other variants that do have accepted items. 

https://civic.genome.wustl.edu/#/events/genes/19/summary/variants/309/summary/evidence/769/summary#evidence

**Comment by jmcmichael** [comment]
Just pushed a fix for this. Also added a 'Show All' checkbox next to the variant filter that will toggle the display of hidden variants.
