### ISSUE TITLE
complete and approve Add Evidence form specification

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-client#70]
I've created a spreadsheet that contains a specification for the Add Evidence form, and will email the share link around. It contains columns for the field name, description of the field's element(s), description of the field's behavior (mostly active assistance for getting the proper value into the field), and the field's help text.

I'll be creating these for every add/edit form and these will supersede the help text spreadsheet that contains help text for all the forms. Once this is completed and approved Adam and I can start implementing it.

**Comment by malachig** [comment]
Went through the spreadsheet and made some minor suggestions.  It sounds great to me.

**Comment by jmcmichael** [comment]
Closing, the form is pretty much done except for the gene typeahead feature.
