### ISSUE TITLE
Applied Submissions Do Not Show Up

### ISSUE THREAD

**Issue by KujanL** [genome/civic-client#701]
With this specific gene and variant, MLH1 G65D, the applied revision RID 3528 (submitting versions of HGVS expression) does not show up under the Variant's HGVS Expression submissions at the top. I have refreshed several times and the revision still does not show up on this variant's main page. 

![screen shot 2017-02-24 at 2 00 13 pm](https://cloud.githubusercontent.com/assets/15361912/23319533/93352876-fa9c-11e6-80a7-4bc648f7c095.png)
![screen shot 2017-02-24 at 2 00 13 pm](https://cloud.githubusercontent.com/assets/15361912/23319535/94c986c8-fa9c-11e6-9722-61a38b06aa24.png)

**Comment by KujanL** [comment]
submitted the same picture twice. Second picture: 

![screen shot 2017-02-24 at 2 23 53 pm](https://cloud.githubusercontent.com/assets/15361912/23319610/e94a95d4-fa9c-11e6-880a-7c9f8bc81e97.png)

**Comment by acoffman** [comment]
@KujanL took a quick look and you're definitely correct; something weird happened. Digging in now!

**Comment by acoffman** [comment]
So, it looks like both suggested changes to the HGVS were accepted and one clobbered the other - this is the "expected behavior" currently which is a little lame. We're working on an alert to let users know if there is going to be this sort of conflict and allow them to choose how to proceed.

**Comment by malachig** [comment]
hmmm, this was in the back of my mind, but I didn’t think to check it.

**Comment by malachig** [comment]
I created a new revision to add the HGVS from the bot back in.

**Comment by KujanL** [comment]
Ok! That makes sense... I will close this issue.
