### ISSUE TITLE
Profile Picture Doesn't Carry Over to Name Icon

### ISSUE THREAD

**Issue by KujanL** [genome/civic-client#702]
I just noticed this with Malachi's icon that his profile picture does not appear on his name icon, despite having his profile picture uploaded. The Name Icon just has the generic design.

I think this problem just happened, because I did not notice this before. 
![screen shot 2017-02-25 at 8 07 19 am](https://cloud.githubusercontent.com/assets/15361912/23331733/823949a4-fb31-11e6-8306-703fd6a0be8b.png)

**Comment by malachig** [comment]
That is strange.  I see it...

<img width="279" alt="screen shot 2017-02-26 at 2 08 05 pm" src="https://cloud.githubusercontent.com/assets/856728/23343191/20ab45d2-fc2d-11e6-82eb-35883e53a8be.png">

**Comment by KujanL** [comment]
That's weird.. I see it now. Maybe it was just a glitch on my end. 
![screen shot 2017-03-02 at 8 45 25 am](https://cloud.githubusercontent.com/assets/15361912/23511976/aa0b78f2-ff24-11e6-803c-d500318a133d.png)

**Comment by jmcmichael** [comment]
Both of those components use the same array of image links, which ultimately come from the Gravatar service via the civic server. Kind of bizarre that you'd be seeing two different icon types. The only thing I can think of that would cause this is either a browser cache issue, or the Gravatar service was for some reason serving up two different icon types for the same email address. I'll close this issue but please file a new report if you notice it again.
