### ISSUE TITLE
Edit buttons should have mouse over text even when logged in

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-client#706]
For some users who are still getting familiar with CIViC they may be logged in but still have trouble identifying the edit button (the pencil is too subtle). We just had this experience with a clinician who is very familiar with consuming CIViC content and wanted to propose a revision to a problematic evidence item but even with verbal walkthrough (over the phone) did not easily find the edit button. A mouse-over text would help I think "click here to edit!" or something.

**Comment by jmcmichael** [comment]
Yeah it's becoming clear that the edit features are way too subtle. To implement the new flag feature's icon, I'll need to redo the edit icon placement as well, since I would like to keep them together. I'll keep in mind the need to call more attention to both of these features.

**Comment by jmcmichael** [comment]
Done.
