### ISSUE TITLE
Requirement for clinical significance not being enforced

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#708]
We just noticed a case where an existing evidence record was being edited.  Evidence type was changed from predictive to prognostic.  This resets the clinical significance.  That field is shown as required but it seems like you can submit without selecting a new clinical significance.

For example, see this revision.
https://civic.genome.wustl.edu/#/events/genes/30/summary/variants/79/summary/evidence/1215/talk/revisions/list/4202/summary#evidence

**Comment by jmcmichael** [comment]
Just pushed an update to master that includes the following updates to the edit form:
- all fields are now required
- submit button disabled if form invalid (also showing a msg below the buttons, similar to Add Evidence form)
- Clinical Significance field now will be shown as invalid after updating Evidence Type, to better prompt the user that they need to update the field
