### ISSUE TITLE
performance of infinite-scroll in evidence grid has plummeted

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-client#711]
If you perform a adv. search that returns several hundred rows and quickly scroll the grid, it has noticeable problems rendering rows fast enough to populate the grid. 

Might be due to the filter-highlight feature that was added to the cell templates. Would be interesting to revert that update to the evidence grid and test scroll performance.

**Comment by malachig** [comment]
Yeah I have been noticing a lot of touchiness in the scroll performance.  I also find, that when my cursor is over the table I get both movement in the table and the page itself scrolls up and down. The overall effect of this is that you have to fiddle a bit to move up and down in the data.  If we can't fix this, maybe revert back to pagination interface for these results?
