### ISSUE TITLE
clinical significance values are now mismatched for prognostic and diagnostic evidence types

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#712]
Not sure when this happened but you can no longer select the right clinical significance values for `Diagnostic` and `Prognostic` evidence types.  The options appear to have been swapped,

Diagnostic should be: Positive, Negative, N/A
Prognostic should be: Better Outcome, Poor Outcome, N/A

**Comment by yanyangfeng** [comment]
This looks like it's fixed now, right?

**Comment by malachig** [comment]
Yes. This appears to be good now.  Closing.
