### ISSUE TITLE
Community Page has missing blocks

### ISSUE THREAD

**Issue by KujanL** [genome/civic-client#716]
When putting my web browser into full screen, the community page has blank boxes. This problem does not exist when my web browser is not enlarged. 
![screen shot 2017-04-01 at 8 47 12 pm](https://cloud.githubusercontent.com/assets/15361912/24583799/89d5a1f6-171c-11e7-96c5-41cda9331390.png)

**Comment by malachig** [comment]
Yeah was seeing this as well.  I wonder if that image for Illumina is slightly too large?  There are other places where this problem is created by names or user names that too long.

**Comment by agraubert** [comment]
I don't think this is specific to Illumina's profile.  It looks like the same issue as #662

**Comment by jmcmichael** [comment]
The method I used to populate the grid has issues with rendering blocks of differing height, and getting the user blocks to render all at the same hight has proven to be problematic. There's a CSS feature called flexbox that has recently made it easier to write selectors to render this kind of grid, which I'll use that to refactor the grid layout.

**Comment by ahwagner** [comment]
ARGH 
![image](https://cloud.githubusercontent.com/assets/811065/25719949/c5880c2a-30d0-11e7-8cfa-1d70f288b700.png)

**Comment by jmcmichael** [comment]
Fixed in latest show-orgs update.
