### ISSUE TITLE
Can not click on publication comment in activity feed

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#720]
I saw someone commented on a publication on the landing page:

"commented on publication Weiler et al., 2015, J Thorac Oncol".

When I click on this type of event, nothing happens.  However, if I go to the "View All Activity" page and click on the same entry, it works.

Clicking the event from "OtiliaMenyhart" does not work here:
![screen shot 2017-04-03 at 11 19 54 am](https://cloud.githubusercontent.com/assets/856728/24619452/a632c222-185f-11e7-9e89-f4c77d45f792.png)

But does work here:
![screen shot 2017-04-03 at 11 20 14 am](https://cloud.githubusercontent.com/assets/856728/24619456/a945efc0-185f-11e7-8b17-f089d4c374f0.png)

**Comment by jmcmichael** [comment]
Fixed pushed to master.
