### ISSUE TITLE
civic homepage not load from China and Hong kong

### ISSUE THREAD

**Issue by sfchen** [genome/civic-client#728]
I am from China, and when I access civic, I got an access error
```
Error: [$injector:modulerr] http://errors.angularjs.org/1.4.7/$injector/modulerr?p0=civicClient&p1=%5B%24injector%3Anomod%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.4.7%2F%24injector%2Fnomod%3Fp0%3DcivicClient%0AI%2F%3C%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.7%2Fangular.min.js%3A6%3A416%0Ade%2F%3C%2F%3C%2F%3C%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.7%2Fangular.min.js%3A24%3A186%0Aa%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.7%2Fangular.min.js%3A23%3A252%0Ade%2F%3C%2F%3C%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.7%2Fangular.min.js%3A23%3A495%0Ah%2F%3C%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.7%2Fangular.min.js%3A37%3A427%0Am%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.7%2Fangular.min.js%3A7%3A320%0Ah%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.7%2Fangular.min.js%3A37%3A275%0Afb%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.7%2Fangular.min.js%3A41%3A35%0Azc%2Fd%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.7%2Fangular.min.js%3A19%3A463%0Azc%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.7%2Fangular.min.js%3A20%3A274%0AZd%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.7%2Fangular.min.js%3A19%3A83%0A%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.7%2Fangular.min.js%3A293%3A238%0Aa%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.7%2Fangular.min.js%3A174%3A399%0AHf%2Fc%40https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.7%2Fangular.min.js%3A35%3A212%0A
```
Seems like `googleapis` is not accessible here.

Error remained if I VPN to HongKong, but disappeared if I VPN to Dallas, US.

**Comment by jmcmichael** [comment]
Hi @sfchen, the error msg you're seeing indicates that angular's dependency injector is attempting to inject a dependency that wasn't instantiated during application bootstrap. We load many of these dependencies via a couple of Content Distribution Networks, including Google's. It may be that China's firewall blocks requests for these libraries, which then causes this error when Angular's injector attempts to instantiate and inject them.

Could you attempt to load the site again, and keep an eye on your browser's Network tab in its Developer Tools window? This will show you all of the network requests made during application bootstrap, including any blocked requests. If our assumptions are correct, you'll notice at least one blocked request.

We did find an online tool that purports to show how a site loads from behind the firewall, and it reports that all the CDN libraries were loaded properly:

https://www.dotcom-tools.com/DetailView.aspx?id=A10DF5DB1536454DA17B96AAD1652415:11&visit=first&Tab=TimeWaterChart

However, I understand that firewall behavior changes quite often and may not be consistent everywhere in China. Please let us know what you find! We'd like to ensure that CIViC will load and run properly everywhere.

**Comment by jmcmichael** [comment]
OK, based on [this Wikipedia article](https://en.wikipedia.org/wiki/Websites_blocked_in_mainland_China), it appears that Google's CDN is indeed blocked. We're looking into switching to an un-blocked CDN.

**Comment by jmcmichael** [comment]
@sfchen, we've rewritten the CDN configuration to a CDN that looks like it's permitted through the CN firewall. This update will be out in the next deploy sometime next week. Please reopen the issue if you continue to have issues after the deploy.
