### ISSUE TITLE
existing evidence item that uses PMID warning stays even after changing PMID

### ISSUE THREAD

**Issue by yanyangfeng** [genome/civic-client#730]
<img width="1109" alt="screen shot 2017-04-12 at 3 52 00 pm" src="https://cloud.githubusercontent.com/assets/16638655/24978929/008a68e4-1f98-11e7-8c26-70f783e01e41.png">
(taken from live site)

If you try to add an evidence item using a PMID that has been used for a previous evidence item for the same variant, we display a warning saying that someone has already referenced this study. But if you stay on this add evidence page and try to change the PMID, the warning does not disappear, even for a new PMID. Changing the gene or variant also does not make this go away. This bug could get you if you were on a curation spree and saw this warning, then decided to just move on to adding the next evidence item on your list with the same view, only to see this warning and be confused (or worse, potentially skip over the rest of your evidence items).

**Comment by yanyangfeng** [comment]
Latest commits to PR #713 should fix this. Just refreshes vm.duplicates every time the search is run - before, no response would be provided to the callback, so vm.duplicates would remain the same as before.

**Comment by jmcmichael** [comment]
Merged!
