### ISSUE TITLE
full results unavailable in search results view

### ISSUE THREAD

**Issue by ahwagner** [genome/civic-client#731]
Sometimes gene and variant names are too wide for their columns in the search results (e.g. https://civic.genome.wustl.edu/#/search/evidence/ab9f68e5-36ac-4585-be0e-bf2172947c74). In this case, I wanted to see gene names--PDGFRA and PDGFRB--but the differentiating characters are truncated and there is no tooltip on mouseover.

Additionally, there doesn't seem to be a way to resize columns, nor does the page resize beyond a certain max width, despite many fields being truncated.

There should be a way to get the full text of the presented fields when reviewing search results.

**Comment by jmcmichael** [comment]
Added tooltips back to Gene and Variant columns - will be in the next deploy.
