### ISSUE TITLE
Add evidence form creates duplicate variant entries by forcing uppercase in variant name

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#737]
For example:

If I try to add a new piece of evidence for: **P25L (c.74C>T)**
https://civic.genome.wustl.edu/#/events/genes/58/summary/variants/850/summary#variant

When I am adding evidence it allows me to specify the variant name "P25L (C.74C>T)".  This differs only by case. If I try to change the "C." to "c." it correctly suggests that variant name I want.  But when I select it the form is still populated with "C."

So when I submit this evidence it creates a new variant that differs by case only.  

I'm not sure if we should force uppercase only on this field.  If we do, I guess we should force it everywhere.  Since we are able to edit variant names and make things lowercase, it creates issues like this...

**Comment by malachig** [comment]
Others can chime in if they feel strongly, but I vote for dropping the uppercase requirement for variant name in the add evidence form.  

As curators we can encourage conventions on this.  In addition to this issue here, there are quite a few variant names where there is a strong convention with regard to use of case that we are not able to follow.

**Comment by jmcmichael** [comment]
This is a simple change in the UI, the form field CSS class just does a text-transform to uppercase on all values. There's also an uppercase transform for displaying gene and variant names in the entity tabs control. I don't recall if we discussed at all or if it was just a design decision b/c the all-caps help to emphasize the relative importance of these labels in the UI.

**Comment by jmcmichael** [comment]
The client Add Evidence form now allows variant names w/ lowercase letters. However, it appears that the server also enforces uppercase variant names after submission. I'll create a server issue to allow lowercase names on submit.
