### ISSUE TITLE
Filtering source suggestions by submitter is broken

### ISSUE THREAD

**Issue by zlskidmore** [genome/civic-client#741]
In the source suggestion queue it is not possible to filter by submitter. I am guessing this is because html elements are populating this column instead of text. We should probably fix this or remove the text box indicating you can filter by that column.

**Comment by kkrysiak** [comment]
This is a repeat of #714.

**Comment by acoffman** [comment]
Yeah, Aaron fixed this before he left, its just waiting on the next deploy which is planned for this week. Thanks for the bug report though!
