### ISSUE TITLE
add warning to edit variant/coordinate

### ISSUE THREAD

**Issue by zlskidmore** [genome/civic-client#751]
Currently no warning is issued if a user attempts to edit's a variant/coordinate and that item has pending revisions. This could lead to duplication of effort. Perhaps a warning should be generated in these cases?

**Comment by obigriffith** [comment]
Warning appears for me. Do you have a specific example where this is not working?

![screenshot 2017-05-18 09 19 49](https://cloud.githubusercontent.com/assets/1638042/26206718/318b9c54-3bab-11e7-9a82-fcf78732882f.png)

**Comment by zlskidmore** [comment]
closing, this is already implemented I just didn't notice it.
