### ISSUE TITLE
Buttons to download files on releases page redirect to home page instead

### ISSUE THREAD

**Issue by cofiem** [genome/civic-client#754]
On the [releases page](https://civic.genome.wustl.edu/releases), when I click on any button, I expect to be able to save the .tsv file.

Instead, I am redirected to the [home page](https://civic.genome.wustl.edu/home).

Could you have a look at this? Thanks.

**Comment by jmcmichael** [comment]
Yeah, definitely shouldn't be doing that. I think this might be related to changes we made to the URL scheme used to direct links to the proper states in the application. Investigating.

**Comment by acoffman** [comment]
Hi @cofiem, the fix for this has been deployed and the download links are working as expected. Thanks for your bug report and interest in CIViC!
