### ISSUE TITLE
Accepted Illumina Variant Aliases Not Showing

### ISSUE THREAD

**Issue by KujanL** [genome/civic-client#755]
For Variant V842I of gene ERBB2, Illumina suggested multiple aliases that were accepted, however are not showing up in the variant's main page.
![screen shot 2017-05-22 at 10 53 06 am](https://cloud.githubusercontent.com/assets/15361912/26314749/eb4a3f9a-3edc-11e7-928c-0d5a9a7bc0f8.png)
![screen shot 2017-05-22 at 10 53 13 am](https://cloud.githubusercontent.com/assets/15361912/26314750/ec97fb3a-3edc-11e7-8d83-0dabad0708cb.png)

I have tried to reload the page and this problem still occurs.

**Comment by jmcmichael** [comment]
Hi, looks like the client is accurately showing the variant aliases returned from the server. I've created a server issue, genome/civic-server/issues/335, regarding the problem.
