### ISSUE TITLE
Variant group displaying redundant/repeated variant name

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-client#762]
This variant group has 4 variants in it (EXON 11 MUTATION, INTERNAL DUPLICATION, L576P, and V654A). But for some reason, 3/4 of these are being displayed multiple times in the new Variant and Variant Group view. See screenshot.

![screen shot 2017-05-27 at 4 17 20 pm](https://cloud.githubusercontent.com/assets/1638042/26524481/fdfb8610-42f8-11e7-8bbb-8c457ff9e0b8.png)

**Comment by jmcmichael** [comment]
Looks like a server issue, as the variants_status endpoint used to construct the menu includes all these variants for that variant group.

**Comment by acoffman** [comment]
This was indeed a server issue - the join table had duplicate entries for some reason; I've de-duplicated the membership and the menu is working as expected now. I will use the server issue to track down where the duplicates came from in the first place!
