### ISSUE TITLE
"Flag Entity" button is making users think their variants are flagged regardless of state

### ISSUE THREAD

**Issue by acoffman** [genome/civic-client#766]
The button in its unflagged state perhaps should be more muted, not red, or less pronounced, as several collaborators thought that all their submissions were being flagged by us. (From the ClinGen call this morning)

**Comment by jmcmichael** [comment]
Updated styles for the flag button. Here's how it looks in its un-flagged state:
<img width="368" alt="screen shot 2017-06-01 at 3 32 11 pm" src="https://cloud.githubusercontent.com/assets/132909/26699492/c4fe515e-46df-11e7-8f68-ae05d0b24bac.png">

Compare to the flagged state:
<img width="425" alt="screen shot 2017-06-01 at 3 32 28 pm" src="https://cloud.githubusercontent.com/assets/132909/26699527/dc5a3660-46df-11e7-8280-a3a4258646df.png">
