### ISSUE TITLE
Order bars in stats page charts

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#769]
Can we order the category `levels` on these pages?:

https://civic.genome.wustl.edu/statistics/drugs
https://civic.genome.wustl.edu/statistics/diseases
https://civic.genome.wustl.edu/statistics/sources

Currently the colored bars for evidence level appear in a consistent order, but not an intuitive one:
C -> D -> B -> A -> E

I would change this to:
E -> D -> C -> B -> A

Screenshot examples:
<img width="1114" alt="screen shot 2017-06-01 at 12 37 40 pm" src="https://cloud.githubusercontent.com/assets/856728/26700038/be970f86-46d0-11e7-895f-6e2bdd1b6e70.png">

**Comment by malachig** [comment]
Also, while the color order used is consistent across those three pages (blue, red, orange, green yellow), the `evidence level` associated with each color changes from one plot to the next.  Also a bit confusing.

We should harmonize these on all three pages.  e.g.
E (Yellow) -> D (Red) -> C (Blue) -> B (Orange) -> A (Green)

**Comment by jmcmichael** [comment]
Updated the levels charts to sort by count, then level descending. The colors all match up now (but aren't exactly the same as specified - e.g. E is blue etc, in all the charts):

![screen shot 2017-06-02 at 4 55 21 pm](https://cloud.githubusercontent.com/assets/132909/26746312/572c06aa-47b4-11e7-95a2-fd3c5dcadac2.png)

**Comment by malachig** [comment]
This looks great!
