### ISSUE TITLE
Variant Group variants displaying multiple times`

### ISSUE THREAD

**Issue by nspies13** [genome/civic-client#77]
Something odd is going on in the new variant group evidence display. Some variants are being displayed as many times as they have evidence items (e.g. PDGFRA D842V in Imatinib Resistance).

**Comment by jmcmichael** [comment]
This looks like a server issue, the client is getting a different list from the genes/variant_groups endpoint (a new endpoint) than from the old method where it got variant groups from the gene endpoint. I've added an issue on civic-server for this (genome/civic-server#50).

**Comment by jmcmichael** [comment]
civic-server updated as of genome/civic-server#50, closing.
