### ISSUE TITLE
unable to reject source suggestion

### ISSUE THREAD

**Issue by zlskidmore** [genome/civic-client#774]
In the source suggestion queue, It appears "as a curator" as though I can not reject a suggestion. hovering over the reject button produces the stop sign and the button's alpha is lighter. I can actually click and reject, refreshing the page it seems to work so this is probably just an aesthetic issue.

**Comment by zlskidmore** [comment]
Actually correction, I am unable to reject at all. logging out and back in does nothing. Is this perhaps just an editor privelege?

**Comment by jmcmichael** [comment]
Yeah currently that button will only be enabled for Editors.
