### ISSUE TITLE
unexpected error from activity evidence grid

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#775]
<img width="1421" alt="screen shot 2017-06-15 at 2 12 49 pm" src="https://user-images.githubusercontent.com/8527125/27197709-e3ef3fba-51d4-11e7-9824-cf113747beed.png">
Malachi's suggested revision to EID4500.

**Comment by jmcmichael** [comment]
This appears to be a server error causing the alert/redirection - the variant referenced, EGFRVIII doesn't appear to exist, but the server still reports it as linkable.
