### ISSUE TITLE
Add evidence form not working properly

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#778]
We received an email from an outside user reporting a bug in the user interface.

"When I add the PMID for a paper, the author names do not automatically get populated. I tried to complete the rest of the fields and submitted the evidence, but it the system did not accept it." "...tried to add evidence for the following PMID 20150365 this afternoon but was unsuccessful."

I haven't submitted evidence yet but I am seeing the same behavior with the PMID not generating the author names.

**Comment by acoffman** [comment]
Resolved!
