### ISSUE TITLE
Support for latest civic-server release

### ISSUE THREAD

**Issue by bwalsh** [genome/civic-client#78]
Hi. Brian from OHSU here.

The latest civic-server has a number of route changes that effects the master branch of civic-client.

I was wondering how the refactoring is going to align with the latest civic-server?  Is the events-refactor branch stable enough to install?

**Comment by jmcmichael** [comment]
Yeah, the events-refactor branch is in sync with the master, as you've discovered. Once I get the add evidence page done then I'll be merging back into master, ideally later today or tonight.
