### ISSUE TITLE
Pre-alpha testing feedback (plus IE edit icon looks wonky)

### ISSUE THREAD

**Issue by bwalsh** [genome/civic-client#79]
Hi.   Just some feedback attached on some testing I was doing this morning.  
It's great watching the project unfold.  Thanks for your support

![image](https://cloud.githubusercontent.com/assets/47808/7618441/f748269e-f966-11e4-8337-c7d6ec2a724d.png)

**Comment by nspies13** [comment]
Thanks for the heads up! We noticed this yesterday and are working on a patch. 

Nick

**Comment by jmcmichael** [comment]
Thanks for catching this! Commit e4bd6f2 should have fixed the issue, please check it out. Sorry it was kind of a messy commit with some other stuff in there, the fix was in VariantsController.js, where I was sending geneIds instead of variantIds when initializing the variant state, as you suggested.

**Comment by jmcmichael** [comment]
P.S. I noticed you're running on Windows - if you have a chance could you give it a spin on the latest version of IE? I don't anticipate any issues, but we don't have many Windows machines around here for testing and I'd like to know if it run as expected on IE.

**Comment by bwalsh** [comment]
Looks good.  Correct evidence shown.


![image](https://cloud.githubusercontent.com/assets/47808/7622182/d0a1eb72-f981-11e4-89eb-34422cc63fd6.png)

**Comment by bwalsh** [comment]
IE display. Editable pencil icons are more noticeable.

![image](https://cloud.githubusercontent.com/assets/47808/7622205/314cf980-f982-11e4-919f-d73b2e0c468c.png)

**Comment by jmcmichael** [comment]
Ugh. Looks like a font issue. Could you open the IE console and see if it's complaining about missing fonts or anything font related?

**Comment by bwalsh** [comment]
IE Console log ...

```
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
File: localhost:3001
HTML1300: Navigation occurred.
File: localhost:3001
HTML1509: Unmatched end tag.
File: localhost:3001, Line: 186, Column: 7
Start:   {} -> events.genes.summary.variants.summary.evidence.summary{"geneId":"146","variantId":"552","evidenceId":"1496"}
Success: {} -> events.genes.summary.variants.summary.evidence.summary{"geneId":"146","variantId":"552","evidenceId":"1496"}
fetching url app/views/events/variants/summary/evidenceGridRow.tpl.html
fetching url app/views/events/variants/summary/evidenceGridEvidenceCell.tpl.html
fetching url app/views/events/variants/summary/evidenceGridDiseaseCell.tpl.html
fetching url app/views/events/variants/summary/evidenceGridDrugCell.tpl.html
fetching url app/views/events/variants/summary/evidenceGridLevelCell.tpl.html
fetching url app/views/events/variants/summary/evidenceGridRatingCell.tpl.html
fetching url app/views/events/variants/summary/evidenceGridEvidenceCell.tpl.html
fetching url app/views/events/variants/summary/evidenceGridDiseaseCell.tpl.html
fetching url app/views/events/variants/summary/evidenceGridDrugCell.tpl.html
fetching url app/views/events/variants/summary/evidenceGridLevelCell.tpl.html
fetching url app/views/events/variants/summary/evidenceGridRatingCell.tpl.html
Unable to assign type from data, so defaulting to string
Unable to assign type from data, so defaulting to string
Unable to assign type from data, so defaulting to string
Unable to assign type from data, so defaulting to string
Unable to assign type from data, so defaulting to string
Unable to assign type from data, so defaulting to string
```

**Comment by jmcmichael** [comment]
OK, nothing about fonts, so probably something else. Could be the 'unable to assign type from data', which might occur if the server sends a font with a mime type IE doesn't like. I'll get a Windows VM up and running this weekend so I can poke around.

**Comment by jmcmichael** [comment]
I don't have access to IE at this point so am unable to troubleshoot this issue. While getting the app working perfectly on IE will (eventually) be a goal, it's far enough down on the list of goals that I'm going to close this now.
