### ISSUE TITLE
Entrez ID not displaying correctly  (events-refactor branch)

### ISSUE THREAD

**Issue by kkrysiak** [genome/civic-client#80]
The Entrez ID is currently displaying the gene name and not the ID number. This behavior is also breaking the link. Example below.

The Entrez ID for ALK should be 238. 
Current link: http://www.ncbi.nlm.nih.gov/gene/ALK     (does not exist) 
Correct link: http://www.ncbi.nlm.nih.gov/gene/238

![screen shot 2015-05-13 at 4 19 17 pm](https://cloud.githubusercontent.com/assets/8527125/7621353/cfe91368-f98b-11e4-9ede-596d33082e32.png)

**Comment by jmcmichael** [comment]
Fixed bf9213b1bc46d5924cd33c36a53a2f57527bc13c

**Comment by jmcmichael** [comment]
Fixed in 15ec8a2588fba7bbd9b7098558b989866149c2f0
