### ISSUE TITLE
evidence level display class 

### ISSUE THREAD

**Issue by bwalsh** [genome/civic-client#83]
Our data import has extended the values for evidence level.  It works seamlessly on the back end.
However, the client displays the text as white with no background.
I wonder if there could be a neutral background (grey?) to provide better contrast

Thanks

![image](https://cloud.githubusercontent.com/assets/47808/7636910/0bba7f92-fa1f-11e4-9b61-cc56ee6ab102.png)

```
<div class="levelCell ngCellText ng-scope" style="height:30px;">
  <span ng-cell-text="" class="btn-block ng-binding" ng-class="{'levelA': row.entity[col.field] === 'A', 'levelB': row.entity[col.field] === 'B','levelC': row.entity[col.field] === 'C', 'levelD': row.entity[col.field] === 'D', 'levelE': row.entity[col.field] === 'E' }">
    FDA-approved
  </span>
</div>
```

**Comment by bwalsh** [comment]
The same issue occurs in the evidence summary section:

![image](https://cloud.githubusercontent.com/assets/47808/7637159/c21306dc-fa20-11e4-991c-d25ef6922b30.png)

```
<td class="value">
            <span class="levelBadge ng-binding" ng-class="{'levelA': evidence.evidence_level === 'A', 'levelB': evidence.evidence_level === 'B','levelC': evidence.evidence_level === 'C', 'levelD': evidence.evidence_level === 'D', 'levelE': evidence.evidence_level === 'E' }">
              FDA-approved - response
            </span>
          </td>
```

**Comment by jmcmichael** [comment]
We can and probably should have a readable default style for that cell. But are you sure you want to denote FDA approval as an evidence level? We intended those to be a qualitative assessment of clinical evidence, and FDA approval didn't seem to quite fit as an attribute of a study - it's more an attribute of a drug, unless I've misunderstood something.

**Comment by malachig** [comment]
I guess I can kind of see this.  Right now a mutation-treatment relationship from the literature that happens to be FDA approved should be considered level A, but we don't strictly require that level A evidence be FDA approved.  There probably are diagnostic and prognostic tests in addition to predictive evidence types that are FDA approved. 

For display purposes, perhaps a short hand could be used for this new evidence level?  For example, maybe `AA`, where it is understood that FDA approval is required to achieve an `AA` status?

**Comment by jmcmichael** [comment]
An `AA` rating sounds like a good idea to me and would be easy to add to the rest.

**Comment by obigriffith** [comment]
Yeah. I expect there are going to be very few cases where a specific mutation-treatment-cancer (as documented by an evidence statement) is FDA approved. But, when there is I guess we want to document that. It would be great to get some specific examples from @bwalsh of when they would use such a status. Is it more like Josh asked that the drug is just FDA approved for use in *some* context?

**Comment by malachig** [comment]
Yeah, agreed, if FDA approval refers to the drug in any context, then this should be metadata on the drug as suggested by @jmcmichael

**Comment by jmcmichael** [comment]
At our last meeting, we decided to table the inclusion FDA approval metadata in CIViC until we have the time to explore the utility of such a feature and strategies for including it in our schema. Closing.
