### ISSUE TITLE
Switching from variant summary to variant talk and back causes drug names to be displayed incorrectly

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#85]
To reproduce:
http://127.0.0.1:3001/#/events/genes/20/summary/variants/39/summary

Then go to the variant talk tab and then back to the variant summary tab.  Drug names appear as ',,,,,,,,,,'.  Reloading the variant summary page clears that and then you can produce the weird display again by switching between these views.

On landing:
![screen shot 2015-05-18 at 10 40 23 am](https://cloud.githubusercontent.com/assets/856728/7684272/61ab0786-fd4a-11e4-956b-d561dde8577e.png)

After switching views:
![screen shot 2015-05-18 at 10 40 40 am](https://cloud.githubusercontent.com/assets/856728/7684277/6fc5d76a-fd4a-11e4-9880-278bca7c4ea3.png)

**Comment by obigriffith** [comment]
I saw this on my instance as well
