### ISSUE TITLE
Evidence item revisions not working

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-client#86]
I made some dropdown changes and edited the summary for a single evidence statement for BRAF V600E. When I go to Evidence Talk the revision is in the Log tab but nothing appears in the Revisions tab. My edits to the summary text are there. Drug ID which was N/A and I didn't change appears as "[{"id":1,"name":"N/A","pubchem_id":null}]". Maybe that is related to the issue.

![screenshot 2015-05-18 11 11 14](https://cloud.githubusercontent.com/assets/1638042/7684810/a020f4f4-fd4e-11e4-867d-e24dd451eed1.png)

![screenshot 2015-05-18 11 09 45](https://cloud.githubusercontent.com/assets/1638042/7684785/76edcf76-fd4e-11e4-8394-8586fd3df43c.png)

**Comment by obigriffith** [comment]
Actually, I see now that all evidence items have the first "Revision Applied" by admin so my revision is not being listed in either the Log or Revision tab. But the displayed text in the Evidence Talk page does reflect some of the changes I proposed.

**Comment by obigriffith** [comment]
Playing around more. It looks like this is only occurring when I use the "Apply" option rather then "Submit Revision for Review". These should still be logged and appear as revisions. They should just go directly to an 'applied' status. The issue with drug name being displayed weird on the Talk->Revisions page persists no matter how the revision is made.

**Comment by jmcmichael** [comment]
Ah, yeah - the admin apply function works differently than the normal user's submit suggested revision. The admin apply just directly updates the entity's record in the db, bypassing the whole revisions workflow, so no revision is generated. I agree this is confusing and either we should shoehorn it into the revisions flow to generate a revision event or make it clear in the UI what is going on.

I will look into the drug display bug. The client gets an array of drug names which I transform into a list string, looks like it's getting skipped somewhere.

**Comment by jmcmichael** [comment]
I created a new question issue on civic-server (genome/civic-server#52) to address the current somewhat confusing admin apply action.
