### ISSUE TITLE
Submit Revision transition, etc

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-client#88]
If I go to edit a gene summary, then hit 'Submit Revision for Review' I get a nice 'Success - Your revision...' message. But it leaves me on the same revision page and I can even hit the 'Submit Revision' button again without making any additional changes. A few things: (A) Should we leave the user on the submit revision form? I guess this is desirable if they realize they have another revision to make. But, if I understand correctly, the first revision would have to be first accepted before a second revision could be proposed without being orphaned? (B) After submitting revision multiple times, on the gene talk page I do see multiple revisions that are identical. I thought there was something to prevent submission of identical revisions. (C) We definitely need some clues so that the uninitiated user knows where to find their revision. A link that says "visit the talk page to see your proposed revision!" or such.

**Comment by jmcmichael** [comment]
I've implemented a link to the submitted revision that satisfies (C).

Regarding (A), I think you're correct: we shouldn't make it easy to just submit an identical revision. I'm not sure quite what to do - my first thought is to totally replace the form with a more extensive message like 'Success! Now here's what you can do to view and comment on your revision: ' etc. I've created issue #114 for this enhancement.

Regarding (B), if this is a bug then this qualifies as server issue. I do know that if you attempt to submit a revision that makes no changes to any of the current entity then you will get a 509 conflict error. While it makes sense that we should also warn or prevent revisions identical to other revisions from being submitted, I'm not sure if that behavior is currently implemented. I've added genome/civic-server#58 to discuss.

Closing this one as the two new issues handle concerns A and B.
