### ISSUE TITLE
Clinical significance options (edit evidence) should change depending on Evidence type

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-client#89]
I believe we decided that the user should only be presented with certain clinical significance options depending on evidence type when creating/editing evidence:
Diagnostic: Positive/Negative
Prognostic: Better/Worse
Predictive: Sensitivity/Resistance

**Comment by jmcmichael** [comment]
Yeah, I am going to implement the these reactive form fields after I get editing collections working properly.

**Comment by jmcmichael** [comment]
Done.
