### ISSUE TITLE
Quick search broken

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-client#90]
Quick search box brings up the expected options dynamically as a type. But, no matter what I select it never loads (blue progress bar gets 99% and then stuck). The same entries searched for can be navigated to with browse function.

**Comment by jmcmichael** [comment]
Note that this requires genome/civic-server@e4bd4245e26dd82827ce93b1a1113dc61b43a03d, so be sure to do a pull on your civic-server installation.
