### ISSUE TITLE
When I submit a revision for review without a comment, a dummy comment is created

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#95]
For example, I am editing a gene entry.  I make my change and I have no comment on this change.  I am allowed to submit it.  Then on the Revisions tab this proposed revision has a comment with title: `New Suggested Revision` and with text `Comment text.` 

I don't think a comment should be required.  And if none is given there probably should not be an comment entity created.

![screen shot 2015-05-20 at 4 44 31 pm](https://cloud.githubusercontent.com/assets/856728/7737314/cf4d642a-ff0f-11e4-8d9a-30ac92b0cc9b.png)

**Comment by jmcmichael** [comment]
I kinda think it's important for any suggested revision to contain a comment by the submitter as to why they made the suggestion. I had intended to make it a required field, maybe eliminating the title, and adding some help text to the effect of 'Please provide a reason for your revision.'

**Comment by malachig** [comment]
Yeah, if its required then this would help.  Right now it is pretty easy to just make you edit and hit the `Apply` or `Submit for Revision` button.  If it is required, then I would be in favor of comment only instead of comment+title so that it seems like less work.

**Comment by jmcmichael** [comment]
OK yeah I'll keep the comment box, and add some help text indicating it's a required field and what to put into it.

**Comment by jmcmichael** [comment]
OK, I've updated the entity edit comment areas. I've removed the title, and instead a title will be added with a name like 'GENE BRAF Revision Description'. This will be the first comment on the revision's summary page (subsequent comments will not have titles). I also added some help text and renamed fields to hopefully clarify the purpose of the comment field.
