### ISSUE TITLE
Download links for releases include the development server port

### ISSUE THREAD

**Issue by acoffman** [genome/civic-client#97]
On the production build, the :3000 is still included, which is causing the links to 404.

**Comment by jmcmichael** [comment]
Currently when developing, civic-server only listens on port 3000 so I need to send all requests to the server on that port. I've got a simple node proxy running that grabs all /api calls and directs them to the server on port 3000. This proxy is so simple that I don't think I can instruct it to also look for /downloads to transparently redirect to port 3000.

So I can either remove the port # from the download link and it will work in production, but then the links won't work on dev (or integration tests, if they ever get written). Or I can figure out how to proxy /downloads too, or we can figure out something else.

For now I think I'll get the URL prefix from $window.location.origin which will get 'http://127.0.0.1:3001' on dev and 'http://civic.genome.wustl.edu' on production. This will break dev but we can figure that out later.

**Comment by jmcmichael** [comment]
Just pushed an update to master that should fix this issue on production (but will break release d/l links on installations using the gulp proxy)
