### ISSUE TITLE
Links to Data Releases broken?

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#99]
From the public site I was not able to get the Data Releases URLs to work:

https://civic.genome.wustl.edu/#/releases

e.g. 
https://civic.genome.wustl.edu:3000/downloads/nightly/GeneSummaries.tsv
https://civic.genome.wustl.edu:3000/downloads/01-May-2015/GeneSummaries.tsv

**Comment by acoffman** [comment]
I think this is a dupe of #97
